### ISSUE TITLE
wishlist sync notes to grauphel

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#1]
_This is a feature request, i may start working on it once I familiarized with [FreePascal](http://wiki.freepascal.org/Lazarus_Documentation#Lazarus_and_Pascal_Tutorials)._

# Why?
- [grauphel](http://cweiske.de/grauphel.htm) is an [owncloud app](https://apps.owncloud.com/content/show.php?action=content&content=166654) that [syncs](https://wiki.gnome.org/Apps/Tomboy/Synchronization) with tomboy, tomdroid anf conboy (and replaces [snowy](https://github.com/sandyarmstrong/snowy))
- enables users to share note trees between Linux, Mac, Windows, Nokia and Android devices

# Steps
- [ ] create [JSON objects](http://wiki.freepascal.org/JSON)
- [ ] establish [TLS connections](http://wiki.lazarus.freepascal.org/fphttpclient) ([Ararat Synapse](http://synapse.ararat.cz/doku.php/public:howto:sslplugin), [ML](https://sourceforge.net/p/synalist/mailman/synalist-public/))
- [ ] implement [REST API](https://wiki.gnome.org/Apps/Tomboy/Synchronization/REST/1.0) (See also tomboy-notes/tomboy#75)

**Comment by davidbannon** [comment]
Oh, that would be so cool !
Its obviously on the list but I must confess I'm not overly keen to start it myself.
Please have a look at https://github.com/tomboy-notes/tomboy-ng/blob/master/tomboy-ng/tb_sync.pas
You will see it implements a class, TTomboySyncCustom, that I designed (in my ignorance) to be usable to make any sync model. I inherent from it to make FileSync, suggest thats its a good start.

We might (ie probably) need to change TTomboySyncCustom as a network sync evolves. But I did try to think REST as I did it. It has no GUI, thats done in SyncGui and dead easy.

Be more than happy to assist in any way I can but I don't see me tackling it by myself in the immediate future.
Kardan is working on some auto installs of a full Lazarus environment but my guess is you would not need much cross platform testing, so a simple install from https://sourceforge.net/projects/lazarus/files/
I'd suggest reading http://lazarus-ccr.sourceforge.net/fpcdoc/ref/ref.html

The wiki has a lot of valuable info, a lot of out of date info and a lot missing. ie, typical wiki. The forum is full of very helpful and experienced people.

And I'd suggest working in the IDE, its hand holding is invaluable with syntax and other help always there. I had not programmed (except for nasty little bash and python scripts) for 20 years !

**Comment by cweiske** [comment]
> The wiki has a lot of valuable info, a lot of out of date info and a lot missing. ie, typical wiki.

Regarding the sync: The Tomboy wiki is accurate.

**Comment by davidbannon** [comment]
Christian, I was referring to the FPC/Lazarus wiki.
If in doubt, please re-read my post.
David

**Comment by davidbannon** [comment]
Another issue listed on the (long term) todo list. Right now, I don't see any significent need or demand so I am unlikely to put the considerable effort in. Therefore will close, just to tidy up.  Feel free to reopen if you wish.

**Comment by tlvu** [comment]
Sorry to reopen this issue.  Using Grauphel has allowed me to sync cross-platform (Linux, Windows, Android).  This is a rather important feature in terms of usability.  I initially choose Tomboy over GNote for this cross-platform sync feature.  Could Grauphel support be back on the roadmap?

**Comment by davidbannon** [comment]
Long Vu, no, I am sorry but I don't see the return on the effort necessary to work with Grauphel.  A few of the reasons -
1. Grauphel is dependent on Nextcloud and installing and maintaining a NextCloud system is not a lightweight task. 
2. Its not an app that commercial NextCloud operators support. So you must DIY.
2. Tomdroid is no longer maintained, has not been for a long time. Sadly, the build process is not documented, so no one wants to take it on. As its so old, I expect getting a new version acceptable to the PlayStore would be quite a task. My own experience with Tomdroid is it has some limitations that need fixing. Sync crashes when working with Rainy (while Tomboy itself worked fine), its inability to work with notebooks....
3. Christian is indicating he is looking to disengage from Grauphel.
4. The new release of tomboy-ng provides a cross platform (Windows, Linux and MacOS) sync using Github that also allows reading and writing to your notes from any device with a browser. That's what I use to access my notes from my phone and I find it vastly preferable to the quite ugly Tomdroid sync solutions I have made previously.

My thoughts are that the problems with Tomdroid mean its very unlikely to get new users and very few people would be willing to put the efforts into building a NextCloud install just to support Grauphel.

Sorry Long Vu.

Davo
