### ISSUE TITLE
Search form: update result Xms after last input

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#10]
In Tomboy 1.15.8 the search result is updated with every key stroke. The first search takes some time, with every character it gets less.

- Another approach is only manually trigger the search, eg when "Refresh" is clicked.
- Some users might find it comfortable to automatically update the result for example 500ms after the last character has been entered.
- With many / big notes this can take time and it would hinder the user from entering text.

Either adding an option (compare the preview checkbox in gimp's or libreoffice's file picker), or turning that off automatically based on the number/size of notes would be a smart solution.

**Comment by davidbannon** [comment]
Hmm, I do understand this question but I am not sure I agree with where it leads. I, personally, hate it when a app starts searching for something as soon as you have entered a few characters. In this case, people with a lot of notes or slow hardware can be severely impacted.

I prefer to start searching when I'm ready by hitting "enter" or clicking a button.
 
I know the progressive search is the fashion but maybe I can say someone more fashion conscious than me can implement it. :-)

Seriously, I have plans for V2.0 that will include (optionally) moving the notes into a database, I'd suggest then might be a good time to look at things like this. Right now, I see it as more important to concentrate on basic functionality and stability. Making it sufficiently useful to attract a user and hopefully developer community. When we release this version 0.1, I'll make an announcement on the Lazarus forum as well as Tomboy list, that may stir up some interest.

**Comment by traumschule** [comment]
yea, let's postpone it. it's really low priority.
