### ISSUE TITLE
Feature: fonts

### ISSUE THREAD

**Issue by claybr00k** [tomboy-notes/tomboy-ng#100]
Have recently found this tool and it is working great for syncing between windows and mac computers. Thanks for the work on it.

One think I would love is to be able to specify a default particular font and specify a size for notes -ex Inconsolas 12pt.  In particular, I prefer fonts that include the strikethru on the zero to quickly differentiate between the letter O and the number 0.

**Comment by davidbannon** [comment]
Thanks Clay. Interesting idea, I think it can be done easily but not sure. Will have a play when  I return from my current travels.

Davo

**Comment by davidbannon** [comment]
OK, I have checked in code that allows user to select font used for notes. 
This allows selection of font but does not allow you to change the size of font. You can select a fixed range of sizes from the settings screen but to remain compatible with the original tomboy model (and file format) I cannot let you choose specific font sizes.
Unless you want to build the current git source, you will have to wait until the next release, will be several weeks away as I am traveling and don't have access to my Mac or Windows boxes for testing.
Davo

**Comment by davidbannon** [comment]
This feature added in 0.24
