### ISSUE TITLE
Strikeout get added to every line after chosen one

### ISSUE THREAD

**Issue by xypd** [tomboy-notes/tomboy-ng#105]
Been having issues with strike throughs on the Mac.

When I make a strike on a note on my phone and sync it to the desktop it does not always keep the strikes. And when I add them to the desktop version it break the notes and then it disappears.

Just testing this out with bullets and without, it seems without bullets it at least doesn't disappear. It doesn't show up on the mobile version.

I use an obscure mobile platform called maemo. It's run debian with a fork on gnome. You can find some info [here about Conboy](http://conboy.garage.maemo.org/)

Any idea how I can fix/work around this better?

Before
```
<?xml version="1.0" encoding="utf-8"?>
<note version="0.3" xmlns:link="http://beatniksoftware.com/tomboy/link" xmlns:size="http://beatniksoftware.com/tomboy/size" xmlns="http://beatniksoftware.com/tomboy">
  <title>Strikethrough test #1 2019-10-01 02:13:57.366</title>
  <text xml:space="preserve"><note-content version="0.1"><underline>Strikethrough test #1 2019-10-01 02:13:57.366</underline>

<list><list-item dir="ltr">This is with bullets</list-item></list>
<list><list-item dir="ltr"><strikeout>Line 2</strikeout></list-item></list><strikeout></strikeout>
<list><list-item dir="ltr">another line</list-item></list>
<list><list-item dir="ltr">And another</list-item></list>
<list><list-item dir="ltr"><strikeout>keeping it going</strikeout></list-item></list><strikeout>
</strikeout><list><list-item dir="ltr">Never ending</strikeout></list-item></list><strikeout><strikeout></strikeout>
<list><list-item dir="ltr">energizer bunny style</list-item></list>

</note-content></text>
  <last-change-date>2019-10-01T02:15:49.4510000-04:00</last-change-date>
  <last-metadata-change-date>2019-10-01T02:15:49.4510000-04:00</last-metadata-change-date>
  <create-date>2019-10-01T02:15:49.4510000-04:00</create-date>
  <cursor-position>1</cursor-position>
  <selection-bound-position>1</selection-bound-position>
  <width>617</width>
  <height>497</height>
  <x>109</x>
  <y>98</y>
  <open-on-startup>False</open-on-startup>
</note>
```

after
```
<?xml version="1.0" encoding="utf-8"?>
<note version="0.3" xmlns:link="http://beatniksoftware.com/tomboy/link" xmlns:size="http://beatniksoftware.com/tomboy/size" xmlns="http://beatniksoftware.com/tomboy">
  <title>Strikethrough test #1 2019-10-01 02:13:57.366</title>
  <text xml:space="preserve"><note-content version="0.1"><underline>Strikethrough test #1 2019-10-01 02:13:57.366</underline>

<list><list-item dir="ltr">This is with bullets</list-item></list>
<list><list-item dir="ltr"><strikeout>Line 2</strikeout></list-item></list><strikeout></strikeout>
<list><list-item dir="ltr">another line</list-item></list>
<list><list-item dir="ltr">And another</list-item></list>
<list><list-item dir="ltr"><strikeout>keeping it going</strikeout></list-item></list><strikeout>
</strikeout><list><list-item dir="ltr">Never ending</strikeout></list-item></list><strikeout><strikeout></strikeout>
<list><list-item dir="ltr">energizer bunny style</list-item></list>

</note-content></text>
  <last-change-date>2019-10-01T02:15:49.4510000-04:00</last-change-date>
  <last-metadata-change-date>2019-10-01T02:15:49.4510000-04:00</last-metadata-change-date>
  <create-date>2019-10-01T02:15:49.4510000-04:00</create-date>
  <cursor-position>1</cursor-position>
  <selection-bound-position>1</selection-bound-position>
  <width>617</width>
  <height>497</height>
  <x>109</x>
  <y>98</y>
  <open-on-startup>False</open-on-startup>
</note>
```

**Comment by davidbannon** [comment]
Hmm, it looks to me that both examples above have bad xml. 
In the first, we see -
`keeping it going</strikeout>` 
that closing tag does not have a matching opening tag I think.  I also see some overlapping tags, you know -
`<tagA>Something<tagB>else</tagA></tagB>`
That confuses a lot of xml parsers.
I know I had a lot of trouble getting bullets to work even as well as they do on tomboy-ng and thats not well at all !
Where was your first example made ?

I have tried to make tomboy-ng very tolerant of bad xml, it can read many files that Tomboy ignores. But I index the file list using "off the shelf" xml parsers and they will probably reject bad xml like you have there. But if you load such a note in single note mode, it goes straight to my parser and is not indexed. As the on screen content is not in xml, what you see on screen **should** be resaved as good xml no matter how bad it is to start with, as long as you can see it.
David

**Comment by davidbannon** [comment]
Hmm... not sure that very promising !   If the bad xml originated in Conboy, then it really must be fixed in Conboy's code. Might mean you have build a build environment, not easy on your maemo device these days I'd expect. With Mono somewhat out of fashion and all.

Be heaps easier to fix if the bad xml originated in tomboy-ng, maybe you should start again just to make absolutely sure ?  Make your test document in tomboy-ng and check carefully for overlapping tags, if its starting there, relatively easy to fix.
Sigh ....

**Comment by xypd** [comment]
Yeah I was thinking the same. When I get a chance I'll do another test. But this time copy it directly from the device in stead of syncing if first then compare.

So 
1. Original cowboy vers. created on the device
2. The same thing but created in tomboy-ng
3 a copy of both after synced.

Then I will post my results here.

**Comment by davidbannon** [comment]
Any further thoughts on this xypd ?  I am preparing for next release.

**Comment by davidbannon** [comment]
I guess we have to assume that this is a conboy issue.  I don't think we can help here. Well, maybe if we identified the problem, I could build in some auto correction .....
Feel free to reopen if you wish to chase that down.
Davo
