### ISSUE TITLE
Undo-redo functionality

### ISSUE THREAD

**Issue by shtalinberg** [tomboy-notes/tomboy-ng#107]
Undo-redo not worked in Mac Os
it's useful when mistake delete or change note

**Comment by davidbannon** [comment]
Agreed, I make lots of typos.
But the underlying component I use in the edit form does not support undo and honestly, I don't think I want to undertake to add it in the near future. I'm not saying it won't happen but it sure won't happen in the immediate future.
Sorry.

**Comment by shtalinberg** [comment]
without undo-redo it's stay not useful app
Easy fast editing and correction should be the main future of this app

**Comment by davidbannon** [comment]
Noted.

**Comment by monperrus** [comment]
redo after undo is much needed. what about reopening this issue?

thanks!

**Comment by davidbannon** [comment]
Crtl-Z and Ctrl-Y not doing it for you ?

Works for me .....

Davo

**Comment by monperrus** [comment]
Yes, it works, thanks.

All my other apps use Ctrl-Shift-Z for undo.

Is there a config option to remap undo to Ctrl-Shift-Z?

Thanks!

**Comment by davidbannon** [comment]
Thread reopened so we may consider ALSO using Ctrl-Shif-Z as undo ....

**Comment by monperrus** [comment]
I'm a Linux user, using Linux apps.

> I could possibly make them respond to both combinations

that would be great, thanks!

**Comment by davidbannon** [comment]
OK, this issue fixed in https://github.com/tomboy-notes/tomboy-ng/wiki/Download_Release

So closing this issue, thanks for your report.

Davo
