### ISSUE TITLE
tomboy-ng 0.24 crashes on Windows

### ISSUE THREAD

**Issue by erik-brangs** [tomboy-notes/tomboy-ng#109]
Hi,

I've tried to run tomboy-ng 0.24 on Windows. It crashes on startup with the message

>Failed to get data for value "AppsUseLightTheme" .
>
>Press OK to ignore and risk data corruption.
>Press Abort to kill the program.

I'm using a dark theme if that's any help.

**Comment by davidbannon** [comment]
Oh, wow Erik, I have assumed that if the key exists, so must AppsUseLightTheme. I only have two windows boxes to test against and, obviously, this is a windows only bug. I was so delayed with this release testing against Linux and Mac, thought Windows was too easy. Sigh...

Very sorry about this.

Davo

I will trap out that error and build a new Windows only release.  Not sure how I reliably test given both my Windows boxes don't suffer this issue. I will find a way to recreate it.

**Comment by davidbannon** [comment]
Erik, I have updated the files in the Github repo to v0.24a. That prevents this crash but did leave me wondering how to react if you have the DarkThemes registry key but not the expected entry. I decided to assume, in that case, you want the dark version of tomboy-ng.  Trouble is that this dark theme on Windows is still a bit ill defined, I expect they will be making changes there in the not too distance future, especially given its popularity (not with me!). 

So, please update and let me know you results.

Systems like Lazarus and LCL don't do dark with Windows at all, developers say they will look at it when Microsoft "get their act together". Its transparent on Linux and unknown to me on Mac. New Mac's do it, my 18 month old OS does not. :-)
Thanks for the prompt report !
Davo

**Comment by erik-brangs** [comment]
With 0.24a, tomboy-ng starts correctly on Windows. Thank you.

**Comment by davidbannon** [comment]
solved, sorry !
