### ISSUE TITLE
How to improve performance

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#11]
# Expected behavior

It is a nice feature to turn already entered text into a link when a new note is created. Currently this happens, when new text is entered. Downside of this is that it takes time to re-render the note on every new character.

As this feature is not time critical it should not be triggered when text is inserted, but some time after a user stopped typing. The expected behavior is to flush a mindburst into the text area without interruption and with a direct feedback about typed text to possibly correct it immediately. After that users tend to look at the text for some time to think, or to switch the window. This is the best time to rerender the text area.

# Observation

For notes with many internal links inserting text is very slow. It takes time for every insertion to appear in the text field just as long as it takes to open this note. This is even when the text typed does not contain a (potential) link.

This is related to the algorithm that checks it for possible links.

Currently tomboy-ng keep the note titles in memory. This list is updated when a user saves or deletes a note. When does tomboy-ng save? Automatically every X minutes?
The problem is that with KControls text can't be marked as a link directly without deleting the text and then inserting a link (replace function). This check happens for the immediate surrounding of the curser. What takes time is the replacement as the whole note text is rerender. Tomboy 1.15.8 shows the same effect that notes with many links take a lot of time to focus a window because in that moment it gets rendered again.

This might be an issue limited to 32bit systems.

**Comment by traumschule** [comment]
I just tested a 32bit version in linux without debug symbols/heaptr and it was smooth as Tomboy NG 1.15.8. I leave it open to eventually discuss performance.

**Comment by davidbannon** [comment]
OK, that makes sense then. The debug symbols and particularly heaptr really slow it down, heaptr records every memory allocation and then tests it to see if its been handed back, very labour intensive.

**Comment by davidbannon** [comment]
My own tests on an single core atom powered netbook with one gig ram is that performance is not really sufficient. But I stopped using this box a few years ago because other things were so slow, browsing the ABC News site was painful.

**Comment by davidbannon** [comment]
I think that, for now, performance is adequate. While we will have to watch feature creep and watch for opportunities to help people on low power hardware, this is not, now, an issue.
So, closing issue.

**Comment by davidbannon** [comment]
But remembering to press the "close and Comment" button ....
