### ISSUE TITLE
Dark mode not properly picked up on autostart

### ISSUE THREAD

**Issue by aguador** [tomboy-notes/tomboy-ng#110]
Running 0.24 on MX Linux (XFCE 4.12.3), 64-bit fully up to date, Spanish language interface.

How to reproduce:

With dark mode set:
1. Set tomboy-ng to autostart from the XFCE configurations (adds "Notas tomboy-ng.desktop" to ~/.config/autostart) [The name of the .desktop file gets translated?!?]
2. Close session / reboot
3. Sign in

Expected behaviour: Tomboy starts in dark mode, i.e., splash appears with dark theme

Actual behaviour: Tomboy starts with a mix of light and dark modes. Splash has "Do not show at startup" in white and almost white. Opening the Search form the notes and filter panes are white with black text, other elements dark with white text. This applies whether starting from the Splash or the systray. Note that the systray popup appears in dark mode. This behaviour holds across three dark themes tested.

If tomboy-ng is exited and started manually (menu, Alt+F2), it behaves as expected.

tomboy-ng 0.24 running on Mageia with Enlightenment DE behaves as expected on autostart, no matter if it is first or last in order of execution (which can be controlled with E!).

I suspect that this is an XFCE issue, but it seemed worth reporting. It seems strange that the splash should appear (usually) just before the DM screen has disappeared. Being able to delay exec may work, but I do not see how to accomplish this in XFCE. I have played around trying to delay by adding "-p XXs" to the autostart (as here [https://forum.manjaro.org/t/xfce-how-to-add-an-autostart-delay-to-a-program/6961/3)](url) to no avail (tomboy-ng starts and quits after XXs!).

David, if you or anyone else can suggest a way to delay startup, I will give it a try.

I would also be interested to know if other users can reproduce this behaviour.

**Comment by davidbannon** [comment]
Thats an interesting one !  As you suggest, it looks to me that XFCe is starting tomboy-ng beforethe Desktop is ready to tell tomboy-ng all the colours it should use.

We can test that by have XFCe start a script that starts tomboy, perhaps after 5s

#!/usr/bin/bash
sleep 5s
tomboy-ng

Hmm, what else ?  The command line switch --dark-theme is windows only, as Linux apps get all that info from the desktop, would seem a bad idea to manually override it.

I don't think I can build in an optional slow start, because Lazarus is all about its GUI, the opening window is the first thing it does.

Davo

**Comment by aguador** [comment]
Yes, even a 1s delay allows the theme to be picked up. (With 1s the tomboy-ng splash still appears just ahead of the wallpaper, but with the theme.)

For autostarting via -ng settings, perhaps it is possible to add a delay in the cfg file via settings?

It is too bad that the "-p XXs" added to the XFCE autostart does not work. I suppose that the delay could be added to the .desktop file [https://www.tomi.cat/2016/02/solucio-la-icona-de-megasync-que-no-es.html](url), but I don't know how you could control that from your end.

**Comment by davidbannon** [comment]
OK, I have added a command line switch, --delay-start, that waits 2 seconds before it proceeds to load all the other forms.  So, for now, that does involve editing the startup desktop file.  If this seems a good idea, I think I could make that the default behaviour when being autostarted.
Davo

**Comment by aguador** [comment]
Will test it out when I have time. I still have XFCE 4.12 so it will be interesting to compare than and the update to 4.14. I may see if I can test in Mageia XFCE as well. I find it weird that ng should load even before the the DM screen has been changed to the DE.

**Comment by davidbannon** [comment]
any further thoughts on this topic ?

**Comment by aguador** [comment]
At the moment no. I just tested with 0.27 and the same: the delay-start switch does not seem to allow the theme to be picked up even though testing in a normal start there is an delay. The only thing that works with MX Linux 18.3 is the separate bash script to delay autostart. No idea why. When I get around to MX Linx 19 will test again. I think this is just a hopeless quirk with either MX or at least the version I am running.

**Comment by davidbannon** [comment]
OK, that surprises me. I guess we'll need to rely on the script model. 
I'll make a note of that on "Known Issues" .......

**Comment by davidbannon** [comment]
We will have to mark this one "unfixable".

**Comment by aguador** [comment]
I know this is closed, but just to close the loop: after updating to MX Linux 19 with XFCE 14.4, this issue went away. Dark theme now properly picked up on autostart with no delay needed.

**Comment by davidbannon** [comment]
OK, I will remove that delay code in that case, its ugly and, as it is at present, untested !

I have a totally new startup model for 0.29, an all command line unit that processes command line switches. It has that delay there, before any GUI components are loaded. I expect it would work but if not needed, its messy and should go !

Thanks.
