### ISSUE TITLE
cannot access notes in synced directory

### ISSUE THREAD

**Issue by EbStewart** [tomboy-notes/tomboy-ng#112]
help! I tried to change my tomboy notes dir a local dir that is synced to a cloud service. I did something stupid to the manifest.xml and cannot open my notes in that directory. Instead It opens a few old notes I no longer need. I've apt-get purged and reinstalled, rooted around in .config, .local/share, and nothing works.
![image](https://user-images.githubusercontent.com/52795868/67644620-dcc6e900-f91a-11e9-9301-61bbe6d81526.png)

**Comment by davidbannon** [comment]
OK Ebon, I reckon there is a very good chance we can find them all.  Firstly, is there the expected number of files with a .note extension in /home/ebon/.local/share/tomboy ?

I guess you have not been taking tomboy-ng snapshots ?

Anyway, if you see the right number of files, please firstly copy them all somewhere safe, make a dir off your home dir and copy the notes there. eg
```
cd 
mkdir tomboy-safe
cp .local/share/tomboy/*.note  tomboy-safe/.
```

If thats all OK, you could, just to set your mind at rest, fire up tomboy-ng, set its notes path to that directory and you 'should' see all your notes. Don't do any sync or anything from there, we are just looking to make sure they are there at this stage.

Davo

**Comment by davidbannon** [comment]
Oh, one more thing, lets grab the backups too !
```
mkdir tomboy-safe/Backup
cp .local/share/tomboy/Backup/*.note  tomboy-safe/Backup/.
```
just to be safe ....

**Comment by davidbannon** [comment]
No answer from Eben.
A careful read of his post indicates to me that is using Tomboy, not tomboy-ng so perhaps he realised he has posted to wrong issues line ?
