### ISSUE TITLE
tomboy-ng-setup-0.24a.exe false error: MSVCP140.dll is missing; etc

### ISSUE THREAD

**Issue by caganer** [tomboy-notes/tomboy-ng#114]
1) throws missing dll error 

"The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem."
In fact it does start and one can then set basic options (Windows 7 SP1 Home Premium x64), I installed as Admin to a different directory from the default.

2) welcome options setting gives choice of notes folder but not of settings file location.  Suggest alternative of an archive/portable option for MS Windows.

3) just installed and don't yet know if this is supposed to provide a hierarchical display but if it does the beginner has no ready means of knowing how to create and.or display a tree structure.

4) import of rtf would be good to enable use of output from The Guide (MS Windows, unmaintained for 11years), which I've used for years but find it now fails text searches on some dbases and on one dbase despite being readable and writable it also then crashes the program. Great application otherwise btw.
https://sourceforge.net/projects/theguide/reviews

**Comment by davidbannon** [comment]
Thanks for that report Caganer.  Can you please clarify for me at what stage you are getting that missing DLL message, during install or running of the app ?

From what I can find, MSVCP140.dll is a Microsoft Visual C++ thing, I am pretty sure tomboy-ng does not need it and would be surprised if the installer needs it. So, a mystery.  I test tomboy-ng on two windows systems, one is a Windows 10 install that is used for nothing else so 'should' have no extra DLLs installed. The other is quite old and may have, over its long life a few starange things put on there.  I'll check to see if either have that DLL.

The app needs to know where to find its setting as it starts so allowing the end user to change it during running is a bit risky. However, there is a command line option to do so. On windows, easyist approach is to make a shortcut and set the executable name to include the switch.

Not sure exactly what you mean by hierarchical here. There is a search screen (choose Search from one of the menus or set it to open by default) and it shows, initially, a full list of all notes, but only a flat list. You can organise your notes into 'notebooks', and clicking a notebook name filters the list.

Importing RTF is possible and something I have looked at but found that the RTF specification is so broard that few application can, with any certaintly import all RTF files you may come across. Tomboy-ng will always import its own files but may not like an RTF file built elsewhere. From memory, code is still in there, try importing from the command line -
<path-to-tomboy-ng>tomboy-ng filename.rtf <enter>

**Comment by caganer** [comment]
Thanks for that. 

Instal error message: The error message was thrown during instal (to non-default directory, something instead like c:\bin\outline\tomboy-ng) but the setup screen permitted choice of options and the program then ran without issue. I've since removed it and reinstalled and can't reproduce the error message nor can I see anything in Windows logs. 

Hierarchical view - if you go to (for example) https://alternativeto.net/software/the-guide/
and click on the still live thumbnail you'll get an example of what I meant.

Importing rtf etc: I see "The Guide" comes with a cmd utility gdeutil.exe which converts its dbase format *.gde to xml: e.g. the following although I've not tried importing the xml into anything yet:
C:\bin\Outline\Guide>gdeutil.exe --action=export --format=xml database.gde

**Comment by davidbannon** [comment]
> error message was thrown during instal

Well, thats pretty weird. I can find no reason to believe that InnoSetup itself (a product I use to make the installer) requires that particular DLL. tomboy-ng does not. My Windows knowedge does not extend to being able to list required DLLs (as I would use ldd), some research indicated ...
> Hierarchical view -
 
Yep, understand. At present, I am keeping, as much as I can, a look and feel that matches the original Tomboy. However, I do not think thats a long term constraint. A more modern interface (and other aspects such as data store) will certainly come but only when I declare "Tomboy Replicated". 
>Importing rtf etc:
 
I suspect that importing into tomboy-ng may be more successful from RTF than XML as things stand at present. The Tomboy Note XML Standard is quite idiosyncratic, I doubt you would achieve what you want using XML. On the other had, a dedicated XML imported could be built that would probably do quite a good job. Happy to help if you want to try your hand.

**Comment by aguador** [comment]
> > error message was thrown during instal
> 
> Well, thats pretty weird. I can find no reason to believe that InnoSetup itself (a product I use to make the installer) requires that particular DLL. tomboy-ng does not. My Windows knowedge does not extend to being able to list required DLLs (as I would use ldd), some research indicated ...
> 
Perhaps not so weird. I just did a quick check on my old Win7 install and see that this file has a 2017 date -- well after I stopped allowing the OS to connect to the Internet or update. I had to look for an updated verseion of the file and install it as the older version would not allows the LibreOffice installer to work. It may be that caganer had either an older version of the file or a corrupted one.

**Comment by davidbannon** [comment]
Hmm, the thing that surprises me is that InnoSetup is a Delphi app, so based on Object Pascal, just like tomboy-ng.  And that dll is a Microsoft visual cpp thing. But yes, I agree it should be installed on a typical Windows install.

**Comment by caganer** [comment]
In my case the machine I installed on (Windows 7 SP1 x64) has not had any MS Updates since September 2018.
Just prepping for early 2020  ;)

**Comment by davidbannon** [comment]
Still a bit of a mystery, we have to assume more recent versions of Windows do have this DLL.
Note that it does not seem to be actually required, just reported to be. Sigh.
Closing issue as new release out soon.
