### ISSUE TITLE
Scaling and collision issues on HiDPI display

### ISSUE THREAD

**Issue by awmottaz** [tomboy-notes/tomboy-ng#115]
I'm running Linux Mint 19.2 with a HiDPI monitor. My display scaling is set to double. In v0.24 of Tomboy, the windows open too small, and the text collides with interactive elements such as dropdowns. You can also see that the buttons get squashed together.

![Screenshot from 2019-12-10 13-09-29](https://user-images.githubusercontent.com/17735385/70560503-52df8200-1b4e-11ea-8e26-73d8f9cfd8ea.png)

**Comment by awmottaz** [comment]
As a point of reference, the old Tomboy Notes that shipped with LM 19.2 looks quite good.

![Screenshot from 2019-12-10 13-15-33](https://user-images.githubusercontent.com/17735385/70560984-3db72300-1b4f-11ea-9a73-dcbae49fd80f.png)

**Comment by davidbannon** [comment]
Thanks Awmottaz, I agree, that looks bad !  Is that typical of all windows that tomboy-ng displays ?

I was aware of a some HiDPI issues, but thought I had more or less solved them. But the Tomdroid screen, being quite experimental, may have missed out on that treatment. Images of some of the Settings screen would be useful.  tomboy-ng, as a policy, provides a lot of settings, I believe in allowing the user to decide but that does make screen clutter a major issue.

Background : I have a couple of users who have oversized fonts set (due to sight problems) and they did experience the same issues as you have just reported. The version of tomboy-ng you are using depends on GTK2 and and the GTK2 libraries I am using do not handle scaling as well as we'd like too.  The next release will include a QT5 and, just possibly, a  GTK3 version, both of which might be better at scaling too. But no matter how well they scale, clutter is an issue !

**Comment by awmottaz** [comment]
Yes, this is typical. Please do write a GTK3 version! Here is a screenshot of the default windows when I open new note, search, about, and settings from the panel launcher.

![Screenshot from 2019-12-11 07-53-31](https://user-images.githubusercontent.com/17735385/70627272-8cb29600-1beb-11ea-92c7-8ca2aa311940.png)

And here are screenshots of each tab in settings, after resizing the window.

<details><summary>Basic</summary>

![Screenshot from 2019-12-11 07-55-39](https://user-images.githubusercontent.com/17735385/70627425-d26f5e80-1beb-11ea-8309-c2fbe808c882.png)

</details>
<details><summary>Notes</summary>

![Screenshot from 2019-12-11 07-55-49](https://user-images.githubusercontent.com/17735385/70627426-d26f5e80-1beb-11ea-974e-861b344166db.png)

</details>
<details><summary>Sync</summary>

![Screenshot from 2019-12-11 07-56-00](https://user-images.githubusercontent.com/17735385/70627428-d307f500-1beb-11ea-90c4-eef281257f88.png)

</details>
<details><summary>BackUp</summary>

![Screenshot from 2019-12-11 07-56-11](https://user-images.githubusercontent.com/17735385/70627430-d307f500-1beb-11ea-91f1-9dcf8701597c.png)

</details>
<details><summary>Snapshot</summary>

![Screenshot from 2019-12-11 07-56-23](https://user-images.githubusercontent.com/17735385/70627431-d307f500-1beb-11ea-9189-e2c1c9f228a7.png)

</details>
<details><summary>Spell</summary>

![Screenshot from 2019-12-11 07-56-34](https://user-images.githubusercontent.com/17735385/70627432-d307f500-1beb-11ea-8ee2-800e30e798ac.png)

</details>

**Comment by davidbannon** [comment]
Yeah, I agree it looks horrible.
I don't quite understand why its so bad however.  I use a HiDPI screen myself and it looks fine. I think I need to try and understand this business a whole lot better.   I might make a small app that displays some of the underlying numbers involved with HiDPI, that might help me understand how it should work. If you don't mind, I will, at some stage, ask you to try the same app and send me the results please ?

One question, does your desktop use Wayland or XOrg ?   I recently did some work with the GTK3 LCL libraries and found that under Wayland, it appears these decisions are taken away from the app (and app designer) - not sure just what that means either .... 

Davo

**Comment by awmottaz** [comment]
>If you don't mind, I will, at some stage, ask you to try the same app and send me the results please ?

Of course! Glad to help how I can.

>One question, does your desktop use Wayland or XOrg ?

XOrg

>another question awmottaz, it seems to me the problem is, effectively, either that the text is too big or the windows its displayed in is too small. Discuss.

The initial size of the window is too small. The text size is good, but it seems that although the text scaling factor is picked up by the application, none of the widgets are resized to account for this text size, resulting in the text that is squashed together or cut-off. In other words, the text size seems to be the only dimensions that are properly scaled.

**Comment by davidbannon** [comment]
OK, here is a zip file, sure you will have unzip on your system. Please run it, be interesting to see a screen dump of it as it starts up and  a second one of it running full screen please.
If you have something handy to measure with, I would like to know the physical height of the line that claims to be 72 point, measure from top of 'H' to bottom of the 'p' or 'q'.

One more question - do you override the OS setting for HiDPI with a manual figure you prefer ?

Thanks for your help.
Davo
[hidpiTest.zip](https://github.com/tomboy-notes/tomboy-ng/files/3958470/hidpiTest.zip)

**Comment by davidbannon** [comment]
And, if you are feeling brave, attached is a (very raw) test version of the next release.  It has a library feature relating to HiDPI turned on that seemed to make no difference to my tests on Linux but you are getting quite different results than me.

No install needed, just unzip into your home directory and run it. (Hmm, you may need to set its executable bit, don't remember.).  It will pick up your existing tomboy-ng settings. It is full of untested code so be careful. In particular, it has a whole lot of new (and simplified) code relating to startup. And it has new code to detect a second instance of tomboy-ng, now the second instance just switches to the first instance showing its search box. Mainly stuff to help people using distros that refuse to show the tray icon.
Davo
[tomboy-ng-hidpi.zip](https://github.com/tomboy-notes/tomboy-ng/files/3958538/tomboy-ng-hidpi.zip)

**Comment by awmottaz** [comment]
For my setup, I have UI scaling set to double (on Linux Mint, `Settings > General > User Interface Scaling = "Double (Hi-DPI)"`). I also have font scaling set to 1.3 (on Linux Mint, `Settings > Font Settings > Text Scaling Factor = 1.3`).

No matter the settings, these settings alone result in a different physical size of things between my laptop monitor and my external monitor (things are larger on the external monitor). So I use `xrandr` to scale my external monitor with

```
xrandr --output HDMI-0 --scale 1.2x1.2
```

That being said, I'm not sure how helpful the physical size measurement will be. HiDPI displays don't all have the same pixel density.

### Running `hidpiTest`

<details><summary>Initial run. Distance from top of "H" to bottom of "p" is 31mm.</summary>

![Screenshot from 2019-12-12 20-00-28](https://user-images.githubusercontent.com/17735385/70763593-3b54f480-1d1a-11ea-8de2-698c7dfefd4f.png)

</details>
<details><summary>Full screen. Text size did not change.</summary>

![Screenshot from 2019-12-12 20-04-28](https://user-images.githubusercontent.com/17735385/70763703-a56d9980-1d1a-11ea-8435-fd7e85ff9fcd.png)

</details>

### Running `tomboy-ng-hidpi`

<details><summary>This is definitely improved!</summary>

![Screenshot from 2019-12-12 20-08-21](https://user-images.githubusercontent.com/17735385/70763860-39d7fc00-1d1b-11ea-9205-81bd34dd56ea.png)

</details>

**Comment by davidbannon** [comment]
Hmm, looks like you have just found a reason to turn on that seting on !  I was leaving it off in the belief that if I could not see it doing anything, I could not be sure of what it would do.
4600 pixes wide screen ?  Wow, thats a seriously large resolution !
From what I see on your attached images, you now get pretty much the same 'experience' that I do.  Would you consider that a solution ?
If so, I will turn that setting on for the next release but will need to do some testing to make sure it does not break anything else.
If you wish to keep using that one, perhaps you should just copy it over your existing binary. But remember its quite possibly buggy, you have to promise to tell be if anything unexpected happens ...

sudo cp tomboy-ng-hidpi /usr/bin/tomboy-ng {enter}

**Comment by davidbannon** [comment]
Forthcoming release 0.25 will have this feature 'on'. Hope that is a good thing ....
