### ISSUE TITLE
please reopen unwelcome welcome window

### ISSUE THREAD

**Issue by EbStewart** [tomboy-notes/tomboy-ng#117]
David Bannon, you  closed #116 because you didn't get my reply. However
I did respond, by email, in reply to your email Apparently that doesn't get through to you. Here is the text I sent:

"Ok, I did as directed:

    Hover the mouse over the error messages and it tells you to go to settings, Snaphots and click Recover. Read the intro screen, take a safety snapshot, click "Existing Notes" tab. If you are sure you don't need the bad note, delete it or double click it to take things further.
    FormRecover window said there was one bad note. I deleted it, but saw, upon fiddling, that there were a number of notes that wouldn't open. Neither would they open from the Search window. So, I made the search window bigger so I cold see the file names, for each unopenable note, opened it with notepad++, made a small change and saved. Some of them became opened, I think but not all of them. (I did it hours ago. Sorry I didn't document anything at the time.)

I did not finish doing the above for all unopenable notes.

In any case, the FormRecover Window says there are no bad notes, the splash window does not show at startup if that box isn't checked, which is different and better, but if it does start with splash, the app crashes when the splash is X-ed closed.

So that is still buggy."

Now I will add a different bug, that one can't cntrl+shift+arrow key (any) to select blocks of text, although cntrl+arrow,shift+arrow (r & L only), home+arrow and end +arrow do work as expected.

**Comment by davidbannon** [comment]
Ed, I have reopened the other ticket, lets treat this one as dealing with the keyshortcut issue that you mention ?
Always good to try and keep to one ticket, one issue. Avoids issues being glossed over.

On my system Shift-Arrow moves and selects, I think you agree. What is it you expect Ctrl-Shift-Arrow to do ?

Many of these keyshortcuts are defined in the underlying KMemo component (think of it as a library) and as its cross platform, there are issues of the various platforms not agreeing on what should happen.

Davo

**Comment by davidbannon** [comment]
Ah, another user has also asked for Ctrl-Shift-Arrow, apparently it should select a word at a time. I have committed changes to make it do so, next release, should fix that for you.
Davo

**Comment by davidbannon** [comment]
OK, that shortcut now exists in v0.26
Thanks
