### ISSUE TITLE
name of QT5 pascal library is inconsistent in rpm

### ISSUE THREAD

**Issue by davidbannon** [tomboy-notes/tomboy-ng#125]
dajoked, in #121 has noted a problem with RPM install of Qt5 version.
Seems that the RedHat library is called (lib)qt5pas1 but OpenSuse uses libqt5pas
I suspect openSuse is correct but alien converts from (the possibly also incorrect) libqt5pas1 that the deb world uses to suit RedHat.

**Comment by dajoker** [comment]
In case it helps, here is some information on creating cross-distro spec files:

https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto

**Comment by davidbannon** [comment]
I suspect, but have not had time to try yet, that rpm allows me to mention the name of what a package provides instead of the actual package name. In both cases, Fedora and openSuse, the libraries declare they provide libqt5pas.so.1.2.6 - thats a touch more specific than I like but might be the answer.
Given time.....
Davo

**Comment by davidbannon** [comment]
Becoming messy.  The rpm lists a dependency of libQt5Pas.so.1 - that is the actual library name, not the package name. Thats how it should be. So, why was openSuse worried about the difference in package name ? The lib is named  libQt5Pas.so.1 in all packages.

For the record, Alien does not pass rpmbuild a list of dependencies via the spec file. I suspect rpmbuild determines the necessary libraries itself, directly from the binary. While I can disable that process, I then need to manually maintain a suitable list. Maybe thats a good thing, I can prevent installing on older and flakier Qt ?

**Comment by davidbannon** [comment]
Right, back on my openSuse Leap, lets look at the dependancies that tomboy-ngQt thinks it has -
```
rpm -q --requires ./tomboy-ngQt-0.25-2.amd64.rpm <enter>
libQt5Pas.so.1
....
```

OK, that says we need something called libQt5Pas.so.1   Lets see if we can find that something :

```
rpm -q --whatprovides libQt5Pas.so.1 <enter>
no package provides libQt5Pas.so.1
```

Thats rather surprising. I happen to know that there is a package called libQt5Pas1 that might be able to help us, lets see : 

```
rpm -ql libQt5Pas1<enter>
/usr/lib64/libQt5Pas.so.1
/usr/lib64/libQt5Pas.so.1.2
/usr/lib64/libQt5Pas.so.1.2.6
```

Ah, thats exactly what we want.  If I can find it that easily, whats wrong with "rpm -q --whatprovides " ? 

I am rapidly loosing respect for openSuse .......

**Comment by davidbannon** [comment]
OK, much of this is related to the way various distros have named the libQt5Pas library package (fortunately, the library is named consistently).  While I have triggered off some processes that may improve things, it won't happen quickly. I have also tweaked the install kits so they are less susceptible to this problem.
About all I can do.
