### ISSUE TITLE
Pasting carriage-return-laden text into Tomboy-ng on Linux (KDE) messes up the text

### ISSUE THREAD

**Issue by dajoker** [tomboy-notes/tomboy-ng#126]
openSUSE 15.1 (Leap) x86_64 using KDE Plasma 5
tomboy-ng 0.25.2 (GTK)

Today I was copying some data from a client who was sadly stuck on windows.  When I pasted the text into Tomboy-ng it did some interesting things randomly.  I have duplicated this using a plain old CRLF-laden text file on my Linux box, then pasted it into a new note.  notice the last 'a' is not where it belongs, and there are extra lines near the top, and if I have more data it seems to get weirder, but this made for an easy duplication and screenshot.

I also noticed that if I take the same text, remove the carriage returns from them (dos2unix command), the pasting works nicely.

I have not tested on windows because, well, that would mean I was also stuck on windows.

![image](https://user-images.githubusercontent.com/307648/71758310-32f46300-2e5b-11ea-8b3e-564b96124c2d.png)

**Comment by davidbannon** [comment]
Was this a tomboy-ng built by yourself ?  It sounds a lot like the KMemo bug fixed by my patch, kmemo_paste_text

Davo

**Comment by dajoker** [comment]
I think you're correct; only if the last line is longest do I really see big issues.  The latest build also does not show the little dots (carriage returns) all over that 0.25.2 did.  Sorry for the duplicate.
