### ISSUE TITLE
Tray icon would not respond requiring kill/restart to use again

### ISSUE THREAD

**Issue by dajoker** [tomboy-notes/tomboy-ng#127]
openSUSE Leap 15.1 x86_64
tomboy-ng 0.25.2 (GTK)

This is my  main rig, so lots of notes, but after I had written in an old note today (originally created 2016-12) I clicked on the -ng tray icon and while the main options were there (Menu, Search,Quit, etc.) the list of recent notes below was not.  No big deal, so I kept on working, and after I closed the note I had open I found that clicking on the tray icon showed nothing at all.  It was still there and seemed to be fine otherwise, but no response providing a menu on click, so not very useful.  The process looked like this, so it had been running for a couple days without major issues:

aaron        1503  0.2  0.3 828452 59640 ?        Sl   Jan03   6:53 /usr/bin/tomboy-ng

I killed (-15) and restarted and everything seems to be fine again, but I'm not sure what this might mean.  Is it because of time used, or notes used, or just data entered recently? Could it be because I opened that old note and edited it?  I just started using notebooks (one notebook per note as default for now) last night for the first time ever, so that's new too, but that was last night and not this morning.

Maybe it was random or fluky.  I'll watch for it in the future and post what I can find.

**Comment by davidbannon** [comment]
If you see this again, I would like you to first try  to restart tomboy-ng, that will tell us if the app itself has crashed and left the icon there or not. Just click its icon from your menu or how ever you normally start it.
If the app is still running, it will switch to the search form when you try a restart. If the orig instance is not there anymore, it will just start up normally and you will get a second icon. (And that will be annoying :-)  )

Davo

**Comment by dajoker** [comment]
Sure, if I can I will, but (it was probably unclear in the original description) when this happened the tray icon had no menu, so I had no way to open notes (to get to a Menu) or to access the 'Quit' option directly.  For al intents and purposes, the tray icon was just a pretty picture down there that, when hovered over, would show "tomcat-ng" (thanks KDE) but when clicked did nothing.

If there is another way to "restart it" then I could try that, but I presume you mean via something graceful like using the tray icon to quit.

**Comment by davidbannon** [comment]
By 'restart' I mean you open your main desktop menu, find the tomboy-ng icon you usually use to initially start tomboy-ng and click that.
Or grab a terminal and type tomboy-ng [enter]
As if you are trying to start a new (ie second) instance of tomboy-ng. It has code built in to prevent that happening and what that code does will be interesting.
Davo

**Comment by dajoker** [comment]
Just a bit more info, now from tomboy-ng-0.26.2 on my main rig.

I saw the list of recent notes go away, but the tray icon still showed me the menu (as originally seen above).  tomboy-ng isn't completely dead, of course, but I still tried running it again, and as you suspected the Search screen came up.  Interestingly, the recent notes list was now present again.  I searched, then closed that, and the recent notes list was gone (but the menu still worked).  Tried Search again, but this time the recent notes list stayed gone.  Closed Search and the recent notes list came back, this time to stay (so far).

Oddly, the note I am working on today, thus has recent changes, is not showing up in the recent notes list, at least not anywhere I can see it and that's unusual; usually, when tomboy-ng works normally, the latest note is somewhere in this list.

me       32442  1.5  0.3 961680 54404 ?        Sl   08:24  10:37 /usr/bin/tomboy-ng

As you can see, using 54 MiB RAM, running for over eleven (11) hours (since I upgraded this morning), and otherwise not that busy.  If it goes away entirely from the tray (or at least loses its menu) I'll try restarting and post results, but so far that has not happened (yet).

**Comment by davidbannon** [comment]
dajoker, you are aware that the recent notes list is filtered ?
If you have performed a search (in the search window) and, for example, found nothing, the recent notes list will show exactly that, nothing.  Same thing applies if you select a notebook, only the notes listed in the notebook are shown in Recent Notes.
The recent notes list should always be the 10 most recent notes showing in the seach window. Can you please check that ?  If you see no notes listed in the recent notes menu, look in the search window and see if there are any listed there ?   That might give me a hint of whats happening ....
Davo

**Comment by dajoker** [comment]
Okay, ignore my last comment then; that was/is clearly what was/is happening there.  I guess this is unrelated to the original report where the tray icon was completely stuck (no menu either).  Thanks for teaching me something new; I had no idea.  I'm not sure if I like it yet, but it's also different from how Tomboy (mono) worked, and I almost never like change at first, even when I love it later, so I'll mull this over and see how things go after a while.  Thanks.

**Comment by davidbannon** [comment]
OK, given the substantial changes to the search form, reckon this bug / issue / what ever is gone.

Davo
