### ISSUE TITLE
Notebook references lost on exit of -ng

### ISSUE THREAD

**Issue by dajoker** [tomboy-notes/tomboy-ng#128]
openSUSE Leap 15.1 (KDE)
tomboy-ng-0.25.2 (GTK)

On my main rig I set a half-dozen (or more?) notes as part of a notebook named 'Current' a couple days ago and today, when trying to search for them, I found that they were not assigned in there, but thought maybe I was just not used to the UI fully to find them there.

I opened one of the notes and added it back in, then verified it via the filesystem:

> grep '<tag>' ../.local/share/tomboy-ng/*
../.local/share/tomboy-ng/2b793191-905a-4b57-bdc5-ef5bdf492f1d.note:    <tag>system:template</tag>
../.local/share/tomboy-ng/9d3828d5-4136-4254-847b-65c6832a9107.note:    <tag>system:notebook:Current</tag>
../.local/share/tomboy-ng/9d3828d5-4136-4254-847b-65c6832a9107.note:    <tag>system:notebook:Current</tag>
../.local/share/tomboy-ng/9d3828d5-4136-4254-847b-65c6832a9107.note:    <tag>system:notebook:Current</tag>
../.local/share/tomboy-ng/B4C6300F-4EC0-48F8-8692-C90E7C7086C3.note:    <tag>system:template</tag>
../.local/share/tomboy-ng/B4C6300F-4EC0-48F8-8692-C90E7C7086C3.note:    <tag>system:notebook:Current</tag>

The one I was modifying is the first one above, with three references somehow all to the same Notebook (I still have the default of only allowing one notebook per note), so that may be a (related?) bug.

After exiting -ng it appears tht the tag was removed:

> grep '<tag>' ../.local/share/tomboy-ng/*
../.local/share/tomboy-ng/2b793191-905a-4b57-bdc5-ef5bdf492f1d.note:    <tag>system:template</tag>
../.local/share/tomboy-ng/B4C6300F-4EC0-48F8-8692-C90E7C7086C3.note:    <tag>system:template</tag>
../.local/share/tomboy-ng/B4C6300F-4EC0-48F8-8692-C90E7C7086C3.note:    <tag>system:notebook:Current</tag>

The only thing left with the 'Current' tag in it is some kind of template that apparently keeps track of the existence of notebooks.

I then fired up a VM with openSUSE Tumbleweed and (still) the Qt version of tomboy-ng 0.25.2 and decided to create a new notebook (also named 'Current') to which I would add three new notes.  I noticed that my existing (test) notes did not show up in the tray icon when clicked, but did not think enough of it until later when I also noticed multiple tomboy-ng processes running at the same time, two (2) of them (out of three (3)) with a -session argument followed by some long hex-looking string, e.g. 1028c1d320b210000157780822200000020350017_1577808223_241578
1028c1d320b210000157780822200000020350025_1577817783_394044

Maybe that's nothing to be concerned about, or at least nothing related, but I have not seen it before or since, not that I am constantly looking.

Uninstalled and installed the GTK version to avoid other issues, but I can pretty easily duplicate the loss of notebooks assignments when exiting tomboy-ng (right-click on tray and 'Quit') which is concerning, as I wonder what else may be lost.

**Comment by davidbannon** [comment]
Ahh, you are right !  I had made some changes in previous release to speed up saving note position if user has not changed it.  But that overlooks its notebook membership. 

Thats very bad !  Urgent fix required.....

Davo

**Comment by davidbannon** [comment]
Have pushed a fix, only superficially tested at this stage.
Davo

**Comment by dajoker** [comment]
I've only done superficial testing too (in Lazarus) but it is working, saving references to notebooks across restarts. I have specifically tested:

Creating a new notebook and adding a note to it at the same time.
Removing the note from the notebook.
Adding the note back to the notebook

This is all with single-notebook-per-note mode.

**Comment by davidbannon** [comment]
Ah, you must have just missed the version that marks every edited not as Open On Start even if it was closed normally before exit ?  Lucky you ! 
Fixed that, now refresh notebook list whenever a notebook is added or removed.
I'd be more than happy for you to check out a fresh copy and see what you can break....
Davo

**Comment by dajoker** [comment]
I'm not sure how that pertains to my last comment, so maybe that was intended for another thread, but I think I have seen that with 0.25.2, which is current.  I know I have seen, sometimes, where I have started tomboy-ng and a dozen notes have suddenly opened when, prior to stopping tomboy-ng (intentionally or via a crash) I had just one (1) note open.

I'm looking forward to 0.26.x.

**Comment by dajoker** [comment]
Verified fixed in 0.26 release.

With regard to the "marks every edited note as Open on Start", I saw that once just after upgrading to 0.26, but on a subsequent restart I did not have it happen, so hopefully the upgrade fixed it but had to get that one last note-open-flurry in, as it opened a dozen or so notes (it's been over a week since I restarted Tomboy-ng).

**Comment by davidbannon** [comment]
Yep, that test version you were using was marking all unedited notes it opened.  So, a note so marked must go through its open on start cycle.   Sigh.

**Comment by davidbannon** [comment]
OK, fixed in 0.26 (but at the cost of initially creating a whole lot of bugs, think I have them all now).
