### ISSUE TITLE
Shift+click does not select text from the cursor to the clicked location

### ISSUE THREAD

**Issue by dajoker** [tomboy-notes/tomboy-ng#129]
tomboy-ng code from repository as of 2020-01-12, running via Lazarus

Perhaps related to issue #120 a similar thing I am missing today is the ability to click somewhere (call it point 'a'), then shift+click at point 'b', and have the text between the two points end up selected (e.g. for copying, or typing over, or deleting, or whatever).  Currently when I shift+click somewhere the cursor simply moves to the new location without selecting anything in between.

The functionality of shift-clicking selecting text can be seen in just about every application I've used, including text editors, productivity products, web browsers, etc.

**Comment by davidbannon** [comment]
quite a lot of Kmemo's editing is driven form a single function, ExecuteCommand() around #4900 in kmemo.pas

If it tuns out there is some support there, pretty easy. There certainly is ways to get that effect there, working out how many char between current cursor and click position.  But I am not sure at what point the cursor is moved.  So, it might be "working out how many char between the previous cursor and the current one" ....

Davo

**Comment by davidbannon** [comment]
Turned out very easy .....

**Comment by davidbannon** [comment]
Fixed in v0.29

Thanks for the report.

Davo
