### ISSUE TITLE
A couple of issues with pasting text from webpages

### ISSUE THREAD

**Issue by corypanshin** [tomboy-notes/tomboy-ng#130]
I've just been collecting some quotes from webpages and have run into a couple of problems.  (This is version 0.25, Windows 7, Waterfox).

One is that it's happened a couple of times now that I pasted a quote of two or three paragraphs, closed the note, and when I reopened it the final paragraph was gone.

The other is that in one of those cases, when I repasted the missing paragraph, the quotation marks and apostrophes were all doubled.

I've been able to reproduce the error, but not consistently.  I can't spot a pattern in when it happens and when it doesn't.

**Comment by davidbannon** [comment]
corypanshin, thanks for the report.
Just to clarify, the missing paragraph problem, after you have pasted, are you sure everything you expect is there, visible, in the note ?  And its after a close / open cycle that it goes away ?  If is only some part of your paste appearing in the note immediately after the paste ?

My guess is that the browser you are using is including some html in the paste, that html is clashing with xml in the tomboy-ng standard.  But thats pretty vague !  I would really like to know how to replicate the problem....

tomboy-ng accepts only two paste formats, plain text and rtf, I'd be quite surprised if your browser is offering rtf. Perhaps as well as checking the whole paste is there, you could also check to see if you see any unexpected angle brackets ?

Davo

**Comment by corypanshin** [comment]
I haven't encountered the problem again in the last day or two.  I suspect it only affects pasting from certain webpages.  But I'm keeping an eye out for further occurrences.  One possibility is that it might have occurred when I pasted text from two different webpages into the same note.  Another is that it might happened when the page I was pasting from used blockquotes or italics.  I'll keep looking for all those things.

**Comment by corypanshin** [comment]
I have now found two notes where the final paragraphs had disappeared since yesterday.  One is from [This page](https://harpers.org/blog/2007/05/washington-insiders-lend-helping-hand-to-princess-of-uzbeks/?fbclid=IwAR1NHrI20goRpC0mVr0lVCAkQFNkpx3sZTrDHZ5A_nLiGw7mUSl7kqR6m_c)  The note in question consisted of that url, followed by a couple of lines I typed in, and then by this pasted text block.

**Comment by corypanshin** [comment]
The other note includes text pasted from [This [webpage](url)](https://www.tabletmag.com/jewish-news-and-politics/211152/trump-data-analytics-russian-access?fbclid=IwAR1f5sawgumdd0sOM2nge7h32MefBE2NIxrl3tJPtbLHb43ZmXoiGncKXJ0).  
![zander](https://user-images.githubusercontent.com/40767397/72923357-e777fb00-3d1c-11ea-98fe-2e7a06ec0fad.jpg)

**Comment by davidbannon** [comment]
Yep, I can replicate that Cory.  I am not sure why its happening but I can get the result you describe.
I think it might be one of two things -
1. embedded codes in the content messing with KControls. Something that looks like rtf code.
2. The fact that we don't have a newline at the end of content.

I am leaning towards 2) right now, I have had an issue a bit similar to that in the past, and its possibly an easier, will investigate more.

Davo

**Comment by davidbannon** [comment]
Yep, thats it. I am amazed we have not discovered it earlier, been there since day one. If you paste content that itself does not end with a newline and there is not already a newline at the end, you loose the last line of (plain) text.
You can avoid it by putting a newline at the end of of your note. Will be fixed in next release and I can cut you a new version with the fix now if you like.

Thanks Cory !

**Comment by corypanshin** [comment]
If it's as simple as hitting Enter after the pasted text, I can do that easily enough.  I'll wait for the next release to get the fix.  Thanks.

**Comment by davidbannon** [comment]
OK, this bug is finally fixed.  
And, given how long it has been there, thats a good thing !
Thanks for great bug report !
Davo
