### ISSUE TITLE
Bold Italic Underline issue on Ubuntu 18.04

### ISSUE THREAD

**Issue by nguxx** [tomboy-notes/tomboy-ng#131]
Hi,
Fist of all thanks for this great app which allow to sync with serval systems.

On  ubuntu 18.4.3  with 0.26 GTK2 I can underline, Bold, Iltalic and Highligh a some text in a new note.
But when I close the note and reopen it again only the Highligh remains, all the other features are gone letting a plain text.
And I cannot put some bold or underline again when i reopen

Same probem with the version tomboy-ng_0.26-0_amd64Qt.deb
My notes are saved on an ntfs disk, by the way, if it matter
Any idea ?

**Comment by davidbannon** [comment]
Hmm, no idea at all nguxx.  I use pretty much the same system here and cannot replicate your problem.  Does it happen every time ?  Can you experiment a bit and see if its dependent on something I am missing please ?

Next, could you open a new note, put a line of text in it, then do your underline, bold, italics and hightligh and close the note.
Now, BEFORE you reopen the note, grab a copy.
`ls -latr ~/.local/share/tomboy-ng [enter]`
That will list the new note last, copy its name and -
`cp ~/.local.share/tomboy-ng/[paste-here]  ~/Desktop/.  [enter]`
Then reopen the note to make sure it does exhibit the problem, if so zip or tar or whatever it up and paste it here please.  That might tell us if its a reading or writing problem.
Davo

**Comment by davidbannon** [comment]
Hi nguxx, are you still seeing this problem ?
I have fixed a bug that was logged at #138, I suspect your problem may be related. #138 underlying problem was a bad note, and, despite my best efforts, that particular bad note could get past my opening tests but messed with sync.  
I think you could have the same bad note.  Would you like to try a beta test version that fixes that bug ?
Davo

**Comment by davidbannon** [comment]
OK, nguxx does not seem unhappy.  I may have fixed his problem, lets hope so.
Davo
