### ISSUE TITLE
Feature request: add option to rename notebooks

### ISSUE THREAD

**Issue by aguador** [tomboy-notes/tomboy-ng#134]
At present a notebook may be deleted and templates created and edited, but I see no way to change/edit the name of a notebook, not from the notebook options in the search form or by right-clicking on the name.

Platform: Mageia Linux, 0.26 Gtk2, Adwaita dark theme

**Comment by davidbannon** [comment]
Yeah, its possible but messy. Unfortunately, the Tomboy note format says we record the name of the notebook in each note that it is a member of, not the notebook's ID.  That means I would need to open every note that is a member of the notebook and rewrite it. Slow and risky in that a powerdown mid change would leave a mess.

And that would have to be synced, to ensure that, we'd need to update the LastChangeDate, so affecting sort order.

The Tomboy note format has a LastMetaDataChange field but Tomboy did not (appear to) use it so I have not. My guess it was intended for this sort of thing.  Would be useful.

I'll look into it a bit further ....

Davo

**Comment by aguador** [comment]
That's like the process I had to go through! I created a notebook with a typo in the name. Since it had only a couple of notes, I simply created another notebook with the correct name, added the notes to it and eliminated the original notebook. Had the number of notes been greater, this would have been a real pain.

(My geometry teacher used to have what she called the cost of carelessness when one got the wrong answer as a result of a stupid computational error. That applies to mistyping a notebook name and, if no changes are allowed, this method of correcting such an error provides a good incentive for avoiding such errors in the first place!)

Now, assuming that such "costs" might evoke a certain peevishness in some users, I will offer a thought. You, of course, realise that this level of programming (OK, just about any level) is out of my league, but here goes. Why would the "notebook" not have a tomboy-ng generated name like the file name of a note? The notes would then carry the internal name (notebook name) which is associated with a string (user-assigned name), the latter string being the (editable) one displayed to the user at opportune moments. That way notes do not have to be changed, simply the master list of user-assigned strings. That means that searches would have to search that list of strings as well as all the note files, which should not be that hard. Perhaps more work is the business of how to edit the user-assigned name and if/how/when to refresh it if other notes from that notebook (or the SearchForm) are open.

**Comment by davidbannon** [comment]
Yep, thats what I meant when I said the Tomboy standard does not record the notebook ID in the note, it records the name.  Would be heaps better data management to record the notebook ID, then all we would change is the name associated with the ID. 
Other aspects do work like that.
D

**Comment by davidbannon** [comment]
OK, 0.27 allows this, but if you sync your notes, make sure you do so before renaming a notebook !

Davo
