### ISSUE TITLE
Unable to remove note from notebook in 0.26

### ISSUE THREAD

**Issue by dajoker** [tomboy-notes/tomboy-ng#135]
openSUSE Leap 15.1 x86_64 (KDE)
tomboy-ng 0.26 (non-Qt)

Today I tried removing a note from the notebook for the first time, and it is basically not working most of the time.  I'll get a video shortly, after I try with the latest code in Lazarus, but I think it should work like this:

Open note.
Click notebook icon.
Uncheck current notebook in which the note resides.
Hit 'Ok' and be done, with the notebook unchecked if the section window is re-opened.

How it actually works:
Open note
Click notebook icon
Uncheck current notebook in which the note resides.
Hit 'Ok', but then still find the option selected when going back into the selection window.

I have tried doing this from the note itself, from the note opened via a search window, with a restart of the application in between, all without reliable results.  I'm guessing fixing the bug where the notebook NEVER stayed has not prevented it from going away.

Somehow, in one test, I managed to get a note out of a notebook, but trying it again has been in vain.  I'm open to the "right way" from somebody.

**Comment by davidbannon** [comment]
Hmm, works fine for me.
How are you closing the little Notebook window ?  Are you clicking the "OK" button ?
If you click "cancel" or you close the windows via the window control, typically a [x] top right then the operation is cancelled and no change is made.  Some OSs will let you close a window like that with the ESC key too, that will almost certainly cancel.

I have just tested both GTK and Qt5 several times and cannot replicate your problem.  

Davo

**Comment by dajoker** [comment]
My test rig agrees with you, both with an RPM build as well as via Lazarus, but my main rig had the issue.  I'll see if I can duplicate it and report back.

**Comment by dajoker** [comment]
I used a new note on my main rig, and it adds/removes just fine.  Most of this notebook, including the one I am trying to remove, are old (Tomboy, non-ng).  Being curious, I decided to go figure out the XML a bit more, and this is pretty strange.  This command counts the number of times any note with 'system:notebook:Current' has that exact string within.  I have never used notebooks prior to tomboy-ng, so none of this is legacy from Tomboy, but look at some of these counts?

> grep -c -e 'system:notebook:Current' $(grep -l 'system:notebook:Current' ../.local/share/tomboy-ng/*) 
../.local/share/tomboy-ng/01cc69e9-8cbd-4070-badd-33281934f969.note:1
../.local/share/tomboy-ng/0968ce89-933c-405a-8df9-9532bd4c18f5.note:84
../.local/share/tomboy-ng/1c502652-0923-44c7-b293-0cea2e4afb34.note:1
../.local/share/tomboy-ng/252adf46-be0f-4695-be4a-b728727234e2.note:1
../.local/share/tomboy-ng/33252788-6DAA-4938-9390-588B951E2B18.note:3
../.local/share/tomboy-ng/348f866b-e756-437d-8359-3097ae9c42fc.note:14
../.local/share/tomboy-ng/46c79e46-7027-4632-9af9-258e406d79ab.note:1
../.local/share/tomboy-ng/4B5CFE09-7258-487F-B52F-2B9BF2BE7847.note:270
../.local/share/tomboy-ng/62b4d2e7-0491-47ba-9737-5e5c3b48d1b4.note:1
../.local/share/tomboy-ng/692d489a-54c0-464d-a4e4-4cb4045c28db.note:1
../.local/share/tomboy-ng/6a43f2a8-5070-4a90-8361-5357da6159f6.note:1
../.local/share/tomboy-ng/77db38a9-b606-441a-bf48-abd79e28d862.note:5
../.local/share/tomboy-ng/9471c4a9-79c8-41b9-8999-fb337d3aeaf1.note:1
../.local/share/tomboy-ng/9b1b5ed5-f74f-4462-a23c-dd0eae771706.note:1
../.local/share/tomboy-ng/9d3828d5-4136-4254-847b-65c6832a9107.note:20
../.local/share/tomboy-ng/a1445f3a-9488-4d79-894c-11b6fc0c3c3c.note:1
../.local/share/tomboy-ng/a5813600-1c3a-499d-b684-04e2f9db9115.note:7
../.local/share/tomboy-ng/B4C6300F-4EC0-48F8-8692-C90E7C7086C3.note:1
../.local/share/tomboy-ng/c6cb713f-241f-4118-955c-be313f4e9323.note:1
../.local/share/tomboy-ng/d35e7263-1101-40b6-98b9-302fdd33a62d.note:20
../.local/share/tomboy-ng/DA1312AB-CBE1-427A-89DA-2289D2C23BE0.note:1344
../.local/share/tomboy-ng/da9a378d-7b4b-4758-87e7-31c691c5f2c2.note:312
../.local/share/tomboy-ng/e0a2d87d-2503-4023-b0b3-4788525bfb28.note:312
../.local/share/tomboy-ng/f0f251ad-9cd7-460f-98a8-f7dd6d1526e9.note:6

I see this "tag" entity still in the one note that I removed from the notebook, so that also seems odd.  I guess I need to do more before/after comparison to see how this works, but these numbers seem to be a little crazy.

**Comment by davidbannon** [comment]
Please cat out ../.local/share/tomboy-ng/DA1312AB-CBE1-427A-89DA-2289D2C23BE0.note and see if it really does have over a thousand notebook references !
I have just checked my notes, I have a couple of notes with two or three of same entries so clearly something is wrong there.  But over a thousand ???
I will have to look through the code and see how this could happen.
Thanks
Davo

**Comment by dajoker** [comment]
Surely it does:

> sort ~/.local/share/tomboy-ng/DA1312AB-CBE1-427A-89DA-2289D2C23BE0.note | wc -l
1543

> sort -u ~/.local/share/tomboy-ng/DA1312AB-CBE1-427A-89DA-2289D2C23BE0.note | wc -l
172

**Comment by dajoker** [comment]
A bit more interesting stuff is I have a .note file with "Current Template" as the name, and I suspect this actually represents the tag/notebook itself, created 2020-01-04.  All other .note files with reference to system:notebook:Current were created or last-modified sometime on/after 2020-01-15, which you'll probably recognize as the date I upgraded to 0.26 to test out the fixed ability to save notes into notebook.

Also, for those notes with many <tag> references I am able to eventually clean them out, and with far fewer un-checks than 1500; I think for that note I had to try to remove it ten (10) times in a row.  I was not waiting for a save (asterisk to go away in the window header) between each attempts, so maybe I just need to be more patient and let the thing save and clear out all duplicate tags at once, but I can also clean them out myself if needed.

I guess this leaves me with:
How did I get duplicates?
Why do duplicates not all clean out at once?
Why do the duplicates clean out with fewer attempts than there are duplicates (ten (10) removals vs. 1500)?  I do not ask these looking for specific answers, but more to help perhaps guide troubleshooting by looking for patterns.

Here's another interesting twist.  I opened a note which has 270 <tag> tags within, all with the same value.  Once opened, the count of duplicates jumped up to 405.  I then went to the notebook list and unchecked it, hitting 'Ok', and waited for the note to show it was saved, and checked the count again, and rinsed and repeated until I had the following interesting output for you:

> grep -c '<tag>' ../.local/share/tomboy-ng/4B5CFE09-7258-487F-B52F-2B9BF2BE7847.note
405
> grep -c '<tag>' ../.local/share/tomboy-ng/4B5CFE09-7258-487F-B52F-2B9BF2BE7847.note
405
> grep -c '<tag>' ../.local/share/tomboy-ng/4B5CFE09-7258-487F-B52F-2B9BF2BE7847.note
202
> grep -c '<tag>' ../.local/share/tomboy-ng/4B5CFE09-7258-487F-B52F-2B9BF2BE7847.note
100
> grep -c '<tag>' ../.local/share/tomboy-ng/4B5CFE09-7258-487F-B52F-2B9BF2BE7847.note
49
> grep -c '<tag>' ../.local/share/tomboy-ng/4B5CFE09-7258-487F-B52F-2B9BF2BE7847.note
24
> grep -c '<tag>' ../.local/share/tomboy-ng/4B5CFE09-7258-487F-B52F-2B9BF2BE7847.note
12
> grep -c '<tag>' ../.local/share/tomboy-ng/4B5CFE09-7258-487F-B52F-2B9BF2BE7847.note
6
> grep -c '<tag>' ../.local/share/tomboy-ng/4B5CFE09-7258-487F-B52F-2B9BF2BE7847.note
3
> grep -c '<tag>' ../.local/share/tomboy-ng/4B5CFE09-7258-487F-B52F-2B9BF2BE7847.note
1

Interestingly it is removing about half of the duplicates each time it saves, and interestingly it jumped up at the start.

Adding a new note to this same notebook results in a single tag, and nothing seems to be changing that currently.  So curious this is.

**Comment by davidbannon** [comment]
Wow, I do not know whats happening here. Its all started since I 'fixed' the problem with notes forgetting their notebooks. 
I cannot find what causing the initial multiple entries but I can stop it happening just by checking for duplicates as I index the notes at startup. Have that working here now but want to do some tests to see if I can find something that is reintroducing duplicates as we work.

**Comment by davidbannon** [comment]
Those multiple entries are a real puzzle. You find that the number of entries half each time you save and exit, then the problem, what ever it is, would have been hidden over time anyway.  There has to be something that increases the number somehow.  I cannot find what.

There is now code committed that ensures no duplicates are loaded at initial index, even if you have a file with a thousand of them !  I don't do the same at save because if there is still a 'something' in there making duplicates, I want to catch it. So far, no sign ....

If you want to be experimented on, there is a 64bit tgz (no rpm, deb nor 32bit) that you can extract the binary from and either over write the one in /usr/bin/tomboy-ng or put somewhere you prefer. It reports itself as v0.26d. In the github release page but not mentioned in the more wordy wiki release page.

Davo

**Comment by davidbannon** [comment]
OK, the problem of multiple notebook entries definitely solved in the v0.27 release.  I have not been able to replicate the problem of not being able to remove a note from a notebook so have to assume its gone with the multiple entries problem.

Davo
