### ISSUE TITLE
Search window loses ordering when closing a note

### ISSUE THREAD

**Issue by dajoker** [tomboy-notes/tomboy-ng#136]
openSUSE Leap 15.1 x86_64 (KDE)
tomboy-ng 0.26 (non-Qt)

This one is easy to duplicate, and hopefully easy to fix.

Open Search
Search on anything.
Sort the results by Title, or anything else, because that's useful.
Open a resulting note.
Close the note while watching the Search window in the background.
Notice the search results scramble in to a random order.
Also notice the Title field still indicates it is being used for sorting (little green arrow) though that is incorrect.

**Comment by davidbannon** [comment]
Yes, it reverts to sorting by last change date. Thats the default way the list is shown.
I wonder what is the best approach here ?  I could clear that little green arrow (and set it to lastchange) or I could repeat the previous search ?
The trouble with repeating the search is that is time consuming and notes get saved quite often.  If someone is typing away they do not want to have things slow down while potentially thousands of notes are being searched and they are not watching.
Interesting .....

**Comment by davidbannon** [comment]
Hmm, interesting indeed, I cannot find ny way to turn off that little green triangle....
Davo

**Comment by dajoker** [comment]
Personally I would like the sorting, and the search for that matter, to remain as it is until I tell it to do otherwise explicitly.  Losing the ordering is really frustrating, especially when going through a lot of notes based on a search, but I also do not expect the search results to update based on changes I'm making in notes at this very moment.  Maybe others do, but I do not think that's particularly normal (just one person's opinion, as always, though).

**Comment by davidbannon** [comment]
Hmm, I have to refresh it at some time.  The code I am working on right now breaks apart the main menu recent list (that must IMHO be updated at every save) from the grid of notes displayed on the search form.  I am now not refreshing the search form display unless its visible, thats a considerable saving in time because the TStringGrid is quite slow. 10mSec on my pretty fast system.

Now, I could extend that (and now would be a good time to do so) to not refresh the search form unless the user re-clicks the appropriate button. That refresh wont always be just a resort, new notes may be shown because they have been created or added to a notebook for example (or removed...).

Is that what you would consider 'normal behaviour' ?

I would always refresh if Search Form goes from hidden to visible but if you have shifted focus to elsewhere and then go back to the SearchForm, thats the issue ....

Davo

**Comment by dajoker** [comment]
I have not tested that latest change to see if it helps, but with the 0.26 version I just noticed that simply editing a note, not even changing it so no save involved, causes the order to be changed, and in fact the results to be entirely reset to some other search.

In other words, search for something that returns five notes (to be able to tell you only have a short list).
Open a note and play around with it, but make no changes (I was searching for data from a few days ago, which I found, but the asterisk never appeared, so no edit, thus no save).
Close the note

The list was changed, and filled up with a lot of notes that did not match the search terms.  If I clicked in the search term field and hit [Enter] it returned my five original notes again.

**Comment by davidbannon** [comment]
dajoker, on the github release page (but not the prettier wiki release page) you will find tomboy-ng-0.26f.tgz.  Its not an install kit, just a tar of a binary along with some files needed if you don't already have tomboy-ng installed.  Its linux only, 64bit and requires the GTK2 env.

If feeling adventurous, you could download, un-tar and put than binary somewhere you can start it manually.  Important : stop existing tomboy-ng before starting the beta. It will find your existing config and notes. Has some bug fixes (but not everything next version will have) and, relevant here, a redesigned Search Window.  In particular if you do a search and then edit or delete one of the notes shown, the order will not change as long as the search window remains open. If there are changes pending, the 'Refresh' button becomes enabled, click it to update the current search.

I am not sure I like this model, bit worried that many users will find it a bit un-intuitive but would welcome feedback.
("Er, I deleted a note but it still shows up in the search box...")

Davo

**Comment by davidbannon** [comment]
OK, this model now in V0.27, lets see how we go.
Thanks for the report and suggestion.

**Comment by davidbannon** [comment]
> Personally I would like the sorting, and the search for that matter, to remain as it is until I tell it to do otherwise explicitly. 

A follow up of a old ticket.

You requested that when notes are deleted or edited, their position in the search window not change until you press the Refresh button.

Following requests from other users (and my own preference) I will reverse this change but will provide a check box on the Search Window that allows you to select the "Manual Refresh".  So, the next release will default to do auto updates but you can over ride that.
 
Davo
