### ISSUE TITLE
Headings in search form are not translated

### ISSUE THREAD

**Issue by aguador** [tomboy-notes/tomboy-ng#137]
Title, Last Change, Creation Date and File Name all appear in English when Spanish is chosen. The same goes for "Notebooks" in the filters.

I know "case sensitive" with the redesign, but I thought other things in the box were up to date. I assume that all these are ng-specific and not covered by the modules own translations.

**Comment by davidbannon** [comment]
Probably easier for me to fix than for you to do the followup translation ....
Davo

**Comment by davidbannon** [comment]
Titles now added tp ResourceString system.
Maybe wait until I have finished fiddling with this redesign of searchform, its still not done IMHO....
Davo

**Comment by aguador** [comment]
Great. When you are close to release/have finished redesign, give me a heads up and I will update the Spanish for the release.

**Comment by davidbannon** [comment]
I think the help notes will need a refresh, so hang off for a bit.  I am still having problems controlling the sort indicators when I refresh the string grid in SearchForm. Its looking like an upstream issue, a regression and quite messy.
Davo

**Comment by davidbannon** [comment]
I will let you report on this one please, pretty sure v0.27 is now all good but my spanish is not great.

**Comment by aguador** [comment]
Yep, everything is now translated in the window, including tooltips.
