### ISSUE TITLE
Line feeds using paste from outside application (windows)

### ISSUE THREAD

**Issue by mrrobmora** [tomboy-notes/tomboy-ng#139]
I noticed an issue on my windows install using multiple-line copy & paste from either Notepad or the old Tomboy whereby the line feeds are inserted in strange spots. Both windows machines I've tried it on have the same behavior, and it looks like it started in release 0.25 (in which I see some other copy/paste issues might have been addressed).  I also see a more minor copy/paste issue going back to even older releases.

Here's what I'm seeing.  If i try to copy/paste the following 4 lines from an external program like Notepad:

1234
abcd
5678
wxyz

it will paste in like this:

1234

abc
d567
8wxyz

I get the same results in both 0.25 & 0.26. Copying/Pasting within Tomboy-ng is fine, it seems to only be with external programs.  Release 0.24 and older (I only tested as far back as 0.19) had a slightly different, more minor issue with an extra line feed after the first line.  The same text would paste like this on those releases:

1234

abcd
5678
wxyz

**Comment by davidbannon** [comment]
Hmm, I noticed something like this yesterday but convinced myself I was imaging it.  I will go back and repeat what I was doing.

The second case you quote was a bug in KControls, now fixed. I do hope fixing that bug has not created a new one .....

Thanks for this report

**Comment by davidbannon** [comment]
Yep, can confirm this happens if you paste at the very end of a note. If there anything after the insertion point, its OK. Looks like another KControls bug I am afraid.
Davo

**Comment by davidbannon** [comment]
KControls issue, I have logged it and patched my copy so next release will have this issue fixed.
Thanks for spotting this mrrobmora 

https://github.com/kryslt/KControls/issues/16

Davo

**Comment by davidbannon** [comment]
All fixed in v0.27
Thanks for that report.
