### ISSUE TITLE
line ending irregularities with cut and paste

### ISSUE THREAD

**Issue by EbStewart** [tomboy-notes/tomboy-ng#140]
I thought you might be interested in this:
I selected all the text open in libreOffice and pasted it into this note,
then did same from your 'about' box.
As you can see, the last char of the line ends up as first char of the next line.

using a PCSpecialist Optimus series laptop with LinuxMint on a standard gpt partition
nvidia card installed but set to use integrated intel graphics

2nd screen by LG connected with dvi to displayport cable

![line ending irregularities with cut and paste](https://user-images.githubusercontent.com/52795868/73973239-1e076580-491a-11ea-8422-0296be625906.png)

**Comment by davidbannon** [comment]
Thanks Eb, thats actually already on the list, its #139, will be fixed in the next release. Its an upstream bug, I reported it, sent a patch and its been fixed upstream too.

Davo

**Comment by davidbannon** [comment]
That bug fixed in v0.27
Thanks
