### ISSUE TITLE
Feature request: keyboard shortcut for new note link

### ISSUE THREAD

**Issue by lydiaslo** [tomboy-notes/tomboy-ng#142]
Is it possible to create a keyboard shortcut for creating a new linked note for highlighted text?  Like CTRL+L in Tomboy.

**Comment by davidbannon** [comment]
Yes, pretty easy. I think we used to do that but it may have got lost when I changed the buttons across the top of the note window to TSpeedButton because of issues on the Mac.
Look for it in next release please.
Thanks
Davo

**Comment by davidbannon** [comment]
That feature now in v0.27
