### ISSUE TITLE
[Q] Which version to download for Windows?

### ISSUE THREAD

**Issue by mwerle** [tomboy-notes/tomboy-ng#144]
Currently there's 3 versions available for Windows:
* 0.26e
* 0.26hHT
* 0.26HTs

They all appear to be experimental based on the release notes, but there's no explanation anywhere of what the differences between these versions are.

Please provide more comprehensive release notes and update them as necessary if more files are added to a release.

**Comment by mwerle** [comment]
...and it doesn't really matter.  Downloaded and installed one at random, and discovered network sync isn't supported yet.

Would be very nice to list the core features in the Readme and which features are currently supported and which ones aren't. For me, network sync is a crucial feature. 

Looking forward to the continued development!  Haven't written any Pascal since Uni or I'd consider helping..

**Comment by davidbannon** [comment]
Thanks mwerle, the best way to select your download is from https://github.com/tomboy-notes/tomboy-ng/wiki/Releases
The raw github download pages show all sorts of things. 
You are the first (I think) person to ask for network sync.  Can you tell me what network server you are using ?  Snowy and Rainly must be beyond their use by dates, I get the impression people don't trust AUTH2 anymore. ....

> Haven't written any Pascal since Uni or I'd consider helping..
Yeah, me too ! I found it very easy to recall. And as a GUI designer, there is no equal.  The sync code is a pretty clear object model, should be easy to slot in a Auth2 client. Please consider......

**Comment by mwerle** [comment]
I use https://github.com/cweiske/grauphel as my network sync server, which plugs into OwnCloud/NextCloud.  I've had pretty poor experiences with using shared drives such as Dropbox in the past so not keen to go back to that.

I'll take a look at the sync code.. but right now pretty busy updating some KSP mods, sorry ;)  Let me create a feature request for that just to track it.
