### ISSUE TITLE
Running sync prints errors about invalid dates to the console

### ISSUE THREAD

**Issue by erik-brangs** [tomboy-notes/tomboy-ng#149]
When running tomboy-ng 0.27 on Linux from a terminal, the sync process complains about invalid date formats:

``ERROR received invalid date string - [2020-03-06 21:25:18]``

This seems to happen only for a few dozen notes. Perhaps it's an incompatibility between versions or operating systems?

**Comment by davidbannon** [comment]
Erik, I am afraid its sloppy work on my part.  In some early release of -ng, I did not worry about putting a full date string in.  So, those notes you are seeing now, date back to that early release.   

At the time, I did not worry, tomboy-ng did not care and my Tomboy test setup did not care. But I recently found that some other releases of Tomboy cannot handle that simplified date string when syncing.  So, this release (and 0.26) has some code in to detect those errors, and, I thought, fix them on the fly.  Important that such notes do not get into sync repo. Maybe, you have a combination that's not being fixed.  :-(

If you can workout which notes are the problem, all you need do is open them, make some insignificant change and close it. That will update the date string and all will be well.  But it will, obviously change the date to "now", if thats not what you want, we'll need to fix them another way. 

But I suspect you won't be able to work out from that message which notes are the problem ?  

I think I need to go back and revisit that code, it should be self fixing .....

Davo

**Comment by davidbannon** [comment]
Erik, I can (still) replicate this problem if joining a new sync and you already have a note in the sync repo with this problem.  Thats a bad miss on my part I am afraid.   

In my test rig here, I have added a bit of code that gives you a more useful statement about the problem, in particular it gives you the title of the offending note or notes.  You can them open, make a change and close that note and its fixed. I think I need to build in an auto fix but that will take a bit longer as it will need much more testing.

Sorry about this, I was pretty sure I had trapped the problem but apparently not.

Davo

**Comment by davidbannon** [comment]
stupid git autoclose .....

**Comment by davidbannon** [comment]
OK, have committed code that auto fixes this problem. As it seems that the offending note hides in the sync repo, I need to update the note date to now and that will force a sync of a fixed note at next sync time.
Davo

**Comment by erik-brangs** [comment]
Thank you. Please let me know if I should test something.

**Comment by davidbannon** [comment]
No worries Erik, if you would like to try a version with this fix (and you have not cleaned those notes up manually) I can cut you a test version.  Would be good to try it out on a "in the wild" system after I have run a few more tests of my own.
What OS do you use ?

**Comment by erik-brangs** [comment]
I'm using Windows and Debian Buster on XFCE (both x64).

**Comment by davidbannon** [comment]
Fixed in v0.28
