### ISSUE TITLE
Conflict having Help Note and Configuration open

### ISSUE THREAD

**Issue by aguador** [tomboy-notes/tomboy-ng#153]
OK, this is badly described, so feel free to modify the description. I will just describe steps to reproduce in v.0.27.

Variation 1:

1. Open tomboy-ng help note
2. Open Configuration
3. On Backup Copy tab, select Show me
4. Double click a note and choose an action

Result: the Help window is raised and the Configuration window becomes unresponsive. It cannot even be closed and, on my E system options to close or even kill the window do not appear when right clicking the window icon on the panel. Closing Help allows the Configuration window to function normally.

Variation 2:

1. Open Configuration (any tab)
2. Open any Help Note

Result: the Configuration window becomes unresponsive, again, impossible even to close or kill. Closing the help note allows Configuration to function normally. This does NOT happen when opening a normal note.

I saw a couple of other variations, but could not remember all the steps to reproduce. DK if this is the result of a feature to prevent errors such as the deletion of Help, or somehow related to where those notes are stored.

**Comment by davidbannon** [comment]
Yes, this is because I use SingleNoteMode to display the help notes (because they need to be read only).  As such they are shown as 'modal' windows, they insist on being the centre of attention.

Will consider ....

**Comment by aguador** [comment]
Ah, I hadn't thought about that. Don't hate me for what I am thinking, but I am wondering if a more "classic" approach to Help than your clever notes wouldn't both solve this and allow a way to incorporate it so that it would be included in translations. Don't worry, if you keep the notes approach I will figure out a reasonably painless way to deal with help.

**Comment by davidbannon** [comment]
Hmm, I must admit the translate issue is a big one with the current help system.  I am not sure if it would be made any better using some other delivery model.  The old Tomboy, from memory, would just open a web browser pointing at some appropriate content. So, that content would still need translating - how would you approach that ?

Lazarus has some standalone (or stand aside) help engine, its based on the original windows chm model, I wonder if there are some tools to make translating that easy ?

**Comment by aguador** [comment]
I actually do not recall how Tomboy operated, but applications that open browsers without warning are a pet peeve of mine as sometimes I am not using other than the default browser.
I brought up the translation issue as the current help system, which in general is quite slick, affects both it and the issue of not being able to keep help open and do other things in ng. I will comment on the translations issues on our other thread (#148).

**Comment by davidbannon** [comment]
> Question: is there a particular reason that help notes must be opened in single-note mode? Can the not be protected otherwise?

Lazy developer ?  I don't remember the specifics but it was certainly easier. Maybe worth looking at how much easier I suppose.  Technically, its more about opening the window as a 'modal' one or not rather than making it read only. Might not be too hard. 

Right now I am having a little panic about the forthcoming Ubuntu 20.04, its contains some problems similar to that one in U19.10 that triggered the debacle about a dependency not available in earlier versions.  And to complicate things, we are finally close to getting a new FPC, the Free Pascal Compiler 3.2.0, so I am running a beta compiler and trunk Lazarus on a beta operating system testing alpha code ......

Davo

**Comment by davidbannon** [comment]
I think this works OK now, I need to do some serious testing as I am, I suspect, relying on an undocumented feature (of TStringList enforcing unique) in the list I now have to maintain of open help notes.

Note, if someone, eg, opens a particular help note in english, realizes its not what they want to see and goes and selects Spanish and then opens it again, they will see two open help notes, one in English and one in Spanish. Does no harm and hard to avoid.
Davo

**Comment by davidbannon** [comment]
Fixed in 0.28, thanks for the report.
