### ISSUE TITLE
Feature request: deletion of multiple backup notes

### ISSUE THREAD

**Issue by aguador** [tomboy-notes/tomboy-ng#154]
This may be controversial or at least require an "Are you sure" confirmation:

At present seeing backup copies of notes involves showing those notes in the Backup Copy of the Configuration window. Notes can then be viewed or deleted one by one.

In my case there are a combination of notes that I knowingly deleted, empty notes I mistakenly created, or notes I simply created for testing. However, even if I am sure which is which, there is no way to select and delete more than one at a time.

**Comment by davidbannon** [comment]
Yes, agree. "At some point in time".

**Comment by davidbannon** [comment]
I have done this, now can select multiple lines and press delete button, but only single lines for recover and view.  Does not make sense to view multiple notes. No multiple recover because recover is a serious step and I believe needs a bit of considering.
Davo

**Comment by aguador** [comment]
Sounds good. Agree that multiple recovers likely not good.

**Comment by davidbannon** [comment]
Fixed in v0.29

Thanks for the report.

Davo
