### ISSUE TITLE
Can't stop blinking cursor on Mac

### ISSUE THREAD

**Issue by MarjaE2** [tomboy-notes/tomboy-ng#155]
MacOS has no global setting to disable all blinking cursors. There are 3 hidden settings to change NSTextInsertionPointBlinkPeriod, ...On, and ...Off, but these only affect NSText and they don't work in Tomboy Notes.

I have neuro issues, and can't see near the blinking cursors, and can get migraines from them.

**Comment by davidbannon** [comment]
Wow, Marja, thats a hard one indeed.  tomboy-ng is built using either the Cocoa or Carbon widget set (although only old systems should consider carbon). Pretty much standard Mac stuff. I will ask around on our forum and see if any one knows of a way to disable the blinking cursor but I must admit, I am not confident !  
I wonder if making it a less obtrusive colour would help ?  (Not that I know how to do that either...)

Davo

**Comment by MarjaE2** [comment]
I have a lot of trouble with these cursors, and I'm not sure lower contrast would be enough. An option to change it to white-on-white or black-on-black might be better than nothing, though it creates its own problems.

**Comment by davidbannon** [comment]
OK Marja, seems it possible on both Windows and (GTK based) Linux but that is all I have found so far.  But still looking ....

**Comment by davidbannon** [comment]
some note for my use -
http://www.macissues.com/2014/12/08/how-to-change-your-macs-text-cursor-blink-rate/
https://askubuntu.com/questions/49606/how-do-i-disable-the-blinking-cursor-in-gnome-terminal
https://forum.lazarus.freepascal.org/index.php/topic,49142.msg355241.html

**Comment by davidbannon** [comment]
Sorry, there does not really seem to be any potential for me to fix this problem on the Mac.

Davo
