### ISSUE TITLE
Can't Page Down/Page Up in Help

### ISSUE THREAD

**Issue by MarjaE2** [tomboy-notes/tomboy-ng#156]
Open Help.

Try to Page Down or Page Up.

It doesn't work.

**Comment by davidbannon** [comment]
No, it does not. I use the mouse to move up and down and have not noticed that the keyboard does not work. Sure it used to so its a regression.

Thanks for pointing it out !

Davo

**Comment by davidbannon** [comment]
Damm git's autoclose 'feature', have to turn that off !
Reopen.
OK, Marja, I have committed a fix for that problem. Very easy.  Next release will have that fix unless you need it now, I can cut you a test version.

Davo

**Comment by davidbannon** [comment]
Fixed in 0.28, thanks for the report.
