### ISSUE TITLE
"Search" box columns

### ISSUE THREAD

**Issue by grosjo** [tomboy-notes/tomboy-ng#158]
Hello,

Instead of the "filename" (which should be in some technical details), can it be to see a notes preview (the first lines) ?

Thank you

**Comment by aguador** [comment]
Davo will have to comment on the processing cost, but I would be curious about your use case. What you see, as your inverted commas imply, is not a filename (which is randomly assigned) but a descriptive name you can assign to the note by overwriting the date and time stamp automatically produced. I have had no reason to test the limits of the note name, but is that not sufficient?

**Comment by grosjo** [comment]
![Screenshot from 2020-04-07 11-07-13](https://user-images.githubusercontent.com/2287111/78656902-f6079480-78bf-11ea-87ba-49cb2a801903.png)

**Comment by grosjo** [comment]
See screenshot above.
The "File name" should be replace with a preview or something usefull
Also, maybe add the capacity for the user to choose the columns to show ?

**Comment by aguador** [comment]
OK, understood, you were really talking about the name generated by ng. What I don't understand is that my search window (v. 0.27 Gtk) no longer shows that column. I thought that Davo had eliminated it as he had been using it during early development.

**Comment by grosjo** [comment]
I see. In git version, it is gone.
Now, maybe interesting to use the sapece to add extra info ?

**Comment by davidbannon** [comment]
Yes Joan, that search window image you posted dates back to an earlier version. Was changed with release 0.27.  The change was about simplifying the interface. I tend to put far too much stuff into an interface, while I will never go for the really (dumbed down) simple model, I do acknowledge that it needed to be cleaner than it was.

If you are building for a pull request, you should be working from a current snapshot.

I could put extra information in a 'hint' that pops up when you hover over the entry in the listbox.  But populating all that extra info would come at a cost !  We have users out there with thousands of notes, the start up time is quite significant.   Maybe it could be optional ?

Davo

**Comment by grosjo** [comment]
Well, the "0.27" version available on Archlinux is not the same.

Anyway, I beleive the columns to be chown shall be a users' choice (some need less, some need more)

**Comment by davidbannon** [comment]
Thats interesting !
Can you see a date on the Arch package ?
The last commit to redesign the search window was Feb 3 and v0.27 was frozen on March 15.  I'd hate to think they are grabbing current source and calling that the next version number .....
I often have somewhat untested code in there !
Davo

**Comment by grosjo** [comment]
The tomboy-ng package has been flagged "out of date" on Archlinux

**Comment by aguador** [comment]
Yes, it is the 0.26 release rather than the current one: https://aur.archlinux.org/packages/tomboy-ng-bin/

**Comment by davidbannon** [comment]
We are already two releases ahead of this topic.
Davo
