### ISSUE TITLE
Upstream issues

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#16]
This might be a good place to track upstream issues and link their communication channels. You can add issues with the todo syntax:
`- [ ] [issue title](URL)`

# FPC
- [news](https://www.freepascal.org/). stable: [3.0.4](http://wiki.freepascal.org/User_Changes_3.0.4) ([download](https://sourceforge.net/projects/freepascal/files/Linux/3.0.4/))
- [bug tracker](https://bugs.freepascal.org/set_project.php?project_id=6)

# Lazarus
- [bug tracker](https://bugs.freepascal.org/set_project.php?project_id=1), [roadmap](http://wiki.lazarus.freepascal.org/Roadmap), testing: 1.8 ([Release thread](https://forum.lazarus.freepascal.org/index.php/topic,38601.msg267271/topicseen.html#new), [fixes](http://wiki.lazarus.freepascal.org/Lazarus_1.8_fixes_branch), [notes](http://wiki.freepascal.org/Lazarus_1.8.0_release_notes)), unstable: [1.10](http://wiki.freepascal.org/Lazarus_1.8.0_release_notes)
- [carbon](http://wiki.lazarus.freepascal.org/Carbon_Interface) (Mac 32bit): [FAQ](http://wiki.lazarus.freepascal.org/Carbon_interface_FAQ), [forum](https://forum.lazarus.freepascal.org/index.php/board,27.0.html), [internals](http://wiki.lazarus.freepascal.org/Carbon_interface_internals), [bugs](http://www.freepascal.org/mantis/view_all_set.php?type=3&source_query_id=1018), [future](http://wiki.lazarus.freepascal.org/Installing_Lazarus_on_MacOS_X#Carbon_and_Cocoa)
  - [ ] #17 [TTrayIcon leak](http://forum.lazarus.freepascal.org/index.php/topic,38917.msg265732.html)  ([report](https://bugs.freepascal.org/view.php?id=32678)), [doc](http://lazarus-ccr.sourceforge.net/docs/lcl/extctrls/ttrayicon.html), [wiki](http://wiki.lazarus.freepascal.org/How_to_use_a_TrayIcon)
  - [ ] [TrayIcon MenuItem Caption not updated](http://forum.lazarus.freepascal.org/index.php/topic,38494.0.html), [bug report](https://bugs.freepascal.org/view.php?id=32516)

# KControls
- [download and discussion](http://www.tkweb.eu/en/delphicomp/kcontrols.html)
- [commit history](https://bitbucket.org/tkweb/kcontrols/rss)
- [X] [NoMethodError](http://www.tkweb.eu/en/delphicomp/kcontrols.html?action=commentaddform&par=5a14825e01662) for [DoAutoAdjustLayout](http://wiki.lazarus.freepascal.org/High_DPI) - fixed in [trunk](https://bitbucket.org/tkweb/kcontrols/commits/9fab2d710a8c)
- [ ] [Peek !!!](http://www.tkweb.eu/en/delphicomp/kcontrols.html?action=commentaddform&par=5a14c24ef0f6f) on file actions

**Comment by davidbannon** [comment]
Not a lot of need for this issue to stay hot.  The Mac TrayIcon memory leak is tracked elsewhere, TK has fixed the DoAutoAdjustLayout in KControls, the Mac carbon v. Cocoa is way beyond what we can do here.

**Comment by traumschule** [comment]
didn't like the link list to track updates or is it documented somewhere else?

**Comment by traumschule** [comment]
I can't reopen it but I agree to have one issues per bug. Thanks for
your fast reply!
