### ISSUE TITLE
33 unfreed memory blocks : 2922

### ISSUE THREAD

**Issue by grosjo** [tomboy-notes/tomboy-ng#163]
Hi
WHen launching the tomboy-ng from the command line, then choosing "quit" from the menu, the app complains of objects not beeing freed 

FreeandNil() missing ?

Heap dump by heaptrc unit
27664 memory blocks allocated : 3253938/3323144
27631 memory blocks freed     : 3251016/3320152
```
33 unfreed memory blocks : 2922
True heap size : 622592
True free heap : 614016
Should be : 615376
Call trace for block $00007FE0F06FFAE0 size 69
  $00000000004F5D76
  $00000000007F7DF0 line 230 of oauth.pas
  $0000000000490855 line 83 of ncsetup.pas
  $000000000057EA62 line 2913 of include/control.inc
  $00000000005E305A line 55 of include/buttoncontrol.inc
  $00000000005E38A3 line 169 of include/buttons.inc
  $00000000005E2F46 line 21 of include/buttoncontrol.inc
  $0000000000432B1F
Call trace for block $00007FE0F04CD180 size 42
  $00000000004F5D76
  $00000000007F7DF0 line 230 of oauth.pas
  $0000000000490855 line 83 of ncsetup.pas
  $000000000057EA62 line 2913 of include/control.inc
  $00000000005E305A line 55 of include/buttoncontrol.inc
  $00000000005E38A3 line 169 of include/buttons.inc
  $00000000005E2F46 line 21 of include/buttoncontrol.inc
  $0000000000432B1F

```

**Comment by grosjo** [comment]
Please apply PR #164

**Comment by davidbannon** [comment]
Sorry, please slow down a bit Joan, I am having to make quite a lot of changes to you patch from yesterday to endure backward comparability.  You will have a lot of problems merging with what I have done.  If you can wait a short while, I will push and then we can see how well this one merges ....

David

**Comment by davidbannon** [comment]
My guess is that your memory leak is from where you create the OAuth, if you create, so must you free !

We could have a look at how that works too, it might be a good idea to only create it when its about to be used and release it immediately afterward.  Thats a bit kinder on memory usage.

For 'regional' vars like OAuth, I like to expressly set them to nil in the FormCreate function then when we want to use it, you might do something like this -

if OAuth <> nil then freeandnil(OAuth);
OAuth := TOAuth.Create
try
      ....
finally
       freeandnil(OAuth)
end; 

Its a safe ....

davo

**Comment by grosjo** [comment]
Yes, all the memory leaks are fixed in my PR
