### ISSUE TITLE
Policy - bugs, features and releases.

### ISSUE THREAD

**Issue by davidbannon** [tomboy-notes/tomboy-ng#18]
Think its time we separated out bugs from feature requests especially in the context of getting a release together. Some suggestions -

**Alpha, Beta release policy.**

1.  I am aiming for for a v0.1 release, its still Alpha, meaning incomplete and bug ridden. 
2.  After that we have a point releases of v0.11 - v0.14 which are further bug fixes and, in earlier points, new features. To keep the code stable, we'll not do anything major later in the cycle.
3. Then we have a 0.15, one we'll announce again on the tomboy list. Goto 2. 

**Bugs v Features**
As we are approaching v0.1 right now, we'll freeze 'features' and do bugs and release stuff.  Sometimes the line between a bug and a feature is ill defined, especially with UI stuff so a lot of flexibility is required.  But I think I need, right now, to declare some things can be held off until after the v0.1.

**As an example Targets for v0.1**

- 32 and 64 bit binaries for Mac, Windows and Linux
- Debs
- All the stuff thats 'works' now with all simple bugs fixed.
- Deleted note should not appear in recent menu or search list.

**As an example Target for v0.15 (or before)**

- Windows Installers
- User option to rerender links in open notes when a note is deleted or created.
- Mac memory leak fixed.

**Comment by traumschule** [comment]
Good you start this thread, i thought about the same. The proposed naming scheme however is confusing, instead I propose 0.1 as next release and 0.2 for later features (Bug fixes would go into 0.1.x). Also you can use labels on issues, for example "low-prio" / "high-prio" or "wishlist" "bug" etc.

**Comment by davidbannon** [comment]
This content is probably better stored on wiki.

**Comment by traumschule** [comment]
agreed, if it is already, please add a link.

**Comment by davidbannon** [comment]
Unless we have someone else contributing code, its pretty hard to justify have a policy document like this. I practice, I am not following it even now.
David
