### ISSUE TITLE
add package to official Debian/Ubuntu sources

### ISSUE THREAD

**Issue by alexanderadam** [tomboy-notes/tomboy-ng#183]
I'm sure that there probably is something but I can't find it therefore I'm just trying to ask here:

Are there any efforts to add tomboy-ng to official packages? Is there any issue that I could subscribe or so?

The only open issue I found is [Debian issue 897688](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897688) (and nothing happened here for a _long_ time). [For Ubuntu I found nothing](https://launchpad.net/+search?field.text=tomboy-ng&x=0&y=0) so far.

Did you [submit your packages for inclusion](https://packaging.ubuntu.com/html/packaging-new-software.html#submitting-for-inclusion)?

**Comment by davidbannon** [comment]
Alex, I have not done so yet, would like to do so but been working on stability and completeness.  For a while there, I had a new version out every month, and needed to !

But it could be argued we are nearly there now, so, next issue is build environment, as I understand it, Debian at least, and, presumably Ubuntu, require source packages, thats not impossible but I am building with a beta version of the FP compiler and not sure how they would react to that.  At present, the FPC320beta is rock solid, fast and has some important features the current release does not. But its still officially Beta.

So, right now, its all just a bit hard but could well be a realistic option soon.

Hmm, just followed the (Debian) link you provided, I wonder if Abou is still interested ?  

Davo

**Comment by alexanderadam** [comment]
Thank you for responding so fast. Therefore I would keep this issue open for tracking the current state, if that's okay for you.

**Comment by davidbannon** [comment]
On the topic of FPC320 -

https://forum.lazarus.freepascal.org/index.php/topic,49110.msg362353.html#msg362353

"Shortly. It is tagged for release and being build for supported platforms. weeks not months now, afaik."

D

**Comment by davidbannon** [comment]
Just an update here.
* I can now push tomboy-ng out as a PPA targeting Focal and will do so in v0.30.  As it has to be built using Focal's available FPC/Lazarus, its a touch inferior to the ones I build but most users would not notice.  I suspect the same package is usable in U18.04 but cannot build it there as it's Lazarus is too old. (Do I also need setup a PPA for Lazarus ?  Lots of out of date ones there ....)
* Debian is proving a harder nut to crack.  While initially welcomed, complying with their processes is not easy. I have not given up but wonder if its worth my time ?  Sounds like it would have to be a Qt5 version ....
D

**Comment by alexanderadam** [comment]
> I suspect the same package is usable in U18.04 but cannot build it there as it's Lazarus is too old.

I guess you could ignore it then as 20.04 is a LTS as well. Those efforts would probably be better invested in the Debian release because it would be available in future distributions then, I guess.

Or what do _you_ think about it?

**Comment by davidbannon** [comment]
> Or what do you think about it?

Not sure. While I would like to get tomboy-ng into Debian, I am not impressed by their approach so far !  Its a bit like being a new kid at school, you can expect to get a hard time because you don't know the culture.  And you have to put up with that hard time while you learn the culture.

Davo

**Comment by davidbannon** [comment]
Some progress with Debian. The code is now legally acceptable. Much thanks to TK for changing the KControls license. I have redone the hunspell binding from scratch.
Just got the OK yesterday !
Only technical issues from now .....
Davo

**Comment by davidbannon** [comment]
Doing an issue sweep on release of v0.31, so update in order.
I have handed over source package (via Debian Mentors) to my sponsor. He will submit it to the Debian FTP gatekeepers, we will wait and see....

**Comment by davidbannon** [comment]
Well, its been a struggle but here it is -

https://packages.debian.org/bullseye/tomboy-ng

Thanks to Philipp for his help and tolerance during a complicated process.
  
And thanks to the many people who have helped along the way, the translators, especially Roy who also contributed to the design in ways I could not. And xypd for the cool icons. All the users who reported and tested bugs !

(It shows up in Ubuntu too. Will probably flow wider still.)

Davo

**Comment by alexanderadam** [comment]
Oh wow, congrats! :tada: 
I cannot check packages.debian.org for some unknown reason but this means it will be solved in future distribution releases and this issue can be solved, right?

Thank you so much for your work! :pray:

**Comment by davidbannon** [comment]
tomboy-ng v0.32 is now in Bullseye and Bullseye will soon be Debian Stable.
QED
Davo
