### ISSUE TITLE
MarkDown

### ISSUE THREAD

**Issue by davidbannon** [tomboy-notes/tomboy-ng#197]
tomboy-ng will import and export markdown and the TomboyTools app does the same, only with more notes.
However, I don't think its completely compliant with https://commonmark.org/

I am not sure that commonmark is a good standard, its a little less rich than many of the other markdown efforts out there but it is, at least, a consistent standard.  Thats better than ad hoc....

Make -ng comply, later do TomboyTools....

D

**Comment by washere** [comment]
Thank you
Thank you
Thank you.

**Comment by davidbannon** [comment]
I am doing so now wrt TomboyTools.  Still no highlight ...

:-)

Davo

**Comment by davidbannon** [comment]
OK, this issue is fixed in version 0.32b, will close.  
Thanks for the report.
Davo
