### ISSUE TITLE
database backend

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#20]
> I have plans for V2.0 that will include (optionally) moving the notes into a database (#10)

If [rainy](https://github.com/Dynalon/Rainy) is still functional it may be a proper backend as a "synchronization server that allows to sync notes with Tomboy and Tomdroid" (PostgreSQL/SQLite, backend encryption) and alternative to *cloud (#1)

**Comment by davidbannon** [comment]
No, sorry, 

- rainy is dependent on Mono developer, trying to get away from heavy dependancies
- Its not really in Tomboy spirit, I see Tomboy (et al) as being self contained.

Rainy is a great sync solution but involves far too much set to treat as a database. I'd consider offering users a choice of where to keep their notes -

- File repo, compatible with tomboy
- sqlite - for medium scale users, operationally very similar to above, code wise similar to below.
- A serious database for really, really serious users. Who know how to setup their own database and manage it. If it was not for the fact that much of the code is re-use of the sqlite stuff, would not be worthwhile.

Hope you don't mind, going to close this issue, don't think we need the distraction right now and would like to see issues list a bit smaller as we go public.

**Comment by traumschule** [comment]
Ok, if it's not rainy it will be something else. Please leave it open as a reminder.

**Comment by traumschule** [comment]
Please leave it open as a reminder.

**Comment by davidbannon** [comment]
yes agree but I'm not intending to get heavily into that (a database backend) unless we hear some calls for it.
