### ISSUE TITLE
Invalid floating point operation errors

### ISSUE THREAD

**Issue by dannaughton** [tomboy-notes/tomboy-ng#201]
I finally got around to deleting the mono version of tomboy.  I'm seeing this error 

Invalid floating point operation
Press OK to ignore, etc
Press Abort to kill the program

This happens with:
Menu ==> New Note
Notebooks - I have no notebooks, but if I select the empty list panel.

I click through it, and it seems to be okay.

uname -r
5.7.12-200.fc32.x86_64

rpm -q tomboy-ng
tomboy-ng-0.30-2.x86_64

**Comment by davidbannon** [comment]
OK, thats not good, not good at all !   I will have to setup an install with no notebooks to try to reproduce this, right now I have no idea why it would happen.  I am not, consciously, using floating point in there (too slow) but maybe its a some scaling issue ?

Can I just clarify your process please ?

You open a new note, and from within that new note, you click the little square "manage notebooks" button.  In the window that pops up, you click in the empty panel space under the "Existing Notebooks" tab ?  And that triggers it ?

Thanks for this report !

Davo



I will get back to you as soon as I can.

**Comment by davidbannon** [comment]
Hmm, I cannot replicate this. I have tried doing it in "manage Notebooks" form from a new note.  And in the SearchForm, clicking in the lefthand panel, in both cases with no notebooks yet created. Would you please step through what you do, step my step ?]
Davo

**Comment by dannaughton** [comment]
i can't get it to duplicate.  It's working fine this morning.  I deleted the ~/.local/share/tomboy-ng and the ~/.config/tomboy-ng folders, restarted, and it still works fine.  Maybe there was something wrong with the older tomboy note files that was fixed?  Anyway - I'm up and running.  Thanks for putting this app together.  Looks promising - I have a ton of stuff in the old tomboy that I can now keep using.

**Comment by davidbannon** [comment]
That is strange indeed.  I think we will leave this ticket open for a while if you don't mind, other people might be more inclined to report it if they see the same thing.
I hate bugs that go away by themselves !
Thanks for your report Dan, glad you are under control for now.
Davo

**Comment by davidbannon** [comment]
OK, I guess as we have seen no sign of this issue since its initial report. We will have to put it down to Remote Alien Interference.
Davo
