### ISSUE TITLE
"About" page opens on different workspace where a note is open, not on the current workspace

### ISSUE THREAD

**Issue by dajoker** [tomboy-notes/tomboy-ng#203]
openSUSE 15.1 x86_64, KDE
tomboy-ng 0.30.2 (non-Qt)

I have not seen this before, but I also haven't probably tried it.  I run with multiple (4) workspaces and I usually keep my note for the day open on #2 and today I as trying to figure out my tomboy-ng version while I was browsing the list of issues over on workspace #0.  Clicking "About" worked, and returned, but nothing popped up.  A while later I swapped back over to the third workspace and found about four (4) windows open showing me the About information for tomboy-ng.

If I open a note on my current workspace, the "About" window opens nicely.  If the only place I have a note open is somewhere else, the "About" window opens there.  If I have a note on workspace 0, then another opened later on workspace 2, and I am on workspace 1, then opening the "About" page opens it on workspace 0, and also moves my notes from workspace 2 over there, and I will not see anything until I go over there to workspace 0 where everything is now waiting for me.

Not a big deal, just quirky.

**Comment by davidbannon** [comment]
Interesting !  Especially that you can open multiple About boxes !  Thats not intentional.

Firstly, do you have wmctrl installed ?  I use that to move an open note to your current workspace if you click on its menu entry. Can you please test that for me ?  eg Open a note in Workspace one (for convenience, if necessary, make a small change to it so its in your recent menu).  Now, move your view to, say, workspace three. You no longer see that note, click the trayicon, select that note from the menu and it should move to current workspace. 

It could be that I have just not applied that same rule to the about box ...

I use my workspaces a lot !  I need that to work well.

Davo

**Comment by dajoker** [comment]
I have wmctrl installed, but it's not moving the window from the CLI for some reason.  I am able to move it other ways, e.g. by clicking on the note name in the list of recent notes (it was open on another workspace, but not it has "moved" to this workspace), or by dragging it from one workspace to another (via the "Desktops" pager that is part of KDE which has a little representation of each window on each "desktop" that can be dragged with the mouse from one to another.  I tried this to move the window via the CLI:

> wmctrl -r 0x006abd6f -t 0
> wmctrl -R 0x006abd6f

Anyway, once I "move" the window to the current workspace/desktop the About window opens "here" which is correct.  If I then move it back to the other workspace/desktop, the About window opens "there" again.

**Comment by davidbannon** [comment]
Note quite sure what you mean here.

> but it's not moving the window from the CLI for some reason. 
Which window do you mean ?  The About window or a note you are moving as I described earlier ?

I will have to look back through the code that I use when moving a note window around and see if I can apply the same method to the about box. 

Davo

**Comment by dajoker** [comment]
Yes, sorry, I meant I could not figure out how to make the command move the note window as you requested, but either way it seems like the About page opens where a note is, even if the note is moved from one desktop/workspace to another.

**Comment by davidbannon** [comment]
OK, fixed this. Now keep a handle to About box and is valid, reshow it.  EnsureVisible seems enough to swap it to current workspace without using wmctrl.  Maybe because it is, really modal (unlike EditBoxes).  Must test under Windows and Mac.
Davo

**Comment by davidbannon** [comment]
this was all fixed in recent release, missed it.
