### ISSUE TITLE
Mass/Notebook Export

### ISSUE THREAD

**Issue by TimothyHD** [tomboy-notes/tomboy-ng#213]
Is there a way to export whole notebooks?  I saw mention of TomboyTools, but cannot find this program.

**Comment by davidbannon** [comment]
Well, hard questions first hey ?
I did make a thing called TomboyTools for another user and have, for some time, intended to get it ready for regular use.  But I have been using its code base as a test bed for some other activities and I would not like you exposed to it as it exists now.

I have some new code I developed for an ill fated thrust into NextCloud for converting Tomboy to markdown that supports a subset of CommonMark and I would rather use that than the less well defined mark down I originally used.

What format would you like to export in Timothy ?   And can you wait a bit ?

It might be reasonable to add that NoteBook export ability directly to tomboy-ng....
 
(Right now I am quite busy trying to release a new version to tomboy-ng and going through a massive process of getting it into the Debian system for the first time. But I could dig back through git and find the original form of TomboyTools if you need it urgently.) 

Davo

**Comment by TimothyHD** [comment]
I actually have realized I may not need the mass export at this time.  I use the program to make board game rules.  I like to be able to make pages when I use a phrase or word that need rules definition.  Tomboy-ng has been great.  The biggest upgrade from tomboy is the ability to define which notebook rules are part of (and more importantly not part of).  Thank you.  All I was considering was a mass text dump of a notebook, btw ;).

**Comment by davidbannon** [comment]
I have moved TomboyTools to its own repo and if you or anyone want a release, just ask.
So, I will close this ticket.  

https://github.com/davidbannon/TomboyTools

Thanks for your input.
Davo
