### ISSUE TITLE
Selected note is not highlighted in search window

### ISSUE THREAD

**Issue by turgutgenc1** [tomboy-notes/tomboy-ng#218]
Hi, thanks for the re-work of Tomboy Notes, I appreciate it!

On tomboy-ng search window, select a note via single click, and it is not clear which note is selected.
It'd be great to be able to move in between notes using arrow keys. But before that, the selected note should be highlighted.
Currently it doesn't.

Platform: x86_64 Win64 (Win10Pro)
Build Date 2020/12/12
Tomboy-Ng Version 0.31

**Comment by davidbannon** [comment]
> select a note via single click, and it is not clear which note is selected.

Yes, you are right. This is a by product of a change I made when another user requested the alternating colours in the note list. Those alternating colours also cause the Qt5 version note list to be displayed with insufficient space between each line, it looks horrible !  I am thinking of dropping those alternating colours in the next release.

> It'd be great to be able to move in between notes using arrow keys.

Thats actually pretty easy.  As long as I do something about the colours ....

Thanks for your input  turgutgenc1, two good points !

Davo

**Comment by davidbannon** [comment]
So, the core issue here is that the Qt5 version and to a lesser extent, the GTK2 version do show which note is selected. The Windows version has a dotted line around the selected cell but its very hard to see.  I need to ask Windows users would they prefer a clear selected indication to the alternating colours, reported to make it easier to read.

My guess is that Windows users would be better of with me turning off the ownerdraw and thus the alternating colours.  But need some feedback from Windows users.

Davo

**Comment by davidbannon** [comment]
Pre-release version now available that addressed this issue. Please see https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.31
If you do use it, please watch for anything unexpected and please report what you find, good or bad.

**Comment by aguador** [comment]
OK, tested this in Gtk dark mode and clicked note is highlighted.

**Comment by turgutgenc1** [comment]
Tested with 0.31h version, works like a charm. Thank you!
