### ISSUE TITLE
Typing @ in Search crashes tomboy-ng 0.31

### ISSUE THREAD

**Issue by turgutgenc1** [tomboy-notes/tomboy-ng#219]
Simply starting to type @ character in Search area crashes tomboy-ng.

Tomboy-Ng Version 0.31
Build 2020/12/12
Platform x86_64 Win64 (Win10Pro)

**Comment by davidbannon** [comment]
really ?  Does not happen on Linux, I'll have to boot into Windows to test. I have no idea why that would happen !

Do you actually have to do a search for the '@' for it to crash ?  Or it crashes as soon as you press the @ key ?

I notice that the "in note search" (which is built using standard library components) does not let you enter @, now, I wonder why not ? 

Davo

**Comment by turgutgenc1** [comment]
It only happens when you type in search box. It is pretty much immediate when you press @. It shows the character in the field, then the app crashes, suggesting not the pressing but the searching causes the issue.

**Comment by davidbannon** [comment]
> suggesting not the pressing but the searching causes the issue.

Thats the strange thing IMHO, no searching takes place until you press Enter. I watch for the Enter key and Ctrl -N, anything else is just put into the control buffer. Sorry, I won't be able to replicate this problem today, have quite a lot of stuff on. Tomorrow is looking better....

Davo

**Comment by davidbannon** [comment]
turgutgenc1, I am afraid I cannot replicate this problem. Tried one @, tried a row of them, no problems.  That is a worry !

If you would like help me track this down, that would be great. In the lower part of https://github.com/tomboy-notes/tomboy-ng/wiki/Bugs-and-Known-Issues there is a section about capturing a log file, its a bit fiddly but not too hard.  If you could set thing up like that article suggests, no need to to set a particular debug mode but do need to define the logfile location. A command like -

`
"C:\Program Files\tomboy-ng\tomboy-ng.exe" --debug-log=%userprofile%\Desktop\tomboy-log.txt`

Start up -ng and trigger the problem, maybe have a look at the logfile that will have appeared on your desktop to ensure  there is nothing there that you don't want the world to see.  Please post it here.  I am not sure it will help but we have to start somewhere....

Davo

**Comment by turgutgenc1** [comment]
Sorry for bothering you sith this, I isolated the issue:
Alt Gr + Q generates @ character in Turkish keyboard layout, but at the same time it is processed as ALT + Q by tomboy-ng.
So it is not the @ character causing in search function leading to a crash, it is in fact the key combination generating quit signal.
If you could catch signals and key combinations, provide a method to modify them that would be grand. But otherwise this is not a bug. Closing.

**Comment by davidbannon** [comment]
Ah, that makes sense !
And maybe we can fix that specific case ?  Now, I don't have a Turkish KB installed, you will have to help me a bit.  Firstly, "Gr", which key is that please ?  I should be able to tell the difference between Alt-SomeKey-Q and just Alt-Q but need to be able to replicate what you are doing....
Davo

**Comment by turgutgenc1** [comment]
"Alt Gr" is the Right Alt key on the right side of the space bar. In Mac, it is the right Option key.  
Left Alt doesn't do the same, but right alt does.

**Comment by davidbannon** [comment]
OK, I understand now. Its probably a case of me making sure that the Shift key is not also down when I respond to Alt-Q, pretty sure thats easy (and should have been done from the start).

Davo

**Comment by davidbannon** [comment]
No, not that easy after all.
In tomboy-ng, Alt-Q does not do anything, its Ctrl-Q that quits the application. 
So, if you are right and what you see is a 'normal' Quit because user requested it, you must have your Ctrl and Alt keys re-mapped somehow. Perhaps thats a function of the Turkish keyboard ? I must admit, I do not understand.
I have checked to see if there is any reason to suspect that tomboy-ng confuses Ctrl-Q with Ctrl-Shift-Q and it does not.
And a right Alt Q does nothing in tomboy-ng, neither does a left Alt Q.
I am afraid I might have to assume its something the Turkish keyboard is generating.  If we could be really sure its a graceful exit and not a crash it would be helpful. Thats a bit harder to do on windows, you need to capture the debug output to a file, documented in the wiki page "Bugs and Known Issues" under Debugging. If you feel like trying that, it may give us a hint on whats going on.  I could send you a version of tomboy-ng packed out with some debugging code that may be even more informative if you feel like a play !

Davo

**Comment by turgutgenc1** [comment]
I had tried debug flags on Windows 10 but there were no abnormal entries, it was exactly the same with closing the app manually vs typing Right Alt + Q. I can surely test a debug enabled version Davo, please let me know where can I access that special version.

**Comment by davidbannon** [comment]
OK, that does say its not a crash. I think.
I will have to ask you wait a bit while I get the 0.32 release out, don't want to disturb the src tree at this stage and making a git branch is more effort than appropriate.  I already have a 'version' of 0.32 available in Debian so need to catch up for everyone else.
Will not be long ...

Davo

**Comment by davidbannon** [comment]
OK, there is a experimental version in the Github Release page, https://github.com/tomboy-notes/tomboy-ng/releases/download/v0.32/tomboy-ng-setup-0.32a.exe

This package addresses two things at once, it writes a few debugln when exiting from Search Form to help debug the issue raised here and fixes another unrelated bug.

I did spot something in there that just might be a factor, the Quit was being triggered by the Ctrl-Q key even if another key (such as Alt or Shift) was also pressed. That should not be and I have fixed it as well. Maybe nothing to do with whats happening here ...

So, please collect the debug statements and we'll see where that leads us.

If it works for you, seems no reason why you should not use it until we push out the next formal release.

Please let me know what you find.

Davo

**Comment by davidbannon** [comment]
OK, well fixed in the 0.32b beta release. So I will close this ticket.
thanks for the report.
