### ISSUE TITLE
New note started from Search window is not listed in Search window until clicking Refresh or a dummy search.

### ISSUE THREAD

**Issue by turgutgenc1** [tomboy-notes/tomboy-ng#220]
Open Search Window, start a new note (either from menu or Ctrl+N), close the new note window. The new note is not listed in the Search window, "Refresh" button is enabled. Either clicking "Refresh" button or running a dummy search starts showing the new note.

When a new note is created, it should be right away shown in the list  of notes for consistency.

**Comment by aguador** [comment]
Obviously, Davo needs to weigh in on this one as it depends on the overhead involved -- and I believe that from other posts there is some significant overhead saved by not updating automatically, especially since the search form, as I recall, involves calling a separate module.

Having come from Tomboy I think I understand your concern. There I kept the search window open, but find myself using ng differently. Now I only have to need to open it from time to time as I usually work with relatively small subets of my notes at any given time. As a result the ng list of the 10 most recent notes that appears from the notification icon in the system tray fits the bill perfectly. I am happy NOT to keep the window open, especially  since I find it busier and less attractive than the old Tomboy search window. Furthermore, new notes DO appear in the popup from the tray right away.

**Comment by davidbannon** [comment]
Yes, as aguador says, the manual update model is desirable for users with very large numbers of notes. They like be able to open the search window, find a note they want to work on, do so, then work on the next one in sequence and perhaps work their way down the list. Having the list refresh itself confuses that work flow.  The list is refreshed whenever you close/open the search window or hit 'Refresh'.

But No, its not really a performance issue, I keep the note metadata in a internal data structure, sorted, so, I can refresh the visible list quite quickly at any time. 

I, personally, am often surprised the list has not been updated !  So, maybe we need to look at making that optional ?  "Auto Refresh" on/off   ?  I worry just how complicated the user interface has become however. I like having lots of options but new users do find it confusing....

turgutgenc1, are you an old time Tomboy user or a new to the tomboy world ?

Davo

**Comment by turgutgenc1** [comment]
I'm an old time Tomboy user (and I had to adopt to nValt on Mac for the last few years because Tomboy kept crashing on Mac). I have been concurrently using Tomboy on Windows with rotational storage, and nValt on Mac with hundreds of notes (close to 900) without an issue with immediate search while typing. So, I think providing auto refresh option might be a good idea for wider range of users.

To give you more insight from the usage characteristics perspective, I am NOT using the same notes over and over again, I tend to visit 50-100 different notes every day. That's why just having the systray icon with 10 most recent notes would not fit my bill. I am using these notes apps to access my small notes faster than finding and opening a file in finder/file explorer. I'm not using the mouse either, I am using keyboard shortcuts to activate the app, switch in between panes/tabs, search, open&close, copy&paste etc. Systray icon doesn't do anything for me either (well, except staying there as an identifier of running application).

After major things are fixed in Tomboy-Ng, I might be asking a menu for keyboard shortcuts, maybe an import function for a pile of regular text files... Which in fact would be very much useful to me at the moment.

**Comment by davidbannon** [comment]
> After major things are fixed in Tomboy-Ng, I might be asking a menu for keyboard shortcuts, maybe an import function for a pile of regular text files... Which in fact would be very much useful to me at the moment.

There is a help note that lists all keyboard shortcuts.

I have a tool that does some bulk import / exports that I have, from time to time made available to other people. Its really a test bed for units I later merge into -ng so at any one time, its quite unstable.  Perhaps its time I again stripped out the silly stuff and tuned up the import/export functions ....

Will have to happen after I merge two two streams of code back to one and incorporate the Tomdroid interface.

Davo

**Comment by davidbannon** [comment]
Pre-release version now available that addressed this issue. Please see https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.31
If you do use it, please watch for anything unexpected and please report what you find, good or bad.

**Comment by aguador** [comment]
OK, just tested with 0.31f and the search window refreshes to show a new note once it has been saved automatically or closed. Eliminating the note also removes it from the search list immediately.

**Comment by turgutgenc1** [comment]
Tested with 0.31h version, auto refresh works! Thank you!

**Comment by turgutgenc1** [comment]
Tested with 0.31h version, auto refresh works! Closing this, thank you!
