### ISSUE TITLE
Enhancement request: Within note search arrows and "not found" indicator

### ISSUE THREAD

**Issue by aguador** [tomboy-notes/tomboy-ng#221]
First, could the search window be simplified to replace the "Search" button with arrows? This is pretty standard practice these days, present in browsers, LibreOffice, pdf viewers, etc. and would allow the removal of the box with the forward-backward search direction. That, in turn, would allow the two checkbox items to be placed side by side thereby reducing the size of the search popup.

Second, when no instance of the search term is found, could -ng provide confirmation? For example, LibreOffice provides a red hexagon with a white x in the center left-justified in the search term box. By doing nothing -ng leaves those of us who are getting older wondering if we actually pressed the search button! :-)

**Comment by davidbannon** [comment]
Would we be better dropping that (library) pop up box and do the searching from a status bar across the bottom of a note ? I would need a field to enter a search term and a forward / backward arrow ?   Would have room to display a 'Not Found' message.

That existing search popup is a library thing, I cannot reasonably easily change it.  But could make another, to our spec, from scratch.

Davo

**Comment by aguador** [comment]
From scratch across the bottom of the note even better. With arrows and I think either an icon for not found or, more informative, a number of instances found.

Would the rodent skeptic want key bindings for navegating?

**Comment by davidbannon** [comment]
Yes, I would greatly prefer the "status bar" approach, and, yes, 'rodent skeptic' ?  'rodent deniers' ? perhaps ?  We already do ctrl-F to start a find, Alt-F to find next one (but that has not shipped yet).  Maybe ctrl `<` and `>`   ?    What else uses that combination you know of ?  Or what other app should we copy ?

The Mac is the problem, they have reserved most combinations for OS functions. They don't get passed to an application...

Davo

**Comment by davidbannon** [comment]
OK, 40 degrees here outside so I stayed inside !  And implemented a status bar style search - really like it but need some ideas on what keyboard short cuts I should use.

Firefox shows it search with Ctrl-F, same as -ng, but firefox does not have keyboard shorcuts for search-next and search-previous.

At present, I am using Alt-F for search-next, Shift-Alt-F for search previous. The Shift-Alt-F is a bit of a chore ...

If we can get this wrapped up, I think we could consider a release ....

Davo

**Comment by aguador** [comment]
Oops, looks like my Spanish keyboard shortcuts are not complete!

Are the left and right Alts distinguished on your keyboard? On Mac? And more importantly are the behaviours different? Here the right one is AltGr, which behaves differently and would be a logical alternative for search backward. Another option might be Ctrl-Alt-F which has the advantage of being on the same row (unlike Shift-Alt).

Are you showing the number of "hits" on the search term? That is not usual (not in LibreOffice, Firefox, Featherpad), but is a nice feature in Vivaldi browser. If I see there is only one instance I know not to look further. This would mean that ng would have to search the whole note, not just from the cursor fwd or bkwd.

BTW check out switching help note languages. I have just found that if I switch to English and open from the systray I can access the help notes the first time I pop that menu up, but not a second. If I switch back and forth, the help notes submenu appears again. If you see the same, we can move this to a separate issue.

**Comment by davidbannon** [comment]
Generally yes, most systems distinguish between left and right Ctrl and Alt but not all do and its regarded as bad practice to rely on it happening.   

But Ctrl-Alt-F feels better, pretty sure i can distinguish that combination, will confirm.

No, I have not printed a total number of hits, reasonably easy to do so, I have to keep a running count of which one we are on anyway. So, '4/12' sort of thing ....

Right now, I am trying, desperately, to make it work on the Mac, as soon as I activate the search mode, half the screen becomes a mirror image !  I am suspecting I am not going to be able to do it this way on the Mac ....

No, I cannot replicated that strange help note problem.  I have switched to Fr, ES and back to EN, opening 4 or 5 notes each time.  What do you see when you cannot open a help note ?  No submenu, an empty submenu ?  

Davo

**Comment by davidbannon** [comment]
Pre-release version now available that addressed this issue. Please see https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.31
If you do use it, please watch for anything unexpected and please report what you find, good or bad.

**Comment by aguador** [comment]
The problem was the help submenu not appearing at all. However, that was only on my Cauldron machine with a compile date of 17 Dec. Both Mageia 7 and MX Linux 19 were fine. Cauldron is now OK with pre-release 0.31f.

**Comment by aguador** [comment]
The search bar looks good, but the behaviour is a bit strange. It appears that search disregards cursor placement searching, with the first search starting at the beginning of the file, subsequent searches from the last instance it found.

I opened a short note with three place names that start with "Saint".

- Place the cursor in the file somewhere between two of the instances and search
- Forward search goes BACK to the first instance with successive forward searches to the second and third
- Backward search from that point simply fails to find any instances

Close and reopen the note.

- Start anywhere and search forward finding successive instances and stopping with the last one
- Move the cursor to between the first and second instances
- Search forward fails to find anything
- Search backward goes forward to the second and then back to the first instance

This is potentially confusing for the user. Also there is the perpetual question of whether a search looked at the whole file. With the current setup it would appear that the answer for an initial search is "yes" and for subsequent searches (assuming a "hit" somewhere past the beginning) is "no".

I am attaching the txt export of the note from the pre-release. (Spaces in the name of the note were eliminated, not replaced with "_".)

Sorry, but I think I just rained on your pre-release parade. The only good news is that the separate search box from earlier versions has the same problem -- even with the option marked to search the whole note.

I also put the list in Featherpad which, like most text editors I know, a) highlights all "hits", b) moves from the cursor position, and c) loops back (i.e. goes to the beginning of the file to continue the search once EOF is reached .. and vice versa).

The case sensitive option is a good one to restore at some point as it could be useful for long notes. (Featherpad offers a nice example of how it can be done.)

**Comment by aguador** [comment]
Oops . . .

[Sinromperelhilo-Nombres-Lugares.txt](https://github.com/tomboy-notes/tomboy-ng/files/5888540/Sinromperelhilo-Nombres-Lugares.txt)

**Comment by davidbannon** [comment]
Hmm, so yes, thats how my Find works, it always starts at the top of a note, if you press next, it finds the next one in sequence, if you have moved further down the note yourself in the mean time, yep, it goes back up the what it considers the next found entry.

But if you have moved the cursor away from the last (as in last in sequence) hit, 'next' should move you back to last hit (because thats all that is available), IMHO  ??   Similarly, in reverse.   I suspect that would solve your issue here ?

Or are you saying that search should always start, relevant to the cursor position ?

I could add an option, 'start at current position', bit messy in that I would need to note current position, start at the top and keep going until I found a hit that is past current position.  Will be slower in Windows as I would need to do the (really dumb) calculation of how many line endings I have seen at each stage. (Windows uses a two char line ending in the Text field I search, in Unix its the same one char as real life).

Anyway, agree, could do better !

I would rather not do a **highlight of every hit**, in KMemo, to highlight (other that the one selection type of highlight) I have to alter the markup and thats a slow process, especially with a big note. But do plan, perhaps a future release, to have that 3/7 progress report. And case sensitive is built in, just not brought out, yet, to the GUI.

(I will follow up the question of export file names in the other thread)

**Comment by aguador** [comment]
Highlight is not a big issue, but not tracking the position in the file seems problematic. How do light-weight text editors do search? Super-light Leafpad, which uses a separate searchbox, keeps track of the cursor, going forward and backward to the nearest "hit" from the cursor position -- and can move past EOF if the "next" hit is at the beginning.

This may seems like a corner case, but I can imagine someone searching for something, then perhaps editing something in a somewhat different spot only to resume the search later and miss an instance of the search term.

The ability to return to the beginning of the file (or vice versa) seems important for not missing a hit. Its only minor downside from a user perspective would seem to be not realising that one his looping through again. In heavy duty programs like LibreOffice one can see from the page number that one has returned to the beginning point. If there is a counter, that would help with long notes with a substantial number of "hits" -- but even that does not seem to be crucial.

**Comment by davidbannon** [comment]
OK, try one of these.  Each zip file contains a tomboy-ng binary only, unzip which ever one you are using somewhere out of the way, make sure your real tomboy-ng is not running and start this one up. It 'should' pick all your settings ...
It has, I think, all you ask !  Search starts at current cursor, rolls over at either end, has a hit counter and a count of how many hits down from the top you are.
Seems to all work, including the feature I wanted, enter a find term, press Enter, Enter, Enter and you will be on the third instance.
I have a test note with 40,000 lines, it can search that in 50mS!
[tomboy-ng-gtk.zip](https://github.com/tomboy-notes/tomboy-ng/files/5897741/tomboy-ng-gtk.zip)
[tomboy-ng-qt.zip](https://github.com/tomboy-notes/tomboy-ng/files/5897742/tomboy-ng-qt.zip)

**Comment by aguador** [comment]
First the good news: search from the cursor seems to work (at least with backwards search).

The bad news (testing with my small file and the gtk version on E):

- Forward search moves to the first instance after the cursor location with the arrow, key binding or Enter
- Once a "hit" is found, forward search does not move beyond it (neither arrow nor Alt-F nor Enter) UNELSS the cursor is moved from the "hit", in which case it will move to the next "hit" only
- Searching backwards moves successively through the "hits" with the arrow (not with the key binding, which remains on the "hit")
- In the foregoing cases, the counter shows the number of the hit over 0, that is X/0
- Searching with Enter shows the counter properly (with total number of instances), but will not move beyond the first instance found (unless you move the cursor and click after the search term in the search box - extremely handy!)
- When using the arrows to search, Cntl-F locks up so the search bar cannot be closed
- (Aside: in 0.31f, "EditSearch" appeared in the search box. In this one you referenced earlier code because "Buscar" appears.)

Frustrating observation: at some point I generated the following warning in the terminal:

`(tomboy-ng:14720): GLib-GObject-WARNING **: 14:42:27.756: ../gobject/gsignal.c:1278: no emission of signal "key-press-event" to stop for instance '0x22d6c20'`

However, I did not notice until after closing ng and was unable to reproduce it later.

**Comment by davidbannon** [comment]
That is a worry. 

Firstly, we must note that the arrows and the binding keys are Next and Previous find, they should not be use to initiate a find. That explains why you are seeing eg 5/0, you have not hit `<enter>` in the Find field. The indexing of a large note is slow, I only do it when user hits enter in the field. It seems to me everyone would type `some term<enter>` to do a an initial find.  If you want to search backwards, well, I don't know. But I am getting worried this whole search interface is getting too complicated. You could search forward once with the <enter> key and then press Ctlrl-Alt-F twice if you really must see the total count updated ?

Maybe I can detect that it is going to display '0' and then (and only then) do a index ? But if someone alters the text in the Find field and then uses mouse to press backward arrow, it will still be wrong.   Perhaps the backward search is redundant, now Find rolls over, the interface is simpler if I remove the backwards Find altogether ?

It does not explain the other things you report. I cannot replicate it in the note I have been using as a test note **but I can in a note that contains UTF8 characters**, and I am sure your notes have a lot of UTF8 !

Need to do some work this morning, will have a play this afternoon.

I am on quite short notice here now, I really want that new Tomdroid code (to replace my clunky ssh based code) in Debian and Debian is about to freeze ....

Davo

**Comment by davidbannon** [comment]
Yep, a UTF8 issue. I normally test with a note with UTF8 content but this time choose one with lots of repeating words, should have known better !

Anyway, another new pair of test binaries.

Davo
[tomboy-ng-gtk_1.zip](https://github.com/tomboy-notes/tomboy-ng/files/5899271/tomboy-ng-gtk_1.zip)
[tomboy-ng-qt_1.zip](https://github.com/tomboy-notes/tomboy-ng/files/5899272/tomboy-ng-qt_1.zip)

**Comment by aguador** [comment]
Much better. My head was spinning after all the gtk variations I tested, but I did a bit of testing from TOF with Qt which did have some differences. Note on my machine I got some Qt related messages:

```
QApplication: invalid style override 'gtk2' passed, ignoring it.
	Available styles: Adwaita-Dark, Adwaita, qt5ct-style, Windows, Fusion
qt.qpa.xcb: Unhandled client message:  "_E_COMP_FLUSH"
qt.qpa.xcb: Unhandled client message:  "_E_COMP_DUMP"
```
The first is the initial warning about the override (haven't been able to fix this completely as something seems to reset it when I try); the later messages appeared from time to time, but I did not see exactly what triggered them.

My conclusion is that this is basically OK without the key bindings. They are causing problems, including an additional one in Qt for some reason. For 0.32 (and perhaps forever), drop them.
[ng_within_note_search.pdf](https://github.com/tomboy-notes/tomboy-ng/files/5899745/ng_within_note_search.pdf)

**Comment by aguador** [comment]
Taking a quick look back over the test results, I think the only issue without using bindings is the initial use of the arrows when there is not search term found. If it can be fixed easily, that sounds like a simple "known issue" for the release.

**Comment by davidbannon** [comment]
Seems several issue at play here.
* `X` - thats easy, its just a place holder so we don't end up with a new entry in translation text, I should have blanked it at startup
* Differences between hitting the arrows and using key binding - in the code there are none !  The key is detected, and it hits the arrow for us. (You noticed the arrow flicker).  So, what is happening there in you case (but not mine) must be some other influence.
* Ctrl-F not closing ?  I cannot replicate.
* `F` appearing in search term ?  That sounds to me like focus is being moved from the Edit field to, perhaps the arrows ?  In my systems, the arrows cannot hold focus, but, maybe in a latter version of QT ?  That may explain a several things including the two above.

I will assign key handlers to both the arrow control and the panel itself, there is nothing else there capable of responding to a key press.

Trouble is that unless I can replicate this myself, I am guessing as to exactly whats happening and won't know for sure if I have it or not !  Might try my bullseye test bed, it has the newest of everything as far as I can tell.

Davo

**Comment by davidbannon** [comment]
OK, I cannot replicate in Bullseye either.  I don't recognise your reference to TOF in your report, what does that mean ?

I don't feel like removing the keybinding, too many people use them I am afraid. And from your report, I don't see the keybinding as a particular issue (because as I noted, the keys are an immediate redirect to the arrows any way).  

Can you tell me Distribution / Desktop you are using ?  I have better try and build one and see if I can understand it there.  

In the mean time, I will add some code that forces the Edit to get back focus after either a key press or a arrow press. I don't believe its necessary but am getting desperate !

Davo

**Comment by davidbannon** [comment]
OK, I now concentrating on this business of the Find Panel not closing on a Crtl-F.  I think its the key to whats happening and the other things are just side effects. Yet another binary attached, QT only as that seems to be at least representative if not chief offender ?

I obsessively force the edit field to have focus, it handles the keystrokes.  I have also added a few lines of debug that might be worth watching as you test.  Look for, in particular either no debug line when closing the panel or two lines, Hiding and Exposing in response to one Ctrl-F.

In the mean time, I'm testing on every (virtual machine) OS I can muster, and not seeing this problem so far (about half way through my list).  Its the first time I have used this UpDown control, gee, I wish I had just used two ordinary buttons but its too late now !
[tomboy-ng-qt_2.zip](https://github.com/tomboy-notes/tomboy-ng/files/5901147/tomboy-ng-qt_2.zip)
 

Davo

**Comment by davidbannon** [comment]
Some progress, I can demonstrate the "fail to close Find Panel" issue in Fedora 33 in GTK2, (cannot get it to run Qt at all).
Thats using the test binary of a couple of days ago, using the (again GTK) test binary from today, tomboy-ng-gtk_2.zip, the problem goes away. I am assuming my forcing the focus back to the Edit field has fixed it.  So, its not a Qt thing, .. ?

If it was anything other than Fedora Gnome, I'd install Lazarus on it and try and debug it all but I find Fedora just about unusable !  I cannot drop a file on the desktop, it won't show the SysTray (without tint2) and it won't even let me minimise an app, I have to close everything I want out of the way !

I guess I will have to debug it somehow on Fedora but not right now. Maybe we can find an example of this bug on some vaguely (IMHO) user friendly distro ?

I am going to have to run with it very, very soon ....

Davo

**Comment by aguador** [comment]
> Some progress, I can demonstrate the "fail to close Find Panel" issue in Fedora 33 in GTK2, (cannot get it to run Qt at all).
> Thats using the test binary of a couple of days ago, using the (again GTK) test binary from today, tomboy-ng-gtk_2.zip, the problem goes away. I am assuming my forcing the focus back to the Edit field has fixed it. So, its not a Qt thing, .. ?

No not Qt, it was apparently the focus issue. As you will have seen from my off list response, tests confirm that problem is gone.
> 
> If it was anything other than Fedora Gnome, I'd install Lazarus on it and try and debug it all but I find Fedora just about unusable ! I cannot drop a file on the desktop, it won't show the SysTray (without tint2) and it won't even let me minimise an app, I have to close everything I want out of the way !

I think I can almost imagine ways to work with Gnome (not that I want to or will). I don't like keeping files on the desktop, but banning them is stupid as placing a couple there you are working on makes sense. As for minimizing, you could send to another workspace, but since you are not allowed to keep a pager on display, you need to remember the key binding. Yep, it's all a pain -- and for the honor of running a bloated resource hog of a DE.
>
Hope the binding can be fixed on ng search . . . .

**Comment by davidbannon** [comment]
Attached are two binaries that now accept a command line switch swapping from `Ctrl-Alt-F` to `Shift-Alt-F`, `--shiftaltF-findprev`

I think I have altered all the necessary helps etc, if I have missed one, well, I am afraid that is how it will have to be. :-)

Obviously, we can fix something in the github distributed versions, and at least I think we have the Debian one working well on Debian.  But I am pretty sure its right now.

[tomboy-ng-gtk_3.zip](https://github.com/tomboy-notes/tomboy-ng/files/5907478/tomboy-ng-gtk_3.zip)
[tomboy-ng-qt5_3.zip](https://github.com/tomboy-notes/tomboy-ng/files/5907480/tomboy-ng-qt5_3.zip)

Your patience has been remarkable !

Davo

**Comment by aguador** [comment]
No problem with my patience. You are doing all the work!

It is late here (22 hours behind you), but I just did a very quick check on MX Linux (XFCE) and the switch works with gtk. However, with Qt the Shift-Alt-F still adds and F to the search box.

Earlier today I wondered, if Enter searches next, is there an available modifier to add to Enter to search prior and forget "Alt-F" altogether?

**Comment by davidbannon** [comment]
> However, with Qt the Shift-Alt-F still adds and F to the search box.

Oh, that could be a killer !

> Earlier today I wondered, if Enter searches next, is there an available modifier to add to Enter to search prior and forget "Alt-F" altogether?  

No, that would not work because we need to be able to use the same key binding in a normal note edit mode. And there, users would expect Enter to add a newline.  So we have to associate Find-ing with something other than Enter, and 'F' makes sense. Its a side issue that Enter works when you have the FindPanel open AND it has focus.  You can have the panel open but focus is on the KMemo, like that Enter will not trigger a Find.

I have no idea how Shift-Alt-F (when set to shift-alt-F mode) is putting an f in the f-ing edit field !   As soon as its detected as being a "do something special" keystroke, it is nulled out so it cannot go anywhere ....

Question : for your test, when you ended up with F appearing in the Edit field when pressing shift-alt-F, it was in shift-alt-F ?

I have a MX Test VM, will try to replicate.

Davo

**Comment by davidbannon** [comment]
No, I did not have a MX, but do have one now. 19.3, XFCe, looks pretty good once I worked out how to turn off that stupid transparency. XFCe can be made look and work quite well ...

So, tried both Qt and GTK, I cannot replicate what you saw.  Are you sure you had it switched to --shiftaltF-findprev mode before pressing shift-alt-F ?  If was looking for the Ctrl-Alt-F combination, it will let other combinations through with out interference. So, it will only grab, use and not pass through Shift-Alt-F when its in --shiftaltF-findprev mode, like wise, it will grap, use and not pass through Ctrl-Alt-F in the default mode (but like I I found that comination does not get that far in MX anyway).

Hmm, or were you using the KDE version of MX ?  OK, I'll pull down one of those too...
(bet its eye candy is even worse ...)

Davo

**Comment by aguador** [comment]
I always use the XFCE version . . . . 

I just tested again and the problem occurs under one condition in Qt: the term you are looking for appears further into the file. In my quick test, the cursor was at the beginning of the file, the searched for term below. Searching prior worked fine with Gtk, but produced the "F" in the search box with Qt.

I don't have more time to test right now, but will look with Enlightenment later today. I also need to figure out about the keyboard in XFCE because in one of these tests it changed the keyboard to English which is complicating writing the messages! I hope it is not another binding conflict.

**Comment by davidbannon** [comment]
OK, think I am beaten !
I have found that for some colour themes, QT blanks out selected text when a control looses focus.  So, when I select text in KMemo after a Find, and keep the focus on the FindPanel, the text in KMemo ie either white on a white background or black on a black background.

The ONLY way around it is the move focus back to KMemo when we Find something. But if the use presses Enter to trigger that Find, they may well press Enter again, to Find the next one. And if they do, that will erase the first find, after all, that Enter is going to KMemo and when Kmemo (or any other editor) receives a key keystroke (other then a special key) when something is selected, that something is replaced with the keystroke's character.

All I can do is totally ignore an Enter in the Find Field (actually, I will wriggle the little help note "press Alt-F etc") and wait until they use one of the key bindings or click an arrow. !  I hate it !

Going to bed, not going to sleep tonight ...

Davo

**Comment by aguador** [comment]
Hope you are able to sleep. This is a knotty one.

Beside what you found (which I can confirm), there are other oddities.

- The good news is that Shift-Alt-F works in Mageia 8 . . . no for the bad:
- The Shift-Alt-F does indeed appear to be changing the keyboard layout in XFCE. It is not a a defined XFCE shortcut from what I have seen, but it still manages to reset XFCE the layout to the defined default, that being the US one given the source of the distro.
- For no search term found, both bindings and arrows still show "not available" rather than "0/0" (both Qt and Gtk)

Non-search related issues with Qt5:

- On start up on both Mageia and MX Linux there is a small window that opens briefly as the program loads. It is really small, so nothing readable. (I noted this with 0.31f Qt that I installed on the MX machine.)
- On Mageia (rpm) the systray icon shows in red rather than yellow. Color is OK on MX Linux which suggests it may be related to that gtk2 style ENV problem I have with E. (So at least this may not be an ng issue!)

OK, I think I. too, need a brief respite at this point.

**Comment by davidbannon** [comment]
I know I keep hammering on about this, please, feel free to ignore, I need to see my thoughts in writing !

Given that I must move focus back to kmemo after each Find, successful or other wise, I must stop the user pressing Enter, Enter, Enter to step through 'hits'. And seems that xfce already uses Shift-Alt-F ?

So, based on something you mentioned a few days ago, the key bindings become Ctrl-Enter and Alt-Enter.  Nothing else.  No cli switch, it works or you use the arrow buttons.
[tomboy-ng-qt_4.zip](https://github.com/tomboy-notes/tomboy-ng/files/5915365/tomboy-ng-qt_4.zip)


Seems to work, I will have to test widely....

And, I must submit what I have to Debian in the next few hours or forget about it.

Davo

**Comment by aguador** [comment]
OK, about to test. Confirmed absolutely that Shift-Alt-F changed my keyboard layout. That is not a documented key binding as far as I could tell, but it definitely caused the problem.

**Comment by aguador** [comment]
Yes! Tested in both MX and Mageia with no problems. If there are no hits the counter appears, but with "not available", but that is not big deal. You can get this out. I am on MX at the moment, but have Cauldron running so will send the modified Spanish help note.

¡Enhorabuena!

**Comment by davidbannon** [comment]
Yep, I have tested Debian Gnome, Debian Mate, Debian XFCe, MXLinux, (and, obviosly U18.04).  All good.
Will try a Fedora or two systems ...
I really don't want to keep interrupting your working day ...
Davo

**Comment by aguador** [comment]
Help note should be in your inbox.

**Comment by davidbannon** [comment]
This one is quick, can you give me spanish for `Find : Ctrl-Enter, Backward Find : Alt-Enter` ?

I will manually edit the po files ....

`rsSearchNavHint = 'Find : Ctrl-Enter, Backward Find : Alt-Enter';`

Davo

**Comment by davidbannon** [comment]
> Help note should be in your inbox.

Got it, thanks !
Davo

**Comment by davidbannon** [comment]
For crying out loud !
**Its 3:00 where you are, knock it off !**
Davo

**Comment by aguador** [comment]
> This one is quick, can you give me spanish for `Find : Ctrl-Enter, Backward Find : Alt-Enter` ?
> 
> I will manually edit the po files ....
> 
> `rsSearchNavHint = 'Find : Ctrl-Enter, Backward Find : Alt-Enter';`
> 
Sorry I didn't see this one before I called it quits. I used Search Next/Search Previous for the Spanish. It was in the note. I'll check to see if you caught it in the .po.

**Comment by aguador** [comment]
Should have checked first. You got it, which is great. I'm happy that things are up-to-date for Debian. Once Deb 11 is out and MX Linux has had a chance to get 21 together, I will look for it in the repos!

FYI: the string for the Shift-Alt-F switch is still in the .po, I suppose because you edited it manually and it will disappear later.

**Comment by davidbannon** [comment]
OK, done in version 0.32.  And quite a job it turned out to be, as we hoth know !
:-)

Davo
