### ISSUE TITLE
Feature Request: Customizable keyboard shortcuts

### ISSUE THREAD

**Issue by turgutgenc1** [tomboy-notes/tomboy-ng#225]
It would be great if you could provide a method to modify keyboard shortcuts. I'd prefer to set "Close window" to Ctrl + W as an example.

**Comment by davidbannon** [comment]
Yes, I can understand where that would be useful but I am not necessarily sure its practical. It would be quite a lot of work and might be awkward looking up a table every time a key is pressed in case its mentioned in the current shortcut table.  I'll have a think about it but I am a bit worried it might just be too hard to do without slowing us down more than I care to permit.

Davo

**Comment by davidbannon** [comment]
I have looked over my code and, sorry, I really cannot justify the performance penalty that this would involve. I might revisit it if I find a better way to handle the problem but afaid, right now, its a "no".
Davo
