### ISSUE TITLE
Blurred text and icons on Windows

### ISSUE THREAD

**Issue by WFreude** [tomboy-notes/tomboy-ng#229]
Why are text and icons so blurred on Windows 10? 
![Tomboy2](https://user-images.githubusercontent.com/16316918/107865201-6d08a480-6e64-11eb-8629-0a5093007dfd.JPG)
![Tomboy](https://user-images.githubusercontent.com/16316918/107865202-6da13b00-6e64-11eb-8d3b-b3dadf80f91b.JPG)

**Comment by davidbannon** [comment]
Do you have a high DPI screen ?

Davo

**Comment by davidbannon** [comment]
OK, so this is seriously embarrassing ! I can fix that "blurred" with a very simple compiler switch.  Sorry, this just shows how bad my Windows knowledge is !

<img width="359" alt="DPI_Aware" src="https://user-images.githubusercontent.com/6291248/107869056-28b9ea80-6ede-11eb-8231-0dc07e2d441a.png">

But that lovely sharp text and images just highlights another issue, everything (in tomboy-ng) in Windows is too large.  The little speed buttons are twice the size they should be, you can see how the bitmap images just fill the center section of each button. 
Now I really have to fix that !

Thanks (seriously, thanks) for highlighting an issue I have been ignoring ....

Davo

**Comment by davidbannon** [comment]
No, while my fix for the Blurring is OK, I cannot adjust the sizing.  

I will make a 0.32b release shortly that cleans up all that Windows Blurring ....

(Sorry WFreude, some notes for myself).

On my laptop, in Windows at 150% scaling, things look too big. But any attempt to adjust that makes either the Desktop 100% scaling all wrong or my beloved's Windows Laptop at 250% scaling all crowded into a thumbnail.

If I am going to do anything about scaling, its going to have to involve a couple of setting that the the end user selects to suit themselves. Right now, Lazarus's automatic scaling is a reasonable (but not good) compromise. Hmm....

Davo

**Comment by davidbannon** [comment]
OK, this issue is fixed in version 0.32b, will close.  
Thanks for the report.
Davo
