### ISSUE TITLE
ctrl-z undo needed

### ISSUE THREAD

**Issue by JBKingdon** [tomboy-notes/tomboy-ng#230]
I know there is an earlier issue for this, but it seems too important to not mention it again. For several years I used Tomboy extensively for organising notes, effectively working in it continuously throughout the day. A recent machine upgrade came with -ng and I'm now having to switch away to an alternative as it's simply unworkable to not be able to undo the sort of accidental edits that inevitably happen from time to time.

Please reconsider adding a ctrl-z/undo feature.

**Comment by davidbannon** [comment]
Hi JB, thanks for the report. I have added a "roll back" that will let you recover to where you either opened the note or last changed its title. But I cannot, at present, see my way clear to add a genuine undo/redo facility. The underlying component providing the editor does not do undo/redo and its author has indicated he is unlikely to add that or any other major capability. Its actually quite a difficult thing to add and would increase complexity, slow the app down considerably.

So, sorry, I don't see it happening in the near or even medium, future.

Davo

**Comment by frederickjh** [comment]
Sorry to hear that as this has been bugging me too since I moved from Tomboy to Tomboy-NG Just came here to create an issue but @JBKingdon beat me to it. It has bitten me a couple of times, when I accidentally select some text then start typing which deletes it and then there is no undo (Ctrl-z). Most times my clipboard manager saves me in that it has a copy of the deleted text but not having an undo a major shift away from what users expect in a text editor. I cannot thing of a GUI text editing app that does not have this feature.

**Comment by JBKingdon** [comment]
Yes, it's a shock when it bites isn't it :)
Reflecting on it I realised I'd come to use Tomboy in a way that it was probably never intended, with large multi-page documents and a light weight document management system that let me not have to worry about where I was storing the notes. Viewed in what I suspect was the original intent of managing electronic sticky notes with small amounts of text the lack of undo is much more tolerable, and I guess that's how the vast majority of users treat the app.

**Comment by frederickjh** [comment]
I am pretty much using it as electronic sticky notes and I miss it terribly. Stuff happens, you accidentally brush too close across the trackpad with your wrist selecting text, which in the next keystroke is gone.

**Comment by davidbannon** [comment]
Yes folks, I understand where you are coming from, I make mistakes sometimes too !

But like I said, its not something I can add to tomboy-ng, my code. Its something I would have to add to KControls, someone else's code and it would take me some time to find my way around his code. And I suspect he has left undo out for a reason, its hard !

I have a small list of other things I need to do to tomboy-ng, all the really easy ones are done so its now a slow moving list. I will add undo to that list and see just what I can find time to do. I cannot in any way promise anything will come of it, but I will try.

(I believe there is a generic undo library in LCL but know nothing about just what it applies to....)

Davo

**Comment by davidbannon** [comment]
OK, the release candidate in the github release page does this reasonably well. Its in feature freeze now and the candidate seems to pass all my tests.  So. will close this ticket.

Thanks for your input !
Davo

**Comment by frederickjh** [comment]
@davidbannon does this mean you have released this on GitHub and now we just need to wait for the packaging folks to do their thing before we see it?

**Comment by JBKingdon** [comment]
Fantastic! Tested with tomboy-ng-0.32i-2.x86_64.rpm and seems to be working fine.
Many thanks David, I'm sure this will be much appreciated.

**Comment by davidbannon** [comment]
JB - thanks for testing !

Frederick, there are packages for all supported platforms for a version 0.32i, its a release candidate for 0.33 but I have not yet formally released it.  That means -
1. The wiki release page does not know about 0.32i, so don't look for it on https://github.com/tomboy-notes/tomboy-ng/wiki/Download_Release
2. They **are in** the github release page, https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.32 - its somewhat harder to find what you are looking for I am afraid. Lots of things in there ...
3. If by "packaging folks" you mean Ubuntu PPA, no, it won't get to the PPA until I do a formal release of 0.33.
4. If by "packaging folk" you mean (eg) Debian, no, its a very long way away. Debian is in freeze right now and not accepting any new packages. Eventually they will release bullseye and some time after that I can submit whatever we have then to their Updates model. I don't, yet know how that works. So, if you are still reading, perhaps you would be better getting it from item 2) above ?

Davo

**Comment by frederickjh** [comment]
Thanks @davidbannon for that explanation. Sorry it did not click with me when you first wrote that it was in the "release candidate" that this was a release build up to a stable release.  Thanks for your hard work on this!
