### ISSUE TITLE
How can I define the hotkeys?

### ISSUE THREAD

**Issue by nickbe** [tomboy-notes/tomboy-ng#232]
Where can I find the definition of hotkeys for "New note", "Search/Index", "Create Link from selected text" ?
Can I enable ESC to close the current note? This key is used a thousand times a day in the old Tomboy (literally)

**Comment by davidbannon** [comment]
The hotkeys that relate to the note editing are in 'editbox.pas', around line 2670.  Some others are main in main from memory....
Davo

**Comment by nickbe** [comment]
Thanks. now that I know how to build it I will look into several small adjustments and will hopefully be able to contribute something over the next weeks.

**Comment by davidbannon** [comment]
And all done here too ?
Thanks
Davo
