### ISSUE TITLE
How is tomboy-ng compiled?

### ISSUE THREAD

**Issue by nickbe** [tomboy-notes/tomboy-ng#233]
Can the project be compiled with typhon or lazarus for windows?

**Comment by davidbannon** [comment]
I have never tried with typhon, tomboy-ng is built using Lazarus.  This wiki page should help you https://github.com/tomboy-notes/tomboy-ng/wiki/Building-tomboy-ng

Davo

**Comment by nickbe** [comment]
Found it 😁 thanks. I must have missed that page.

**Comment by davidbannon** [comment]
All done here apparently !
Thanks
Davo
