### ISSUE TITLE
Inline Images are not saved

### ISSUE THREAD

**Issue by nickbe** [tomboy-notes/tomboy-ng#234]
I can paste an image from my clipboard into a note (windows), but it doesn't seem to be get saved.

**Comment by davidbannon** [comment]
While the underlying component used for editing a note, kmemo, can handle images, the tomboy standard file format cannot.  The original Tomboy did not handle images.

So, all that needs to be done to image enable tomboy-ng is to determine how and where the image data is saved. When I first started out, there were still a lot of Tomboy users so I have been careful to comply with the Tomboy format, not sure thats so important now.

So far, over several years, I have had only one request to add images to tomboy-ng so I have not worried about it.

Davo

**Comment by nickbe** [comment]
Well I think that depending on what you do with your notes, images are important enough nowadays. For example I'm making a lot of notes regarding design aspects and other things which require screenshots. 
Maybe it would be a nice idea to let the user choose between two formats. A standard richtext in delphi when saved should handle inline coded images pretty well. So yea I think it would be great to have that.

Cheers
Nick

**Comment by nickbe** [comment]
Any news regarding this? Basically the missing option to use inline images still prevents me from using tomboy finally. I still think that it should be possible nowadays.

**Comment by davidbannon** [comment]
No, sorry Nick, no news either way.  My issue is that its a big departure from the standard Tomboy note format, a big change to saving and loading. If you paste in an image, I'll need to scale it in some way, most people who have images these days have something like 3000x2000 pixels !  A lot of extra code.

Lots of decisions to be made about how its done and, it seems, only one person with any interest in it. 

I need to establish a planning committee   :-)

But definitely not a 'no' yet.

Davo

**Comment by fuzzy7k** [comment]
I agree that adding inline picture display would be a burden. Implementing that cross platform would not be fun. 
Do they need to be inline though, or can they just be links? 
I rather like having links to images. It keeps the focus on the content with access to a visual. 

In that case, maybe a working implementation for the paste use case would just be for tomboy to save the file somewhere and insert a link. I am assuming that tomboy-ng can recognizes file uri's and make them clickable.

**Comment by davidbannon** [comment]
Yes, Fuzzy, I have played a bit, more as a thought experiment than in code, along those lines. The simplest approach would be an in line link pointing to a user managed image.

Next, maybe a small, fixed size 'thumbnail' image if you hover the mouse over the link, or just a text hint with the image name. Click it and we open the real image with what ever the user's favorite image viewer is. Focus moves from the note to the image viewer.

In that sort of thing, tomboy is not managing the images at all, the user just inserts a link to an image of their keeping. So, tomboy-ng would make no attempt to sync or archiving the images, if the note appears on a second machine and that image is not there, NMP (not my problem). 

I am not sure thats satisfactory enough for me to present as a solution .....

Davo

**Comment by davidbannon** [comment]
While the newly released tomboy-ng 0.40 still does not save images, I do have a solution of sorts. Its now possible to embed "file links" that will point to an image and open that image, with your favourite image viewer, when clicked. Given the other constrains we have discussed, I think thats about the best I can do.

Thanks for your suggestions and feedback, valuable !

Davo
