### ISSUE TITLE
Tomboy REST API

### ISSUE THREAD

**Issue by syskill** [tomboy-notes/tomboy-ng#236]
I've been using the Tomboy app on Linux and Windows, and Tomdroid on my phone, to sync with Rainy, which implements the [Tomboy Web REST API](https://wiki.gnome.org/Apps/Tomboy/Synchronization/REST/1.0). Turns out, the Tomboy app is unusable on a 4k monitor on Windows, and unfortunately TomboyNG doesn't know how to use the REST API. Is this a planned feature?

**Comment by davidbannon** [comment]
syskill, no, sorry, I don't think its likely.   A couple of reasons, tomboy-ng already has a one to one, cable based sync with Tomdroid. The Rainy sync is based on OAuth One and requires Mono, neither technology is very popular these days as I understand it. 

Personally, I found the Rainy sync just a bit unreliable, I used it for some years and had some problems that were, from memory, quite difficult to recover from.

You might like to consider https://github.com/grosjo/tomboy-reborn

Davo

**Comment by davidbannon** [comment]
OK, hope syskill is aware you can sync to a a sshfs or any other disk share such as google drive, smb etc.
If you don't mind, I will close this ticket now.
Davo

**Comment by davidbannon** [comment]
,

**Comment by davidbannon** [comment]
.
