### ISSUE TITLE
Request to add in the Wiki, an explanation on how to rename a Note

### ISSUE THREAD

**Issue by devEric69** [tomboy-notes/tomboy-ng#237]
Hello,
 
This is not a bug report. It's just a suggestion to add a item-help in the Wiki. 

By default, every new note is created with a regex name "New note YYYY-MM-DD ...". Normal. But, I would just suggest you to indicate, to explain how to "rename as..." or "save as..." a "New note 2021-04-19 11:30:48.536" to "Hello_my_note", for example (i.e. by simply editing the _header hyperlink_ inside the note). Really, when we don't know at the beginning, it's not obvious and we may quickly end up with unclassified "New note *" that have become unclassifiable, asking us if the application doesn't know how to do that after all... I "know" you as a Lazarus developer, so I've persevered, thinking that there must be a trick, somewhere. But it may discourage others.

Congratulations for your application.
Regards.

**Comment by davidbannon** [comment]
Hmm, interesting thought.  I hate it when 'obvious' things are not documented and someone not in the know searches endlessly.  But thats the case here. 
I will see what I can do !
Thanks
Davo

**Comment by devEric69** [comment]
Thank you (I searched for a while, before I found it :)

**Comment by davidbannon** [comment]
Hmm, I don't see a sensible place to add the necessary line to the wiki. So I have added it to the README.md file (visible on the opening page) and in the HELP notes.  But end users will not see the new help notes until they get a new version (and the notes get translated).
Original Tomboy had a "getting started" note for new users, perhaps I need to consider that approach ? I would open that note automatically if its the only note in the repo, other wise it would be listed as a note unless user deletes it.
Thanks (its hard to think like a new user when you have used this app and its predecessor for something like twenty years !)
Davo

**Comment by devEric69** [comment]
Hello,

Thank you for the help note in the README.md. In fact, it's indeed obvious when we know it. 
Now, it could be true that a person who is in a hurry, who doesn't know what to use, and who is testing different lightweight softwares in order to compare a "simple notes" replication system, may quickly pass Tomboy by saying to himself that it's just  
devolved to create short-lived notes that don't need to be named after all, a bit like some virtual "post-it" notes.

>
> Original Tomboy had a "getting started" note for new users, perhaps I need to consider that approach ?
>

Personally, I didn't know Tomboy. But at the time (20 years ago), I was using a similar mini-soft on Palm OS 
(OS bought by Hewlett Packard, who didn't do anything in fact with it, after all; and then Android came out...). So, I like this spirit 
with a very simple interface: it allows us to do many, many things rapidly, before moving on to Office365, Google drive applications... 

>
> its hard to think like a new user when you have used this app
>

In fact, I am using it as my daily post-it note organizer, in one of my workspaces. As an anecdote, two other people are asking me how to share documents (office suite like *.ods, *.odt, ...) and working notes, with each other, in a collaborative cloud. So, I suggest a quick solution using Tomboy (one person is uncomfortable with english language, hence my current interface translation tests) which is:
- create a Microsoft OneDrive (just because this is the drive in the "cloud" that I'm using, that I know) accessible to both, in read-write mode (I call it 'remote_oneDrive');
- install replication between their local OneDrive directory (I call it 'local_oneDrive') and the shared 'remote_oneDrive' directory;
- install Tomboy on their OS;
- install replication between the Tomboy working directory and the local_oneDrive directory;

Then they could organize themselves as best they can. Basically:
- create named directories in 'local_oneDrive' (with the *.ods, *.odt, images, ... all their working files classified in them);
- create notebooks in Tomboy named like the precedents directories;
- create prefixed notes, prefix with the same name as the *.ods, *.odt;

It would allow them to continue using their usual tools (calendar, webmails, etc).

Regards.
