### ISSUE TITLE
PGdkDisplay -> PDisplay

### ISSUE THREAD

**Issue by salvadorbs** [tomboy-notes/tomboy-ng#239]
Hi,

I was looking at your code for a problem in my project when I noticed this comment:
https://github.com/tomboy-notes/tomboy-ng/blob/1ae09f5d38342168eff6eb8e931940d2fbecd061/source/mainunit.pas#L459

You can use method https://developer.gnome.org/gdk3/stable/gdk3-X-Window-System-Interaction.html#gdk-x11-display-get-xdisplay to get X Display from GDKDisplay (see https://github.com/salvadorbs/AsuiteComps/blob/beab429e63a120d9e2e25c55b64dc092e1c271e9/library/platform/unix/Hotkeys.Manager.Platform.pas#L545).

Of course you will also have to insert the declaration to the external method (The method is present in the GDK module of GTK3 + and there is no pascal binding of it, yet). See https://github.com/salvadorbs/AsuiteComps/blob/beab429e63a120d9e2e25c55b64dc092e1c271e9/library/platform/unix/Hotkeys.Manager.Platform.pas#L93

I hope I was helpful. Thank you

**Comment by davidbannon** [comment]
Thanks salvadorbs, that may well be useful info. I am not concentrating too much on GTK3 at the moment, its so incomplete at this stage but good to keep my code comfortable with any future improvements.

If the "problem in your project" relates to SysTray, you may be interested in some progress I have just made with Debian/Fedora and Gnome, I can now display a systray icon on those 'awkard' platforms.  Still testing and writing it up so have not gone public yet. Let me know if you want details (as they exist at present).

Davo

**Comment by salvadorbs** [comment]
> If the "problem in your project" relates to SysTray, you may be interested in some progress I have just made with Debian/Fedora and Gnome, I can now display a systray icon on those 'awkard' platforms. Still testing and writing it up so have not gone public yet. Let me know if you want details (as they exist at present).

For now, I'm testing it in Ubuntu and KDE Neon, but I will test other distro (but i don't know when). For now on KDE Neon, I have this issue with trayicon: https://forum.lazarus.freepascal.org/index.php?topic=54416.msg404179#new

Thank you very much

**Comment by davidbannon** [comment]
Time to close this too.
Thanks salvadorbs  for your input, very useful !

Davo
