### ISSUE TITLE
tomboy-ng slow for large notes >50k

### ISSUE THREAD

**Issue by monperrus** [tomboy-notes/tomboy-ng#241]
Hi Davo,

FYI, one of my notes is large (more than 4000 lines, more than 50k characters) and tomboy-ng is terribly slow for editing it.

Thanks, --Martin

**Comment by davidbannon** [comment]
Yep Martin, that is generally the case.
On my pretty fast hardware, I regard 50K as a biggish note.  Not a lot I can do I am afraid, its about the upstream KMemo component.
I sometimes consider stripping some of the features it has, such as embedded images etc but I have no idea if it would help and it would involve forking kcontrols, something I do not want to do. TK has been very helpful ....

Davo

**Comment by monperrus** [comment]
OK, thanks for the explanation.

**Comment by davidbannon** [comment]
Just a follow up before closeing this note, v0.34 has a couple of speed up improvements, neither major things but may help a little. But the truth of the matter really is, varying hardware not withstanding, I tend to think of 50 k and a up around the maximum limit one note should be.  

But thanks for your input here too !

Davo

**Comment by monperrus** [comment]
FYI, really suffering from this limitation.

Tomboy handles well much larger notes.

**Comment by davidbannon** [comment]
monperrus , I understand but there is little I can do to help. The problem relates to my choice of a ready made editing component, KControls. I initially used a different one, RichMemo but found its cross platform support very disappointing.

KControls is a much larger, more ambitious unit, its capable of embedding images, tables and drawing and is all written in Pascal so its portable to a very large number of platforms. I suspect the price I pay for that flexibility is overhead that slows us down.

RichMemo has a great deal more platform specific code, as a result, many features are not working on all my key platforms. While its improving, and I try it out from time to time, contributing some tweaks, its not yet ready for use. It may be at some stage, and if it appears to be continuing to be well maintained (important given its platform dependence) I may move over to it. But not yet.

In the mean time, maybe, just maybe, I will look at striping out some of the non-text capability from KControls, don't know how that will improve things or even if its possible. And maybe not a job I will enjoy !

Overall, I consider -ng is about notes and "notes" are, implicitly a lot smaller than the ones you are having this problem with. 

Davo

**Comment by monperrus** [comment]
I understand, thanks for the explanation. Indeed, my reading notes are very large, much larger than a shopping list  :)

**Comment by monperrus** [comment]
Which KControls component is used in the main editing window? I can have a look at the options.

**Comment by davidbannon** [comment]
Its KMemo, one of the components in KControls. I am currently using a forked version at https://github.com/davidbannon/KControls while TK decides how he wants to handle multilevel bullets, he is unhappy with my choices in a pull reqest.

The original, and where all pull requests head back to, is at https://github.com/kryslt/KControls.

The issue, if there is an issue, is that KMemo is capable of handing tables, in line images and similar and maybe, just maybe, the extra effort in watching for things like that slows it down. I don't know.

When I make a Debian Source Package, I strip out a lot of the extra code not associated with KMemo but that does not remove the unused code in the KMemo units themselves. On the other hand, the FPC Linker is very good at removing unused code at link time .....

Davo

**Comment by monperrus** [comment]
> I am currently using a forked version at https://github.com/davidbannon/KControls

That's good! It means that we have full control over it if we identify the one feature which makes everything so slow for large notes.

**Comment by pa-0** [comment]
Just wanted to add (in case it helps) this snippet I found in an [issue 56 of KControls's upstream repo](https://github.com/kryslt/KControls/issues/56), which also reports slow responsiveness with larger notes:

> I have use this code fixed it.
> 
> ```
> try
> 	KMemo1.Blocks.LockUpdate;
> 	while BlockNo < Kmemo1.Blocks.Count do begin
> 		SomeCrazyProcedure(KMemo.Blocks.Items[BlockNo]);
> 		inc(BlockNo);
> 	end
> finally
> 	KMemo1.Blocks.UnlockUpdate;
> end;
> ```
> 
> https://wiki.lazarus.freepascal.org/KControls/KMemo_notes [Locking chapter].
> 
> Thanks for ur reply.

I believe @davidbannon indicated that he had not yet implemented any speed-improving algorithms in the code, including the above.

**Comment by davidbannon** [comment]
Thanks Peter, yes, tomboy-ng does use locking everywhere it possibly can.  Without it, 50K notes would be totally and completely unusable. 5K notes would struggle.

Davo
