### ISSUE TITLE
Template Content is not being used.

### ISSUE THREAD

**Issue by davidbannon** [tomboy-notes/tomboy-ng#247]
When making a new note based on a Notebook Template, the extra content that may (or may not) be in a template does not make it to the new note.

**Comment by semugu** [comment]
Thanks, Davo!

In my old Tomboy-version I could define the template under settings/tools. The "new" solution I like better as I now can create several templates :-) It is, however, more hidden.

I will check for updates of 0.33d. :-)

**Comment by davidbannon** [comment]
OK, fixed in newly released v0.34, will close this ticket.
