### ISSUE TITLE
.dmg not created for v0.33a

### ISSUE THREAD

**Issue by gjarboni** [tomboy-notes/tomboy-ng#248]
Not huge, but no .dmg file exists for v0.33a. There is a .dmg file for v0.33. I'm adding in case the lack of a .dmg file is a symptom of a bigger problem. Thx!

**Comment by davidbannon** [comment]
gjarboni, very sorry. Its a symptom of my carelessness, nothing more.  I built it three weeks ago, just have forgotten to upload it.
Its there now, thanks for pointing this omission out to me !

Davo

**Comment by davidbannon** [comment]
OK, fixed, will close this ticket.
