### ISSUE TITLE
Release v0.12a refuses to start or quit on MacOS Sierra

### ISSUE THREAD

**Issue by sunjam** [tomboy-notes/tomboy-ng#25]
v0.12a shows a pop window for setting up basic configuration the 1st time after installation.  I went for default settings and support for a note in multiple notebooks, then no window was visible for the application except “tomboy-ng” in the menubar.  Only option given for the app is to quit, which doesn’t work or give any sort of feedback.

**Comment by davidbannon** [comment]
Sorry about that Sunjam. And thanks for logging it.

Mind if I ask you to help debug a bit ?  Firstly, what platform are you running on (Windows, Mac, Linux), and even which version of the operating system ?

You mention seeing tomboy-ng on the menubar ?  I guess thats what I call the Trayicon, its a small icon that appears in different places depending on your OS.  In windows its hidden inside a group of similar icon in the bottom bar, cannot remember its actual name. On Linux its very dependent on the distro, Gnome3 systems put such things off to the left of the bottom bar, you need to hover the mouse to the lower left. Always seem visible top rightish on the Mac.

Clicking the trayicon should give you a dropdown menu of 16 items : "New Note", "Search", then 10 (empty in your case) recently used notes, "About", "Syncronise", Settings", "Quit close and go away".
Now, you say only option given is to Quit. Are you seeing the other menu items and they don't work or are they not present at all ?

Thanks for your help sunjam.

David

**Comment by sunjam** [comment]
Apologies for any confusion: platform is MacOS Sierra running release
v0.12a.  Trayicon is visible on MacOS, but I don’t see any application
specific options at all in the menu besides the ones always provided on
Mac.  Tried qutting the application, but it didn’t work.

**Comment by davidbannon** [comment]
Hmm, thats very strange indeed. I am focusing on you words "but I don’t see any application specific options at all in the menu besides the ones always provided on Mac". In this popup menu, there should be absolutely no options other than the tomboy-ng ones. So no "ones always provided by the Mac".  
Would it be possible for you to click that trayicon and send me a screen dump please ?  I am pretty sure we are not talking about the same thing. Or something has gone horribly wrong .....
I just grabbed a fress copy from github and have taken a couple of screenshots of how my system looks, one shows the menu and the other shows the bright green trayicon unclicked. How do you compare to those images sunjam ?

https://drive.google.com/file/d/1lLG7WXOmXhK7hVKxGMIJXf_AUM92pFjt/view?usp=drivesdk
https://drive.google.com/file/d/1m7Nd1vHChfz0chdMJ60DAMiQ46Z7jexB/view?usp=drivesdk

Another Mac user appears to have similar issues, strange business.

**Comment by davidbannon** [comment]
Speaking to Josep on the mailing list, it looks clear to me whats happening here. tomboy-ng, being a cross platform app, not a dedicated Mac app, does not quite do what Mac users expect. I am pretty sure the menu you are talking about is the one that appears top left with the word "tomboy-ng". I have not hooked into that menu at all, don't know if its even possible for me to do so.
I have been referring to the bright green note book and pencil icon to the top right, thats the one that appears similar (and driven by the same code) on all platforms tomboy-ng runs on.
I'll make a note on the wiki about this when I get a chance.

**Comment by davidbannon** [comment]
OK, release v0.13 is a lot more Mac like. However, we still don't respond to a Command Q keystroke so leaving this ticket open until thats fixed.

**Comment by sunjam** [comment]
@davidbannon could you please release 0.13 as a packaged dmg installer.

**Comment by davidbannon** [comment]
This confusion was caused by me forgetting to 'publish' or 'release' v0.13.
David
