### ISSUE TITLE
Line terminations are selectable

### ISSUE THREAD

**Issue by radi8** [tomboy-notes/tomboy-ng#250]
This may be very upstream of tomboy-ng but when selecting the text at the end of a line the carriage return/line feed gets selected with it as you swipe the last word. If you select the last word on the line carefully, you can avoid selecting the line terminator and it is possible to select the line terminator just on its own and copy and paste it anywhere in the note.

It is a pretty unusual experience and does not happen in any other editor that I have used including this issues editor and unfortunately I use a note daily to organize the order of a list plus adding and deleting items. I keep getting messed up with that terminator.

Tried the Qt version (which I prefer) but the same issue is there also. Hope that it is something that you can do but not holding my breath. Thanks for the **great** work that you are doing on this app.

Cheers, Graeme

**Comment by davidbannon** [comment]
Graeme, thats an interesting question.  Yes, what you say is correct, there is some artifact of the newline there and you can (or not) select it. And, as you say, its upstream. 
I guess I have got used to it and, to some extent, like it, I find its lack on every other editor I use noticeable. I have to agree, it should not really be there.  Will look into it but am not hopeful of a happy ending ....

Will get back to you.

Davo

**Comment by davidbannon** [comment]
Yes, as suspected, this is deep withing KMemo and unlikely to be improved upon given how it happens.

I am going to close this ticket but do please feel free to reopen or create a new one if you feel strongly about the problem.

Davo
