### ISSUE TITLE
Adjusting timestamps

### ISSUE THREAD

**Issue by semugu** [tomboy-notes/tomboy-ng#252]
Using Ctrl+D creates a timestamp in tomboy, f.exp. "2021-10-18 12:49:10". With the old tomboy there was a possibility to adjust the format of the timestamp via the [add-in](https://help.gnome.org/users/tomboy/unstable/addins-tools-timestamp.html.en), f.exp "2021, Tuesday, September 14, 8:37 am" . Does tomboy-ng also have this possibility? Where do I find it?
I am using version 0.33d with the amd64.deb-version on Ubuntu 18.04.

**Comment by davidbannon** [comment]
Hmm, like if we made the timestamp automatically bold or highlighted ?

Davo

**Comment by davidbannon** [comment]
OK, fixed in newly released v0.34, will close this ticket.
