### ISSUE TITLE
Bug: selecting text and pressing ctrl+D (insert datestamp) can't be undone

### ISSUE THREAD

**Issue by omn1vor** [tomboy-notes/tomboy-ng#254]
Hey, thanks for the app, first of all, I like it a lot.
As for the bug:
1. Select some text in a note.
2. Press ctrl+D, a datestamp will be inserted over the selected text.
3. You can't undo this action, and that's the problem (selected text is lost for you forever).

**Comment by davidbannon** [comment]
Yeah, it would be too !  Thats an oversight, I have not hooked the Ctrl-D into the undo mechanism.

I'll fix it !

Thanks for the report. Could be messy, you could have the while document selected !  Ahh....

Davo

**Comment by davidbannon** [comment]
hi omn1vor, I have just put some alpha packages on the tomboy-ng 0.34 release page that address this issue. They are relativly untested but I have been using much of the new code for some months with no apparent problems. Depending on how brave you feel, you might like to git it a go.

https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.34

Davo

**Comment by omn1vor** [comment]
Thanks man, I'll wait for main, but I will let the guy who had found this bug the hard way know right now :)

**Comment by davidbannon** [comment]
Fixed in 0.35
So, I'll close
Thanks for the report.
Davo
