### ISSUE TITLE
Tray dropdown menu opens downwards on upper monitor

### ISSUE THREAD

**Issue by donquixote** [tomboy-notes/tomboy-ng#258]
I am using tomboy-ng on KDE Plasma with a multi-monitor setup like this:

```
   +-----+-----+
   |  A  |  B  |
   +-----++----+
          | C  |
          +----+
```
I have a bottom panel on each monitor, with a tray area at the end of the panel on the primary screen.
The tomboy-ng icon does show up in that tray area.

When I make C the primary monitor, then the tomboy-ng menu opens upwards, which is good.

When I make A or B the primary monitor, the tomboy-ng menu opens downwards, so only the top 16 or so pixels show up.

```
 +-----------------+
 |                 |
 |                 |
 |                 |
 |                 |
 |                 |
 +-------------====+
                ↓↓↓  bad
                 
 +-----------------+
 |                 |
 |                 |
 |                 |
 |                 |
 |              ↑↑↑| good
 +-------------====+
```

Other items in the tray area don't have this problem.

**Comment by davidbannon** [comment]
Hmm, thats a hard one I am afraid.  In my code, I get no control over where or how the menu is shown. I simply define an icon and a menu and pass it to one of the libappindicators.  So, the decision you are unhappy about is a decision made in either the particular libappindicator you are using or in your desktop. As far as I know, neither you nor I can influence that decision.

I don't have the facilities to setup a screen system like your so I cannot do any experimenting here I am afraid. Maybe we can work through some ideas on your system ?

Now, be useful to know which libappindicator you are using, it may be benificial to use an alternative but I don't know if that possible.  One way to see which library tomboy-ng is using is to start it from the command line (having stopped an existing instance) with an env var set -

`LAZUSEAPPIND=INFO tomboy-ng [enter]`

Its likely you will be using either the "Traditional" one, originated in Plasma, managed for some years by Ubuntu, now being abandoned, or the libayana* one, new kid on the block, was subject to quite rapid dev for a while, hopefully may be interested in getting bug reports !

Davo

**Comment by donquixote** [comment]
> So, the decision you are unhappy about is a decision made in either the particular libappindicator you are using or in your desktop. As far as I know, neither you nor I can influence that decision.

Interesting. Other menus in this area don't have this problem..

> LAZUSEAPPIND=INFO tomboy-ng [enter]

I get this:

```
~ $ LAZUSEAPPIND=INFO tomboy-ng

(process:927141): Gdk-WARNING **: 00:52:31.542: locale not supported by C library

(process:927141): Gtk-WARNING **: 00:52:31.543: Locale not supported by C library.
        Using the fallback 'C' locale.
APPIND Debug : Will not use AppIndicator3
```
I think we can ignore the gtk-warning, it is unrelated.

**Comment by davidbannon** [comment]
Yes, the gtk warnings are just gtk's usual wordiness.

But you are not using AppIndicator3 at all, that means the desktop is providing all the service. I wonder if the API it uses provides some extra capability ?  If so, maybe (just maybe) I can tap into that. I will do some tests on a KDE desktop and see what i can find out. Unfortunatly, I don't have anything like your multiple monitors so any tests will need to be done by me sending you a test app.

Davo

**Comment by davidbannon** [comment]
OK, seems this issue has gone stale one way or another.
Thanks for your report.
Closing ....

**Comment by donquixote** [comment]
Actually, right now the menu does open in the correct direction.
I don't know if it is universally fixed, but it works for me now.
