### ISSUE TITLE
Auto-remove note title text styling after pasting a note title into a note body

### ISSUE THREAD

**Issue by mlncn** [tomboy-notes/tomboy-ng#26]
Steps to reproduce:

1. Create a new note.
2. Copy all or a portion (for instance the date) of the title of the current or other note into the body of the note.
3. The text styling stays as a large and blue font, underlined.  (The font can subsequently be made normal size through the Text menu options, but there's not even a way to remove the blue or the underlining)

Expected behavior (and behavior of the old... in my case, very old... Tomboy):

3. Text styling automatically changes to match its new context.  This would happen on the next press of spacebar or enter key in old Tomboy.

**Comment by mlncn** [comment]
Update: Closing and re-opening a note removes the inappropriate formatting so this is a super-minor issue.

**Comment by davidbannon** [comment]
Yeah, I had not thought of this I must admit. Should be easy to add to the other house keeping stuff.

**Comment by davidbannon** [comment]
Fixed in v0.24, thanks for report.
