### ISSUE TITLE
How does one migrate notes from Tomboy into tomboy-ng?

### ISSUE THREAD

**Issue by jtcmedia** [tomboy-notes/tomboy-ng#262]
I've looked through the issues and wiki and can't find any information on how I can migrate my notes from Tomboy into tomboy-ng. The Tomboy notes are stored as XML. I looked at [TomboyTools](https://github.com/davidbannon/TomboyTools) but it only imports markdown or plain text. Tomboy can only export HTML.

**Comment by jtcmedia** [comment]
Was simpler than I thought. In case anyone else wonders, you can simply copy your notes under %AppData%\Tomboy\notes to %AppData%\tomboy-ng/notes

**Comment by davidbannon** [comment]
Well solved JTC. 
I have wondered if I should have a button that does automatically the copy you just did  ? Maybe ....
In fact, you can just point tomboy-ng to your Tomboy dir if you wish. tomboy-ng does not care where your notes are as long as it can find them.

Davo

**Comment by jtcmedia** [comment]
I don't know if a button is necessary @davidbannon  but a comment about migration in the docs would help. I had falsely assumed tomboy-ng stored notes in a different format just because TomboyTools doesn't do XML.

**Comment by davidbannon** [comment]
OK, have added a sentence to the main wiki page.  

TomboyTools is a more specialized, case by case thing, its used by a small number of people who have specific workflow needs.

Thanks for your feedback !

Davo
