### ISSUE TITLE
'about' dialog has weird wrapping of info text, Xubuntu 20

### ISSUE THREAD

**Issue by Alexey-T** [tomboy-notes/tomboy-ng#266]
![Screenshot_2022-06-16_17-53-11](https://user-images.githubusercontent.com/4154978/174098201-ff6ab8f3-6635-4dbb-a5cf-082dced2115a.png)

**Comment by aguador** [comment]
Davo, I just looked at the .po file and the first three lines are separate strings, which is why it has the odd breaks. Any way to make that a single string? Roy

**Comment by davidbannon** [comment]
From memory, the Mac had trouble rendering a single string, but that might have been on Carbon rather than Coco. And, over time, the content has changed there explaining the different length of the strings.

Does it seem that important ?

Davo

**Comment by davidbannon** [comment]
I have reopened this issue because Alexey has raised a good point. 
Davo

**Comment by aguador** [comment]
The other option is a single string with line breaks (br between <>) inserted manually. While that has a similar effect to three separate strings, it is easier to adjust manually.

Note that when translating one simply moves those breaks around to produce a similar format in the target language message.

**Comment by davidbannon** [comment]
OK, just looking at this now. I wonder if its time that message was shortened ?  Drop the lecture about backups ?

**tomboy-ng, a note tool built using FPC and Lazarus.
https://github.com/tomboy-notes/tomboy-ng
ver XXX
build date XXX
target XXX**

That way there is no wrapping to worry about and two less string to translate ?

Davo

**Comment by aguador** [comment]
All for ending lectures. A shame to loose the note about the relationship with Tboy, but at this point seems unnecessary. Tomboy is dead. Long live tomboy-ng! (Sorry, couldn't resist that.)

**Comment by davidbannon** [comment]
Yeah, pretty good. 

According to South Park, it was 22 years before we could make jokes about AIDS, you have set a much shorter time here. Pretty good !

Davo
