### ISSUE TITLE
'welcome' form shows 'found 0 notes' even if I made few notes

### ISSUE THREAD

**Issue by Alexey-T** [tomboy-notes/tomboy-ng#267]
even if I made 1-2 notes, 'welcome' form don't see it! can you run a timer to update it?

**Comment by davidbannon** [comment]
The welcome form is only intended to be seen at application open. In practice, most users close it or set it to remain closed permanently.  Its very existence is a historical accident, the Original Tomboy did not have it, but on Linux using Gnome desktop it was a necessary workaround to the endless problems I had with the TrayIcon on that platform.  As that Gnome issue is now solved (mostly) it could, perhaps even be removed now.
But that would involve some work that I don't think would excite too many people. So, its a case of why worry about it ?
Davo

**Comment by davidbannon** [comment]
I have reopened this issue because Alexey has raised a good point. Seems we have three options -
1. Add a bit of code that updates the number (of notes) displayed as it changes, new, delete ...
2. Consider hiding this form, maybe only showing it if an error is detected. Still have same updating issue ...
3. Do nothing.

**Comment by aguador** [comment]
1.5 more options:

  3a. Simply change the text to indicate "x notes at startup" (Problem: people who keep their machines going for days/weeks.)
  4.  Add a timer to have the window automatically self-destruct (OK, OK, close).

For me the window is like a startup splash, so having it disappear at some point seems logical. The chief downside would be for those who start their machine, go for coffee and return a hour later having missed the information. In that case, there are two non-exclusive possibilities: a) override auto-destruct if an error is detected (still have the update issue), b) offer a "status check" option on the menu to reopen the window - assuming it updates when reopened.

**Comment by davidbannon** [comment]
OK, notes as mentioned in the splash screen are now updated.
So, I'll close
Thanks for the report.
Davo
