### ISSUE TITLE
this form shows ugly border around bottom buttons, not nice

### ISSUE THREAD

**Issue by Alexey-T** [tomboy-notes/tomboy-ng#268]
Xubuntu 20

![Screenshot_2022-06-16_18-06-11](https://user-images.githubusercontent.com/4154978/174101028-33241970-f367-42bd-9e39-64d503fdf555.png)

**Comment by aguador** [comment]
Button appearance will change with the application theme. This looks like the Greybird theme. Have you tried others?

**Comment by Alexey-T** [comment]
i talk about Lazarus TPanel border. which is around all bottom buttons.

**Comment by davidbannon** [comment]
Again, I think 'ugly' is in the eye of the beholder, I believe its looks OK. The difference is just a setting of TPanel, Alexey, you can set TPanel to a number of different looks, maybe you need to experiment with some of them ?
Again, its a way to draw the user's eye.

Davo
