### ISSUE TITLE
this form shows too tall buttons, 2x taller than usual buttons in UI

### ISSUE THREAD

**Issue by Alexey-T** [tomboy-notes/tomboy-ng#269]
Xubuntu 20

Also - ugly borders around top info-text.

![Screenshot_2022-06-16_18-08-27](https://user-images.githubusercontent.com/4154978/174101493-fbfbbfb3-02f3-4d77-b523-ccca02b0e5db.png)

**Comment by aguador** [comment]
Those buttons do seem overly large, but I do not understand the comment about the border or whether it is ng or theme dependent. Attaching screenshots of ng window in first, Enlightenment, then XFCE, both with a Vertex dark application theme.

![ng-E_20220616](https://user-images.githubusercontent.com/8114758/174126545-5e41ee51-305d-45ca-9c26-bc42f09e3445.jpg)
![ng-XFCE_20220616](https://user-images.githubusercontent.com/8114758/174126551-67674733-f2aa-4bc9-8d86-cd8db09a6d3a.png)

**Comment by davidbannon** [comment]
I use a raised panel when I want to user to see it, I am an engineer, not an artist so functionality is more important to me than "first look appearance"
