### ISSUE TITLE
Ghost spaces shown at the end of every line on re-opened notes

### ISSUE THREAD

**Issue by mlncn** [tomboy-notes/tomboy-ng#27]
Steps to reproduce:

1. Create a new note with multiple lines
2. Close and re-open the note
3. Place your cursor at the end of each line with text, or even blank lines that have a following blank line.  It will appear to have one space more than you actually typed ("My line. " instead of "My line.", but deleting this space will cause the line break to disappear.

Expected behavior:

- There never appears to be spaces where the note-enterer never pressed the spacebar.

 v0.12 of tomboy-ng.  Build date 2018/01/31  TargetCPU x86_64  OS Linux

**Comment by davidbannon** [comment]
Yes, know what you mean. Its an artifact of KMemo that I don't like. I don't think its something I can do anything about. But will investigate and if I can be sure I understand it, report it upsteam.

Davo

**Comment by davidbannon** [comment]
Actually, a much simpler explanation. Sloppy programming on my part .....
Fixed
