### ISSUE TITLE
Escape no longer closes current note. 

### ISSUE THREAD

**Issue by salamander2** [tomboy-notes/tomboy-ng#271]
I just migrated from the old Tomboy to the new. Is there some way to get this functionality back?  ESC is such a simple and handy thing. It should be under settings (to enable it if you wish).

Thanks. You have a lot to do ;)

**Comment by davidbannon** [comment]
Sorry for the delay in answering, been travelling in quite remote parts.

Hi salamander2, this was a (possibly selfish) decision made way back in the early days of tomboy-ng. The reason ESC does not close an edit window is I am a big vi/vim user.  And using vi, you press ESC all the the time!
However, I note you suggest it as an option, and maybe thats not such a bad idea.
Right now, Ctrl-F4 is what you are looking for, its widely used in other applications that that pop up non-modal windows.
I'll treat this request as an Enhancement Request (but guess you think of it as a bug ;-)   )
Davo

**Comment by salamander2** [comment]
Hey, thanks for replying. 
Don't worry about getting this working, I can get used to the new method. 
I also use vim all the time, but when I'm not in a CLI screen I don't think of <ESC> as having the same function as in vim.
M.

    On Monday, August 15, 2022, 3:22:06 AM EDT, davidbannon ***@***.***> wrote:  
 
 


Sorry for the delay in answering, been travelling in quite remote parts.

Hi salamander2, this was a (possibly selfish) decision made way back in the early days of tomboy-ng. The reason ESC does not close an edit window is I am a big vi/vim user. And using vi, you press ESC all the the time!
However, I note you suggest it as an option, and maybe thats not such a bad idea.
Right now, Ctrl-F4 is what you are looking for, its widely used in other applications that that pop up non-modal windows.
I'll treat this request as an Enhancement Request (but guess you think of it as a bug ;-) )
Davo

**Comment by davidbannon** [comment]
OK, all done in version 0.35
So, I'll close
Thanks for the report.
Davo
