### ISSUE TITLE
[Feature Request] Checklist

### ISSUE THREAD

**Issue by renatordutra** [tomboy-notes/tomboy-ng#282]
It's a great program so far, better ideas than the usual Sticky Notes around. But I still fell the need on some features like checklist support. Is there any hope to see that on Tomboy?

**Comment by davidbannon** [comment]
Always hope renatordutra.
Could you give me a clearer idea of what you want ?   Some sort of checklist structure in a note or applying to lists of notes ?
Davo

**Comment by davidbannon** [comment]
Any further thoughts renatordutra ?

Do you want a checklist showing a list of the notes or a note with a checklist section in it ?

Davo

**Comment by davidbannon** [comment]
Hmm, no response from user. If there is still some interest, please reopen.
