### ISSUE TITLE
Feature request: customize color for hyperlinks

### ISSUE THREAD

**Issue by aguador** [tomboy-notes/tomboy-ng#287]
Currently the colour of titles, text, background and highlights can be changed, but not that of hyperlinks. In 0.35 Gtk the hyperlinks appear in dark blue, which provides little contrast for those of us who use dark themes. An option to set it independently or to have a lighter colour by default in dark theme would help a great deal.

Consider it a holiday wish, Davo.

Roy

**Comment by davidbannon** [comment]
Hmm, special treatment for dark theme users ?
Yeah, Roy, I think its possible, I will have a look.
Davo

**Comment by davidbannon** [comment]
OK, I thought dark blue on a black background was supposed to be popular amongst Dark Theme users. I sure see it popping up on terminals much to my annoyance. 
Anyway, easy fixed, I have added Teal (same as Title) as a default link colour in a dark theme and the ability to set it, manually to any colour you like, see -
![LinkColour](https://user-images.githubusercontent.com/6291248/210134604-3675f426-5f57-4539-afe6-a4e587a290bc.png)

(hmm, think I forgot to save that particular colour scheme, sad, I'll never be able to create it again !)

Will put out a 0.35a soon.

Davo

**Comment by davidbannon** [comment]
Resolved in the newly released 0.35a
Thanks
