### ISSUE TITLE
GitHub Sync not working

### ISSUE THREAD

**Issue by eamwml** [tomboy-notes/tomboy-ng#288]
Hi, I’m trying to set up the GitHub Sync, following the [instructions](https://github.com/tomboy-notes/tomboy-ng/wiki/Github-Sync) precisely, and every time I reach the point where I click Setup, I get an error message telling me

`Unable to proceed because Github Downloader - InOutError
Could not initialize OpenSSL library`

Machine being used runs on Windows 8.1 Professional. I tried googling the error message (whole and in parts), but couldn‘t find any solution. Also, for some reason my version doesn’t show the _ChangeSyncRepo_ button mentioned in the explanation, only _Setup_.

Any pointers to what I can try much appreciated.

Thank you!

**Comment by davidbannon** [comment]
Hmm, I have only tested github sync with Windows 10/11, ssl libraries can be very picky.  You 'might' be able to solve this by putting an appropriate open SSL dll file in the same directory as tomboy-ng, that will override the system installed one without affecting any other application. 

I will look into this and see what I can find, will get back as soon I can ...

The Change Sync Repo button only shows up after you have a working sync, sounds like you have not got that far yet !

Davo

**Comment by davidbannon** [comment]
eamwml, yes, I can confirm that the ssl DLLs at https://indy.fulgan.com/SSL/ work fine. Others may too but I know most Windows using Pascal people use the ones from Indy. 

Seems I have previously installed them on both my Windows test boxes system wide so they just worked there. So, very sorry about the problems I have cause you (and anyone else who does not already have SSL installed on a Windows machine).

I suggest the easiest and safest way to use these DLLs is to download the latest zip from the above link, extract just the two DLL files (libeay32.dll and ssleay.dll) and then put them in the same directory as the tomboy-ng binary. In my case that is c:\Program Files\tomboy-ng\ 

Restart tomboy-ng and all will work as expected.

I do **not** suggest you put the DLLs in a general purpose area in case they clash with some other app, probably not but just not worth the risk IMHO. But its quite likely you know far more about Windows that I do ! If you have your own favorite openSSL DLLs, that you would prefer to use, just put them in with the tomboy-ng binary, will probably work fine.

Please let me know how you go.

David

Ref: https://wiki.openssl.org/index.php/Binaries

**Comment by eamwml** [comment]
Hi David,

Thanks a lot, everything works perfectly now! I'm usually on Ubuntu, but I don't always get a choice at work ...
