### ISSUE TITLE
Tomboy-ng icon not displaying in Taskbar Windows 10

### ISSUE THREAD

**Issue by jgsylvester** [tomboy-notes/tomboy-ng#293]
Tomboy-ng icon not displaying in Taskbar (right side) in Windows 10. I am using the latest version .35a. I have tried several suggestions found on internet to fix icons not displaying on Taskbar to no avail. Any suggestions?

**Comment by davidbannon** [comment]
By default, Windows hides the systray icons under a angle bracket that points up (for lack of a better name). It's on the task bar, towards rhs. If it's there, you can set it to display always, if not there, please let me know....
Davo

**Comment by davidbannon** [comment]
I guess the user has found the icon.
