### ISSUE TITLE
Sync error : "(line 1 pos 1) Root element is missing"

### ISSUE THREAD

**Issue by nguxx** [tomboy-notes/tomboy-ng#294]
Hi,

I have this error went I try to create a synchronization : "(line 1 pos 1) Root element is missing"
version 0.36eb x86_64 OS Win64

**Comment by davidbannon** [comment]
nguxx, this sounds like a broken note. When you restart tomboy-ng does the splash screen pop up with a warning about errors in your notes ? 

It could be that the broken note in in your sync repo and tomboy-ng is refusing to sync it so you may not see that error message.

Which sync are you using, file sync or sync to github ?  

You may need to try and capture tomboy-ng's debug stream, it usually has something to say about most errors. To do that on Windows is a touch hard, you need to follow the instructions on https://github.com/tomboy-notes/tomboy-ng/wiki/Bugs-and-Known-Issues#debugging

Try it first without the "--debug-index", attempt to start up a sync. If there is nothing much interesting in the log file, try it with --debug-sync

Before posting the logfile here, make sure you look through it first, it will probably have note titles in it, you may not want them public.

Davo

**Comment by davidbannon** [comment]
Hi nguxx, any news on this problem ?

Davo

**Comment by nguxx** [comment]
Sorry, Hollydays in France. AFK.Back the 30th.I'll let you known then.ThanksLe 21 avr. 2023 01:58, Davo ***@***.***> a écrit :
Hi nguxx, any news on this problem ?
Davo

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
Le 21 avr. 2023 01:58, Davo ***@***.***> a écrit :
Hi nguxx, any news on this problem ?
Davo

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
Le 21 avr. 2023 01:58, Davo ***@***.***> a écrit :
Hi nguxx, any news on this problem ?
Davo

**Comment by nguxx** [comment]
Hi David,
First, my TB is in French, I’ve tried "note in English" but it stays in French so I will try to translate the commands.

Sync is local.

When the splash screen opens it says : Cannot index notes Please go to Settings > Recup > Recup notes
I have 11 notes broken, I tried to delete them. After quitting and restarting the notes are gone and I do not have the splash screen at the opening anymore (my option’s choice) 

So it’s fixed, thanks for your help.

**Comment by davidbannon** [comment]
But you lost 11 notes ???

Thats very bad news indeed !  Do you have any idea what might have caused such a disaster ?  Power failure ? Bad disk ?  It should not happen unless something really serious has happened. So, I worry, it might happen again.....

(Note to self : I should zip up deleted notes so they can later be examined if user wants, just deleting them leaves the trail cold.)

Davo

**Comment by nguxx** [comment]
> But you lost 11 notes ???

Fortunately no, I had a backup of my folder and I could get them back.
I think the problem was in the synchro of my Nextcloud. 
My Tomboy-ng folder is sync with the Nextcloud client to my Nextcloud server. And I have many devices with Linux and Windows OS with this feature, at the end I often experience conflicts.
That 's what is very precious for me in TB-ng, I have the same folder fed with different OS (double boot plus VM) on my main machine plus external machines sync with the cloud. Everywhere I have my notes (except on android). Very handy !

**Comment by davidbannon** [comment]
Good, backups help us sleep at night !

Hmm, I was looking at a direct NextCloud sync, to their notes application. But their model for storing last change date/times was quite buggy. I believe it has been revised since then, maybe I should look again ?

And Android ? Have you tried the Github sync ?  I use it for a subset of my notes and find it invaluable. I always have my phone with me and it was quite easy to decide which notes needed to be made available that way. The github editor is a bit clunky on a phone but even just being able to read the notes is useful.

Davo

**Comment by davidbannon** [comment]
Sounds like user sorted this problem out.
