### ISSUE TITLE
Export to PDF produces blank file

### ISSUE THREAD

**Issue by docaltmed** [tomboy-notes/tomboy-ng#296]
expected behavior: note text exported to pdf file

actual behavior: pdf file is blank.

**Comment by davidbannon** [comment]
Hi [docaltmed](https://github.com/docaltmed), sorry about that. The PDF exporter is very sensitive to what fonts you have available. You have not mentioned the operating system or the version of tomboy-ng you are using, please provide that information and I will see if I can replicate your problem or suggest a test you can do to isolate it.

Davo

**Comment by davidbannon** [comment]
docaltmed, any further thoughts on this issue ?

Davo

**Comment by davidbannon** [comment]
This matter addressed in the new, 0.40 release of tomboy-ng.
Thank you for you input.
David
