### ISSUE TITLE
does it work OK on CrunchBang Linux?

### ISSUE THREAD

**Issue by Alexey-T** [tomboy-notes/tomboy-ng#299]
I cannot test it yet (distro is not installed), but maybe you want to test this distro with TomBoy.
https://forum.lazarus.freepascal.org/index.php/topic,64405.0.html

what needs to be tested in TomBoy: input in SynEdit fields. does app use SynEdit?

**Comment by davidbannon** [comment]
Hi Alexey, no I have not tested against CrashBang Linux, in fact, never heard of it. Because of the infrastructure each test platform needs, particularly diskspace, I only test against the mainstream ones or ones people advise me they are having a problem with.
Davo

**Comment by davidbannon** [comment]
Alexey, I did not answer your second question, No, tomboy-ng does not use SysEdit. SysnEdit cannot do the larger or smaller fonts we needed. Richedit was not sufficiently cross platform for my needs so I choose KMemo, harder work initially but proved to be a good decision.
Davo
