### ISSUE TITLE
don't run multpile instances

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#3]
If not requested otherwise by the user (maybe with an option) tomboy-ng should not start multiple instances but exit silently or with a note "already running".

**Comment by davidbannon** [comment]
http://wiki.freepascal.org/UniqueInstance might be a solution but I suspect it provides lots of additional services we don't want and is another Package that needs to be added to development machines. Not tested on Mac.  Would like something simpler .....

**Comment by traumschule** [comment]
An easy alternative is to drop a .pid file in the configuration directory and check for that at startup.

**Comment by davidbannon** [comment]
Yes, I'd started to plan something along those lines. But don't like it at all. You have issues with a unplanned powerdown and the file is left there, have to ask user. I have done things like that in the past but never been proud of it. And its one more disk i/o at powerdown, thats frowned on.  
Was thinking we could ignore an existing pid file if it listed an invalid pid, that way you only need to ask ps if the file is there. But don't know how to do that under windows. Been searching for a library function to read processes but ....

**Comment by traumschule** [comment]
> You have issues with a unplanned powerdown and the file is left there

The file contains a PID number and you drop it if no process with that PID exists.

**Comment by traumschule** [comment]
another [trick from the forum](http://forum.lazarus.freepascal.org/index.php/topic,12107.msg77321.html#msg77321):
> I'm using FileOpen with fmShareExclusive for both locking and checking.
> FileOpen will return error -1, if file is already opened with fmShareExclusive.
> 
> Works fine on linux.
> 
> If you use same method on Windows, FileOpen will succeed regardless, i don't know is this a bug or intended.
> But then you can try to read  with FileRead, where it will fail if locked with fmShareExclusive.

**Comment by davidbannon** [comment]
I have been looking at this -
https://github.com/graemeg/freepascal/blob/master/packages/winunits-jedi/src/jwatlhelp32.pas
but seems to be abandonware (at least as a Lazarus port) and no 64bit version. Have not looked closely enough to see what the 32/64 issues are but believe MS changed api quite a lot so it probably hits a obsolete API. We could fork ....

I thing the LazarusIDE approach might just be a bit more than we'd want on what is intended to be a lightweight app. And there does not see to be a Lazarus Unit to talk to TooHelp.dll  (plus, I'd need to know that the dll is installed by default, don't want to introduce more dependancies).
I am afraid its looking like a dialog box that says "Hi there, looks like you are either running a second instance or running after a crash...."
I hate that but it will be easy and reliable cross platform. And maybe later on, we can do better....

**Comment by traumschule** [comment]
Oh, we should copy some of those assembler statements, just to let the code look better. Unfortunately this whole file tells me nothing, except JEDI was a cool gang long time ago.
What about [this example](https://forum.lazarus.freepascal.org/index.php/topic,39127.msg267457.html#msg267457) using TEvent.

**Comment by davidbannon** [comment]
to quote -

> the only problem is if the application crashes without a nice reset events then you cannot launch application again, unless you restart your system (because events are still set)

I've just spent some time implementing a pid file approach reading necessary data from /proc. Thought would at least get me past the Linux and Mac. But it turns out mac does not have a /proc, what sort of ($%3..&##) Unix is it anyway ?  So, re do using ps I guess. Then see if the 32bit code in jwatlhelp32 runs next to the 64bit in windows. At present I am destinguishing between definitive yes/no and Windows maybe yes - if all else fails, I'll have to ask the user when I cannot be sure. Hate that.

**Comment by davidbannon** [comment]
OK, fixed at last. Have added a new unit based extensivly on something on Lazarus website. It checks to see if there is a process with the same executable name. Does not leave semaphores and does not use PIDs. But does work reliably cross platform. Note, it calls a built in RTL/LCL library identified as being 32bit but seems fine in a 64bit application.

**Comment by traumschule** [comment]
Thanks! (The dialogbox could be removed later, for example claws-mail exits more quietly with not even a message on the prompt)
