### ISSUE TITLE
 Yellow highlight in pasted text.

### ISSUE THREAD

**Issue by nightwindzero** [tomboy-notes/tomboy-ng#300]
When I copy and paste from Tomboy-ng to Word O365, the text comes out with a  Yellow highlight 

This does NOT happen when I use OpenOffice Writer though.

This seems to happen with all my notes but the one I was specifically using when I went through this doesn't have any reference to yellow in the file that I can see.

Version 0.36b

Thanks for all your hard work. 
I love this app.

**Comment by davidbannon** [comment]
Hmm, do you mean that text that is highlighted yellow in the -ng note keeps it highlight in Word but not OpenOffice ?

Or do you mean all text copied from an -ng note is highlighted yellow when you paste into OpenOffice ?

In my case, on Linux, copying from a note to OpenOffice seems to always drop all markup. The way copy and paste works is that an application being copied from puts its content into the clipboard in plain text and possibly one or more markups. The app getting the paste chooses which version to use. In tomboy-ng's case, it copies the (default) plain text and a rich text version. 

I guess its possible add another format if we can workout what OO likes to get.

Davo

**Comment by davidbannon** [comment]
It appears LibreOffice will accept html (via "paste special") - migt experiment with pushing some html code into the clipboard ?

**Comment by nightwindzero** [comment]
I apologize for not being totally clear.
I primarily use tomboy-ng as text only. Very little formatting ever.

When I copy from a "vanilla note" into Word or Outlook, it comes out with
yellow highlighting.
I'll do a video later today for clarity.

Expected results:When I copy from a note in tomboy-ng with no formatting
into word, I expect no formatting in the text.
Observed:  When I copy from a note in tomboy-ng with no formatting into
word, I get text that is yellow highlighted.

**Comment by davidbannon** [comment]
No need for a video, I understand exactly what you mean. While I cannot replicate it here, I understand how annoying it really is. I do not understand why apps like OO or LO don't have a setting "always paste plain text". Personally, I hate the way it brings in formatting from elsewhere when its almost always the case that you want to apply the OO documents formatting. <grizzle mode off>
You can force a plain text paste, from memory (I need to look it up every time I use it) its ctrl-alt-V but you should check that. That will ensure OO is using the plain text option from the clipboard (tomboy-ng has put both plain text and rich text in there).

I 'might' be able to do a plain text copy from tomboy-ng, not sure, but worth trying. It would appear as an option. But honestly, a decision that 'should' be made in the receiving app. 

Davo

**Comment by nightwindzero** [comment]
Hi Davo,
I found my problem, my default background in Tomboy-NG was yellow and it
must be picking that up when I copy/paste it.
I will probably update my default background and call it a day.

Possible feature requests:
"Text Only mode notes" - Where the title is highlighted, but everything
else doesn't have markup.
Rationale - Ever since I started using Tomboy-OG - I have never used
markup. I understand there's a back and forth over, "More features vs
maintain backward compatibility"
But for my use case I just made it work.

Make it so the default background color isn't copy and pastable.
This must have just cropped up a few months ago, It certainly didn't
always do this. Would you like me to find out when the change occurred or
do you think you know?

Thankyou for this great program!

**Comment by davidbannon** [comment]
Yeah, that makes sense. What ever colour you -ng background is set to, right now you will get that colour, if you set it to white, its recorded as having a white background in the new app. What you want is no markup at all so it gets what ever the new apps background is. As I said, I would love to be able to paste into another app with no markup by default, but thats a matter for the other app, tomboy-ng does place a plain text copy in the clipboard, its just that most apps are setup to use the most 'complete' item in the clipboard. 
I will look into an option for tomboy-ng to place only the plain text copy there. Sometimes thats not what we want, eg, copying between tomboy-ng notes. So, will have to be an easy set option.
Davo

**Comment by davidbannon** [comment]
OK, embarrassing easy to fix, I have provided an additional Right Click Menu, "Copy Plain" that does appear to do just that. Libre Office does not use the RTF Text on my system so I cannot positively test it.
[nightwindzero](https://github.com/nightwindzero) - let me about your system and I will cut you a beta test version. Just to be sure.

David

**Comment by nightwindzero** [comment]
I'm running Windows 10 on the system I use Tomboy NG on

**Comment by davidbannon** [comment]
OK, look for the Windows Installer, the one ending with .exe, and with 0.36e in the file name, here -
https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.36c
sorry, there are a lot of files in that directory, you need the one called tomboy-ng-setup-0.36e.exe, note the 'e' in the version number.

Davo

**Comment by davidbannon** [comment]
OK, this issue resolved in https://github.com/tomboy-notes/tomboy-ng/wiki/Download_Release

So closing this issue, thanks for your report.

Davo
