### ISSUE TITLE
Import from original Tomboy

### ISSUE THREAD

**Issue by mach-o** [tomboy-notes/tomboy-ng#302]
Is it possible to import tomboy notes into tomboy-ng?

I didn't immediately see anything in the wiki or settings.

Even importing somewhat corrupted versions would probably be useful to me, tbh.

**Comment by davidbannon** [comment]
No importing is necessary mach, tomboy-ng will read and write to your existing Tomboy notes.
It will make a reasonable effort to recover old, corrupted notes too so don't be surprised if you see ones you have not seen for some time !

I have just (like, 2 minutes ago) pushed up a beta release of tomboy-ng 0.37, its called 0.36h and its complete except for translation files. It has a somewhat more sensible setting approach to where your notes are, you can, if you like set it to look for them in the directory old Tomboy used to use. You might find that more usable than existing versions.

https://github.com/tomboy-notes/tomboy-ng/releases

Davo

**Comment by davidbannon** [comment]
Question answered.
New release https://github.com/tomboy-notes/tomboy-ng/wiki/Download_Release

So closing this issue, thanks for your report.

Davo
