### ISSUE TITLE
Line feed (shift-enter) does not work.

### ISSUE THREAD

**Issue by salamander2** [tomboy-notes/tomboy-ng#305]
This used to work in the original Tomboy. 

<ENTER> normally makes a new paragraph in word processors. e.g <P> Here it shows up as a new line.
<SHIFT><ENTER> normally makes a new line eg <BR>. 

BUT it fails totally in bulleted lists.  

Sometimes in a list, I want to go to a NEW LINE and stay inside the same bullet item.  If I press ENTER it makes a new bullet.

But <SHIFT ENTER> makes a total mess of things. It's kind of crazy sometimes, inserting the same text in 3 consecutive rows.

**Comment by davidbannon** [comment]
That is a much, much more serious problem I am afraid. The whole Bullet code is a very ugly hack on top of a KMemo.  Unfortunately, KMemo does not do bullets the way most users expect it to. So, I intercept keystrokes, and manage the bullets manually. There is, simply no way we can handle multi paragraph bullet items I am afraid.

Given that it messes up so badly (I was unaware of that), I wonder if I should disable Ctrl-Shift, at least when within a bullet ?  Doing nothing would be better that allowing the Ctrl-Shift to go through to the KMemo.

Sorry about that but is is a real "no fix" problem.
David

**Comment by salamander2** [comment]
It's not actually a multi-paragraph bullet (check out the original Tomboy). It seems to do the equivalent of adding <BR> at the end of the line.

Yes, disabling SHIFT-ENTER in bullets would be better. Then you simply can't mess it up.  Disabling also means that you have to deliberately press ENTER to make a new bullet.

Weird, I wonder why it doesn't work, but I really don't know the code at all, and am very grateful for all your work. :heart:

**Comment by salamander2** [comment]
Hey! My code in the top comment did not show &lt;SHIFT&gt;&lt;ENTER&gt;  anywhere.  Github must have interpreted the angle brackets as HTML tags and removed them.  I've now written &gt ; etc.

 I'm glad that you figured it out anyway.

@davidbannon

**Comment by davidbannon** [comment]
OK, shift-Enter does make sense, I can replicate very strange things when I try that here. So, drop it on floor anytime.  Thanks, useful fix.
Will be fixed in next release and that will be soon.
Davo

**Comment by davidbannon** [comment]
OK, this issue fixed in https://github.com/tomboy-notes/tomboy-ng/wiki/Download_Release

So closing this issue, thanks for your report.

Davo
