### ISSUE TITLE
XML markup (related to plugins in old Tomboy) is removed when the note is saved in Tomboy NG

### ISSUE THREAD

**Issue by mlncn** [tomboy-notes/tomboy-ng#31]
Before opening my infamous Tomboy note collection in Tomboy NG, i put all the notes under Git version control.

Here's the differences in a note that was opened and saved without making any changes:

```
-﻿<?xml version="1.0" encoding="utf-8"?>
+<?xml version="1.0" encoding="utf-8"?>
```
(No, there's no difference i can see there either.  Maybe some whitespace is trimmed?  I'm not worried about this.)

```
-<link:url>https://drushcommands.com/drush-8x/core/entity-updates/</link:url>
+https://drushcommands.com/drush-8x/core/entity-updates/
```

Apparently automatic linking of web sites are provided by a plugin which has not been ported? 

```
-c: <datetime>2018 January 24, Wednesday, 8:10 PM</datetime>
+c: 2018 January 24, Wednesday, 8:10 PM
```

This must be another plugin i rely on, pressing _ctrl+d_ to insert a date.  Hadn't even realized it put it inside tags.

Takeaway:  It doesn't seem to be a good thing that Tomboy-NG deletes any XML markup it doesn't understand from plugins it doesn't have.

**Comment by davidbannon** [comment]
This is a problem Benjamin. You see, tomboy-ng is not a 'port' its a complete rewrite. And the note, while active, is in a Object Pascal 'component' called kMemo. So, I read the xml, convert it to KMemo and then when we save, convert back to XML.  While in KMemo, there is no xml. So, any xml I don't know about will not make it through the process. 
**Links** - I do intend to highlight http links at some stage. I think it makes more sense to do so 'on the fly' rather than embed tags because I need to check them anyway, if you edit a bit of text and it becomes a link, I need to mark it and if it stops being a link, I need to unmark it.
Dates - I don't see any reason to tag dates, do you ?  It might make searching easier ?  Anyway, dea easy to implement a Ctrl-D to make insert a plain text date. Would that help ?

But as a general answer, not much I can do about automatically handling xml that is outside of what I support, apart from directly supporting it of course.

**Comment by mlncn** [comment]
I think it's worth directly supporting, as far as preserving, all XML that could be produced by Tomboy or its standard plugins— i think these plugins, they're called "Add-ins" actually in my interface, must be in its core repository, though all i know for sure is that they were included with the Tomboy Version 1.14.1-3 as installed from the Debian repositories.

Here are the ones i could imagine generating XML— i only use the first two but enabled the others to see what they produce:

- Backlinks (none, though maybe it makes *use* of the link:internal below)
- Insert Timestamp
- Fixed Width (monospace, below)
- Underline (underline, below)

Everything else below must come from Tomboy core.

Here's the XML i regularly see:

- `<link:internal></link:internal>`
- `<link:url></link:url>`
- `<datetime></datetime>`
- `<underline></underline>`
- `<monospace></monospace>`
- `<bold></bold>`
- `<italic></italic>`
- `<list><list-item dir="ltr"></list-item></list>`
- `<size:small></size:small>`
- `<size:large></size:large>`
- `<size:huge></size:huge>`

Note that normal-sized text does not get marked up.  There may be a better way to get a comprehensive list of in-note XML produced by Tomboy, but this is my best effort.

**Comment by davidbannon** [comment]
Just some comments on your list of tags -

- `<link:internal></link:internal>` - I don't plan to record internal links in the xml, there is no point as such things are constantly being rewritten. Its fully functional already.
- `<link:url></link:url>` - As above but its not functional. I personally hate the way Tomboy guesses often invalid links so am not terribly motivated to add this 'feature'. Someone else my be better motivated.
- `<datetime></datetime>` - I don't see any point in recording in the xml that something is a date time reference. If anyone else can think of why its a good thing, I might implement it. I can easily add a Ctrl-D to add a date time literal at cursor position.
-  `<underline></underline>` Tomboy does not seem to offer an underline feature. It is, to some extent, used up by links.
- `<monospace></monospace>` - Yep, monospace is definitely on my todo list but its an issue of determining exactly which font to use in a cross platform manner.
- `<bold></bold>` - we do that already.
- `<italic></italic>` - we do that already
- `<list><list-item dir="ltr"></list-item></list>` - we do that already
- `<size:small></size:small>` - we do that already
- `<size:large></size:large>` - we do that already
- `<size:huge></size:huge>` - we do that already

**Comment by alexanderadam** [comment]
Just be sure: will tomboy-ng also remove tags if I don't change a note (so not typing in it)?

**Comment by davidbannon** [comment]
Alex, sorry I have overlooked your question.
No, tomboy-ng will not resave an unchanged note.
I think I'll close this ticket, most if not all the issues it raised have either been implemented or do not seem appropriate to implement. 
It is still the case that tomboy-ng will not preserve the xml tags beyond the standard set. It does preserve the content between removed tags. 
If anyone wants particular XML features added, please post such a request, should be easy to do as long as we can agree its a good idea to extend the 'standard'.
