### ISSUE TITLE
Can't delete notes from search dialog

### ISSUE THREAD

**Issue by mecworks** [tomboy-notes/tomboy-ng#313]
I have over 350 notes and need to do some house cleaning.  In the original Tomboy, I could delete any note (or many notes) from the search dialog.  With Tomboy-ng, I can only select a note to view it.  I cannot select more than one note and I cannot delete any notes.  I have to open the notes individually and delete them.  This is the biggest PITA I have experienced in a LOOOOOONG time.

Please make it so that notes (one or more) can be selected in the search dialog and they can be deleted.

For now, I am going back to the original Tomboy.

**Comment by uwemock** [comment]
+1 from me.
When you delete a note you have selected from the search dialog, the list jumps to the top. This should not be the case. The list should not move (significantly) only because a note is gone.

**Comment by davidbannon** [comment]
Yes, I firmly agree. I look for that capability  myself sometimes !  Should be there in the next release, a beta for  the brave not too far away.

Davo

**Comment by davidbannon** [comment]
OK, I have just released a beta that addresses this issue. Reasonably well tested and probably quite safe to use.
https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.40a

Thanks for your report and helping to make tomboy-ng a better product.

Davo

**Comment by uwemock** [comment]
When I delete a note that is currently open from the search dialog, the note disappears from the list in the search dialog but remains open.

**Comment by davidbannon** [comment]
Wow, thats a good one uwemock !  I did not even think of that possibility.

How you you react ?  Should we just close the note first and then continue deleting OR, because the user has that note open, maybe its a mistake, decline to delete it ?  Or refer the user to the open note where they can delete it directly ?

Davo

**Comment by uwemock** [comment]
When the user requests the note to be deleted, ist should be deleted (and the open window should close).

**Comment by davidbannon** [comment]
Hi, version 0.41 of tomboy-ng is now available. I believe it solves the issue you reported here.
Thanks for your input.
Davo
