### ISSUE TITLE
Search results: title match first

### ISSUE THREAD

**Issue by monperrus** [tomboy-notes/tomboy-ng#314]
Hi Davo,

A very useful feature of tomboy is that in the search results:

- first, the notes with title match are given 
- then, the notes with body match

Would be great to have this in ng as well.

Thanks!

**Comment by monperrus** [comment]
> As an alternative (but, IMHO less satisfactory) approach, how about an option (button, top right of Search Form) to search either title only or whole note ?

not as good as the tomboy-og option but still useful!

thanks Davo

**Comment by davidbannon** [comment]
Hi, version 0.41 of tomboy-ng is now available. I believe it solves the issue you reported here.
Thanks for your input.
Davo

**Comment by monperrus** [comment]
thanks @davidbannon I confirm that one can search in title only now.

It's not exactly the feature described here though.
