### ISSUE TITLE
Cannot copy-paste text from Terminology

### ISSUE THREAD

**Issue by aguador** [tomboy-notes/tomboy-ng#316]
This is a strange, very specific one!

1. Do something in the Terminology, e.g., rpm -qi clipit
2. Copy the resulting text
3. Attempt to paste into a new or existing note

Expected: ¡Voila, the copied text appears!
Actual: Nada, zilch

4. Open text editor
5. Paste copied text (Expected & actual result: text appears)
6. Return to ng note and paste

Expected: ¡Voila, the copied text appears in the note!
Actual: ¡Voila, the copied text appears in the note!

More detail: After step 2 above I confirmed that the text was indeed present in the clipboard before attempting to paste it into a note (as, of course, the results of step 5 suggest).

I have tested with Xterm (Mageia) and XFCE terminal (Artix) and copy and paste works as it should. However, NOT with E's Terminology in either Mageia or Artix. Note also that Xterm has a light theme and the XFCE tested was, like Terminology, dark...so it does not seem to be a theme issue.

Not a big deal given that one can work around it, but curious...

**Comment by aguador** [comment]
Oops: Essential data - tests were of the Gtk2 version on X11 only, ng 0.40a for Mageia, 0.40 for Artix

**Comment by davidbannon** [comment]
Now, thats weird. Are you sure that Enlightenment is not running Wayland ?  I read in the Wikipedia Wayland page that Enlightenment was the first desktop to use it.  

>$ env | grep WAYLAND

Which copy (and paste) model are you using, the conventional Ctrl-C, Ctrl-V or the Unix middle mouse button "primary paste" model ?

Do you use any sort of Clipboard Manager, I use Diodon. As well as remembering a heap pf previous copies, it displays them for you and can show you what you have in the clipboard. But only, I suspect, plain text.

I suspect there is an issue of text format.  (Almost) All apps copy plain text to the clipboard but will also copy one or more of their favorite formats, RTF is a popular example. Typically, the formatted version is used when you paste back into the same application, plain text is the lingua franca between applications.
 
I have not seen this issue on my Mageia Enlightenment test VM, but that is quite old now I guess.  Maybe I need a current Enlightenment test box, Mageia again ?

Davo

**Comment by davidbannon** [comment]
No, I can replicate this, even in my old E install. I normally use the xfce terminal when I use Enlightenment, but if I look for it, I can find Terminology and yep, problem shows up there.
So, I can answer my own questions....

Davo

**Comment by davidbannon** [comment]
OK, so, it seems that terminology only puts two formats in the clipboard, "text/plain; charset=utf-8" and "application; x-elementary". XFCe by comparison does 6 including the (default ?) "text/plain".

It appears to be a KMemo issue, I might need to dig down and see what format Tomas uses. It 'should' be possible look an additional format. I think ....

Davo

![E-paste-terminology](https://github.com/user-attachments/assets/accd7bf0-614f-4a21-8d7d-b9809662613e)
![E-paste-xfce](https://github.com/user-attachments/assets/2f375df4-7c6e-4ef9-bee9-fe95d2d01293)

(putting aside the depressing black colors and tiny little font ...)

**Comment by aguador** [comment]
That's E --lean and mean, not a lot of wasted overhead! :-)

Hope the LCL issue is fixable. BTW, is it not strange that pasting into another app somehow modifies the copied text on the clipboard without actually copying from the other app?

OK, this is above my pay grade...and it looks as if, from that "bug" label on one of the other issues, that you have more urgent things to worry about.

**Comment by davidbannon** [comment]
Hmm, I can probably make a patch but not sure I'd bother if its not going to be accepted. I suspect they may respond that text/plain says it all. 

I will make some inquiries...

Davo

**Comment by davidbannon** [comment]
https://forum.lazarus.freepascal.org/index.php/topic,68624.msg530902.html

**Comment by aguador** [comment]
Hats off and thank you to paweld!
Thanks for pursuing this, Davo. Let's see if it's accepted.

**Comment by davidbannon** [comment]
OK,  I have released a beta that addresses this problem. https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.40b

Davo ;-)

**Comment by aguador** [comment]
Cool, thank you. Only did quick tests with Gtk2 version, but presume this is not dependent on the widget set.

Roy

**Comment by davidbannon** [comment]
Hi, version 0.41 of tomboy-ng is now available. I believe it solves the issue you reported here.
Thanks for your input.
Davo
