### ISSUE TITLE
Cannot display chinese character in pdf export 

### ISSUE THREAD

**Issue by Serenade600** [tomboy-notes/tomboy-ng#317]
The text is 
```Title
测试
这里是中文
Above text is in chinese
```
appearing like 
![image](https://github.com/user-attachments/assets/1375259d-d7cd-486a-89c9-f7444efbaa88)
, but the output in pdf is like 
![image](https://github.com/user-attachments/assets/144e90de-b02b-48bf-8d5c-cb96a0dd6522)

**Comment by davidbannon** [comment]
OK, so the problem there is, I am afraid, the font in use. You have not mentioned which version of tomboy-ng you are using, I recently made some improvements there but don't know if they will help you.

Please tell me which version of tomboy-ng you are using. 

Maybe you can suggest what default fonts would be a good choice to support Chinese text, its about outside my experience !  Perhaps I should have a way for someone like you to select fonts that you know are capable of working. Trouble is that they need to be TTF to work in the PDF exporter.

Davo

**Comment by Serenade600** [comment]
I use the latest version 0.40a on windows 11.
One possible choice of chinese font could be 楷体 using simkai.ttf. This font is frequently used by people and initially contained in Win system.

**Comment by davidbannon** [comment]
Thanks Serenade. This going to be a bit hard I am afraid. That font is not made available on English speaking versions of Windows and I don't seem to be able to download it. I generally use Linux for my development work anyway.

I suspect that Microsoft's license for simkai.tty does not allow it to embed fonts ina document the way tomboy-ng does it, just to make matters worse.

I have done some testes here and can confirm what you say, so, I have some work to do. The biggest blocker seems to be that my code requires TTF fonts, my Linux box has several Simplified Chinese capable fonts but they are not TTF. So, firstly, I need to solve that, then I should, I think, be able to allow you to set a preferred font for PDFs.  That will be a good thing !

But it might just take some time I am afraid.  I'd like to send you some test binaries at some stage so you can test it in a real situation. I hope you understand that I speak or write absolutely no Chinese at all, sorry !

Davo

**Comment by davidbannon** [comment]
OK, what I have found so far. And its not good.

I cannot get simkai.ttf, seems Microsoft does not mention it anywhere. My Windows box has several Simplified Chinese fonts preinstalled but only simsun-extB is a True Type Font. Rest are .ttc, a 'bundle' of true type in one file. And, sadly, the library I use to calculate font dimensions (fpttf) will only work with TTF.

But even with simsun-extB, that library fails to report the correct height of the font, its always 0. This problem only seems to happen with Chinese capable fonts !   

I am investigating further !  Two issues, it needs to work with the more modern .ttc files and must give accurate height.

Davo

**Comment by davidbannon** [comment]
So, I can work around the zero height issue. Its because simsun-extB has CapHeight set to zero. That is don't understand.

But even with a workaround of the height issue, the pdf library does not reproduce the chinese characters. Using fonts know to contain the appropriate charcter. And I find  reports that this is a problem elsewhere.

Not sure where this is heading but whereever it is, its going to be a slow trip !

Davo

**Comment by Serenade600** [comment]
> So, I can work around the zero height issue. Its because simsun-extB has CapHeight set to zero. That is don't understand.
> 
> But even with a workaround of the height issue, the pdf library does not reproduce the chinese characters. Using fonts know to contain the appropriate charcter. And I find reports that this is a problem elsewhere.
> 
> Not sure where this is heading but whereever it is, its going to be a slow trip !
> 
> Davo

Thanks for your effort.  Never mind. Hitch of CJK display is often met. I could use English instead.

**Comment by davidbannon** [comment]
https://forum.lazarus.freepascal.org/index.php/topic,68657.msg531033

**Comment by davidbannon** [comment]
OK,  I have released a beta that addresses this problem. https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.40b

You now get a chance to select the font used before creating the PDF. You can use eith the "Human Name" of the font or the font filename. Sorry, eith seem to need to be in English !

Not all fonts work, it has to be a real True Type Font, *.ttf.   Sadly, it seem that not all fonts with an extension of .ttf are suitable. So, some experimenting might be necessary.

At present, in the beta, the font you use will not be saved in the config. If you test this and find its OK, I will add the ability to save the chosen font in the config and you will not have put it in every time !

Thanks for rising this very interesting problem, I have learnt a lot !

Davo

**Comment by davidbannon** [comment]
Hi, version 0.41 of tomboy-ng is now available. I believe it solves the issue you reported here.
Thanks for your input.
Davo
