### ISSUE TITLE
Search is unexpectedly case sensitive

### ISSUE THREAD

**Issue by mlncn** [tomboy-notes/tomboy-ng#34]
I thought search was broken but it's just case sensitive, when in my opinion (and in my experience with Tomboy) it shouldn't be, at least not by default.

(Still testing version 0.12 and my frame of reference is still the Tomboy available in Debian repositories.)

**Comment by davidbannon** [comment]
Hmm, again this is a performance issue. Can be 'fixed' if desired but at the cost of speed. Might have to be an option ?

**Comment by mlncn** [comment]
I have to push back on both these search issues.  Search is the definition of when one uses an index.  Search as case insensitive by default is definitely a user expectation across every web site, application, etc. in common use less grep.

**Comment by aguador** [comment]
Indeed I noted this as a problem as all text-based applications I have used are case insensitive by default, with most offering the option of overriding that for individual searches. The original Tomboy is not case sensitive for search, nor do I see an option in the application of plugins at the moment to make it case sensitive.

**Comment by davidbannon** [comment]
You know nothing John Snow !
I know that the search function stops at the first xml tag in the note's text content !  Thats far more serious that the case issue or the wildcard issue combined. Sorry !
I believe its a bug in the xml parser I'm using but I am currently coding around it. And what I'm finding so far is slow. Sigh ....
Davo

**Comment by davidbannon** [comment]
Have checked in code that allows user to choose, from Settings form to do a case sensitive search or not.
This check-in also fixes a significant problem in the search tools but at the expense of performance. Further research is indicated.

**Comment by davidbannon** [comment]
Just checked in code that speeds up that search by factor of 100, now searches my test note directory of a 100 notes in about 35mS on my 'medium' speed laptop.
