### ISSUE TITLE
Feature: A notetaker can undo what they typed with ctrl+z

### ISSUE THREAD

**Issue by mlncn** [tomboy-notes/tomboy-ng#35]
It would be nice to restore the undo feature with control or command z or the appropriate operating-specific conventions for undoing.

This might be a feature request against the Free Pascal and Lazarus frameworks that Tomboy NG builds on?

**Comment by davidbannon** [comment]
Actually, KMemo does have built in support for undo, have no idea how it works ....
One day !
D

**Comment by davidbannon** [comment]
Looked into this further and the KMemo support for undo is just a set of stubs, unimplemented.
I don't think I'm going to find the time to implement given this is, in MY opinion, not a high priority and some thing that might be quite an effort and might actually slow down other actions.

Obviously, if someone wants to play, be more than happy to cooperate.
