### ISSUE TITLE
Feature: A notereader can search in-note with ctrl+f

### ISSUE THREAD

**Issue by mlncn** [tomboy-notes/tomboy-ng#36]
(Originally titled this "A notereader can open in-note search dialog with ctrl+f" but have since realized the "Search" button shown 

Currently, "ctrl+f" inserts ""

I had to open the note XML file in a separate program to copy that symbol, because, ah, man, "ctrl+x" doesn't cut, or when it does cut, nothing ends up in the clipboard.  OK, at this point, Tomboy NG is actively fighting basic operating system functionality, let alone implementing common conventions like control/command f or control/command z.

The right-click menu copy or cut doesn't work either.

Like #35 this seems like something that needs to be fixed in the framework Tomboy NG is built in, or we're just not taking advantage of something it does offer.  Is this sort of thing working for people on Mac and Windows?

**Comment by mlncn** [comment]
Update: ctrl+c does copy!

**Comment by mlncn** [comment]
Further update: ctrl+x can cut so long as the performance improvement granted by disabling "Show Internal Links" per #29

**Comment by mlncn** [comment]
ctrl+f still inserts  though!

**Comment by mlncn** [comment]
And ctrl+n (expecting to create a new note) inserts ""

**Comment by mlncn** [comment]
(these are different non-printing characters; GitHub just doesn't ... print them, naturally)

**Comment by davidbannon** [comment]
OK, this comes down to the fact that I don't use keyboard short cuts myself. So don't think about it. The characters you see are probably utf8 characters. I think its easy to add all those shortcuts, I'll need to get a list together....

**Comment by davidbannon** [comment]
OK, just committed code that allows an open note to respond to Ctrl F, Ctrl-Shift F and Crtl N
Searchbox responds to Ctrl N
