### ISSUE TITLE
License of Tomboy NG and its software dependencies?

### ISSUE THREAD

**Issue by mlncn** [tomboy-notes/tomboy-ng#38]
In looking to see about performance-related issues posted for KMemo in regards to #29 i went looking for the KMemo repository and found http://wiki.freepascal.org/KControls with this worrying sentence:

"KControls is provided free on 'as is' basis, with complete source code. However, it is licensed software. More information about license can be found in source file headers."

Anything that wouldn't have a [license that could be included in Debian](https://www.debian.org/social_contract.html#guidelines) wouldn't be a Tomboy replacement for me.  :-/

**Comment by davidbannon** [comment]
KMemo.pas -  
<B>License:</B><BR>
  This code is distributed as a freeware. You are free to use it as part
  of your application for any purpose including freeware, commercial and
  shareware applications. The origin of this source code must not be
  misrepresented; you must not claim your authorship. All redistributions
  of the original or modified source code must retain the original copyright
  notice. The Author accepts no liability for any damage that may result
  from using this code.

**Comment by davidbannon** [comment]
I am assuming no one is still worried about this issue.
