### ISSUE TITLE
Stray letter “c” in Layout of note window on v0.13

### ISSUE THREAD

**Issue by sunjam** [tomboy-notes/tomboy-ng#39]
Visible on the far right, just past “Notebook” on MacOS v0.13

![f81cb01e-408d-4d12-a7a5-6bb9d721f18f](https://user-images.githubusercontent.com/1787238/36343256-b7b08eca-13be-11e8-8890-f4b2cd965a1c.png)

**Comment by davidbannon** [comment]
Ah, yes, sorry Sunjam. It stands for 'Clean'. It changes to 'd' when the memo is 'Dirty', that is, needs to be saved. Its just my way of keeping track of the auto save feature. I will remove it some time in the future, but as I have been recently playing with getting housekeeping tasks, including Save, happening while the system is idle, I need it there for now.
I am very concerned I don't loose any user's notes ....
David

**Comment by davidbannon** [comment]
Have committed code that puts a '*' ahead of the note title when its unsaved. So, the 'c' can go !
Look for this in v0.15
Thanks for the report.
