### ISSUE TITLE
partly highlighted text is unhighlighted using 'highlight'

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#4]
1. hightlight a word in a line
2. mark the whole line 
3. click highlight

# expected behavior
The whole line should be (un-/)highlighted.

# observed behavior
it inverts the marked parts, the previously unhighlighted words are highlighted and the other one is normalized.

**Comment by davidbannon** [comment]
Ah, this is not isolated to "highlight", bold and italics do it too. 
All done in the same function. And a complicated function it is. Sigh .....

**Comment by davidbannon** [comment]
OK, fixed. When we change a selection of text, it has to be done block by block. But we now base the whole change on the first character of selection, not first char of each block !

**Comment by traumschule** [comment]
Good it is fixed now. As I am picky, i tried the following:
- add some words to a line
- mark one word and click highlight, the word gets highlighted
- mark this word or a part of it together with unhighlighted text and click highlight - the whole marked area should get highlighted. instead it gets UNhighlighted.

Side note: Can we change the color of marked highlighted text? Currently I need to unmark text to check if it is highlighted.

**Comment by davidbannon** [comment]
The test to determine whether we highlight or un-highlight is what the first character of the selection is. Thats the standard way and only way that makes sense IMHO.  So, when you say "together with unhighlighted text", whats important is where that (new to the selection) unhighlighted text is. If its in front of the part you just highlighted, then the first character will be unhighlighted and the action is to highlight the  new selection. On the other hand, if the addition to selection is after the part you previously highlighted, the the first character will be already highlighted and the action will be to unhighlight it all.

If this is not whats happening, its a bug, please detail just what you are doing to demonstrate it.

**Comment by davidbannon** [comment]
re your sidenote about color of text. The 'highlight' text color is set in settings.pas, line  number 151.  Hover your mouse over clRed and you can open the unit where the predefined colours are defined.  If necessary, we could make it a user settings.

**Comment by traumschule** [comment]
i agree, Tomboy NG does the same.
