### ISSUE TITLE
Copy n Paste problems under Linux

### ISSUE THREAD

**Issue by davidbannon** [tomboy-notes/tomboy-ng#40]
Just as I released 0.14 I realised there is a significant issue, under Linux, wrt copy and paste when Unicode characters are involved. Specifically -
1. Copying Unicode between two tomboy-ng notes or within one note fails badly. Copying Unicode into or out of tomboy-ng works fine !
2. Copying anything into a note that has bulleted text causes the bullet character (a unicode char) to mess up. This also affects Mac. 
3. I also believe Linux has an occasional issue applying to the first copy after the whole application is started. Its fine after that. This issue has been reported before and then withdrawn by the reporter ...

**Comment by xypd** [comment]
First thank you for taking the mantle and continuing this project. I really find Tomboy/Gnote to be the best app for my needs (it one of 3 note taking solutions that works with an older linux device).

I was looking at using tomboy-mono, but didn't work great on osx. I was using Gnote which was great, but that stop working after 10.13. I was going to try and compile gnote or try homebrewing
 a solution, when I found your endeavors. I'm very excited since at lease at the moment I can see and carefully edit my notes

So, I'm happy to do test some updated binary's for you since I'm running Mac OS X 10.13.3. Or help best I can when I have time.

![tomboy-ng_copy_test](https://user-images.githubusercontent.com/23583395/38580184-49285e14-3cd7-11e8-974d-2577fd88d614.jpg)

**Comment by davidbannon** [comment]
Yep, thats the problem. For sure.
As I noted above, I have a work around, not one I am particularly proud of but will push it out as a temporary fix. And, maybe a proper fix with the next release ?

Anyway, in the next day or so, I will replace the Linux and Mac binaries in v0.14 and if you could test them that would be great.

I am guessing you don't mean you want to build your own ?  You would need to install Lazarus and the KControls addon and then patch KControls as detailed above. Bit of a slow job but not hard....

**Comment by xypd** [comment]
Yeah, I'm currently rebuilding my system on a new machine so I'm trying to keep it to only the important tools and files. I'm considering a few dev like tools for compiling some software (home-brew, even Lazarus), but Lazarus would only be for this app ... so hard to justify at the moment. I will consider it though once I can build a VM or boot drive for stuff like this. So for now I happy to test your binaries. And can let you know if that changes.

**Comment by davidbannon** [comment]
OK, I have updated the binaries associated with v0.14. The changes made are to the build env not the tomboy-ng source !
My tests do indicate that  we've fixed the "pasting unicode" and "messed up bullet points" problem but at the expense of a copy between notes not taking along its format on Linux. I think thats a small price and hopefully one we can claim back in a future release.

**Comment by xypd** [comment]
Tested the latest update (39fa78b). The uni-code works well now, thanks.

However formatting and the bullets seem to be missing now on the Mac.

Additionally, the search command doesn't seem to work. The new note command does work, but only when a note is already open.

![tomboy-ng_copy_test](https://user-images.githubusercontent.com/23583395/38656486-d9e85e74-3de8-11e8-80d0-c9a05c9b7593.jpg)

**Comment by davidbannon** [comment]
OK, can I clarify what you mean about Bullets and Formatting missing ?   If you have a Note A and it contains the words "My Text" in bold, italic and you copy it to another note, Note B, you will end up with "My Text" in plain text in Note B. Thats what I mean about "not taking its formatting along". 
Before this fix, that same paste would have failed completely to copy any unicode and would have killed any bullets that were already in Note B.

I don't rule out fixing the overall problem and have a copy between tomboy-ng notes retain the original formatting but it will involve me learning a lot more about codepages, RTF and UTF8. Obviously copy and paste between different applications almost always is plain text. And, you know what ? Personally, I suspect I'd rather it copied plain text most times !

Next, the search command ?  Do you mean search in this note or search all notes ? Are you invoking it by using a control key combo or the menu item ? If menu, from a notes menu or from the top of screen menu ?  I don't, personally, use the control (etc) keys very much on the Mac because I never know what keys have already been defined for something else.

Ctrl-F (search within a note) without a note having focus does not make sense but maybe Ctrl-Shift-F (search all notes) does.  And I guess Ctrl-N (new note) probably does too. I think I can apply same tricks I used to make [that crossy thing key] Q work (quit the app). This would be Mac only code because Win/Linux users must use the mouse to activate the TrayIcon and then choose a menu item.

Thanks for your help !

**Comment by davidbannon** [comment]
xypd - lets try and keep things simple.

Could you please open a separate ticket for this shortcut key issue ?  Best not to try to track multiple issues with one ticket. Can get confusing. Especially so as your one is a Mac only issue and I suspect we will strick some problems with keyboard shortcuts as I migrate Mac's tomboy-ng to 64bit cocoa.

**Comment by davidbannon** [comment]
Copy n Paste.
I have now worked out where, in KMemo, this copy and paste goes bad. In fact, in two places. I have documented my fixes at http://wiki.lazarus.freepascal.org/KControls/KmemoNotes and reported it to the author of KMemo.  Hopefully he will release a fixed version, in the mean time, anyone wanting to build tomboy-ng needs to apply those fixes to KControls during their Lazarus install.
I'll leave this ticket open for awhile while we see if the that fixed version is, in fact, rolled out.

**Comment by kernelOfTruth** [comment]
I can confirm that formatting and bullets also seem to be missing:

especially highlighting doesn't seem to work on imported tomboy notes,

bold font + italics seem to be working.

When copying notes from e.g. gnote to tomboy-ng no formatting or bullets are preserved - it ends up as plain text

**Comment by davidbannon** [comment]
Next release will have this problem fixed in the binaries. But its not a source issue, its 'upstream' in KControls. So, anyone building from source must apply the patch mentioned above to KControls before compiling.
But copying notes from (eg) gnote and pasting into tomboy-ng is probably not going to preserve formating. The way copy and paste works is an application copying will put its content into the clipboard as plain text and possibly in other formats that it thinks are a good idea. Tomboy-ng uses KControls and KControls uses plain text AND RTF. So, when pasting, an app that thinks to check if the clipboard has any RTF may well copy over formatting. I don't know just what format gnote puts into the clipboard, if its RFT (unlikely) then next release will work. 

I suspect better approach might be to transfer via file. I can easily make tomboy-ng import RTF and, with some effort, some other format as long as its well documented.

Worth looking to see what format gnote can export in perhaps ?

**Comment by davidbannon** [comment]
OK, finally committed a fix for the third and final problem identified in first post of this issue. Closing.
