### ISSUE TITLE
A sync while a note is open might be messy

### ISSUE THREAD

**Issue by davidbannon** [tomboy-notes/tomboy-ng#41]
If you do a sync and you have a note open and that note turns out to be in need of update, that is the remote one is newere than the local, open one, the open one is not closed !

That means, eg, if the user makes a change, it will be saved over top of the newly synced note and not clash warning will be issued.

I think it might be prudent if not convenient to close all notes before starting a sync ....

**Comment by xypd** [comment]
I think I remember it being this way before. You would not get any warning but you would have a conflict file in you tomboy root dir. I would know when I had 2 version of the same note, one new and the other old.

Are you saying it will only keep one file, the last one closed?

**Comment by davidbannon** [comment]
Yes, if user has a note open (but not changed) and does a sync that decides to download a more recent copy of that note, it will do it behind the user's back. If the user then makes a change to the open note, that note will overwrite the one on disk. If the sync wants to delete, I suspect its even worse, note would be marked as deleted but could be resaved.....

**Options** 
1. As we only do sync manually right now, if user clicks 'Sync' and a note is open, tell them to close all notes and try again. Easy, clean but not very friendly. Not compatible with a future auto sync model.
2. As we do a sync, before downloading or deleting a note, close it if open. Reopen if it was a download. This is possibly best option for user but I have designed the tb_sync.pas unit to be quite standalone and not interact with the GUI much.Harder, not clean but user friendly and would work with auto sync.
3. As in 2. but ask the user before closing, friendlier still but means an auto sync would be blocked if user was not watching and if the user is watching but doing something else, interrupts unacceptably.
4. Go ahead with sync and only make a fuss if and when user makes a change to note. Lots harder to implement, would need to alter data structure that keeps track of all notes and would need to consult that before saving a changed note. Um, what if a note is marked as read only as soon as it is sync-download or sync-delete while open ? User can close it (and reopen if it was a sync-download).

Hmm...

**Comment by davidbannon** [comment]
Looks like option 4 might be the winner. I have coded up a function to make a edit box read only, you cannot change it and when you close it, it is not saved.
![readonly](https://user-images.githubusercontent.com/6291248/38670830-2db5fdaa-3e8d-11e8-927f-f51f66ae8a3d.png)
User can still read it and even, if they have made a terrible mistake, can copy its contents and paste that into a new note.

**Comment by davidbannon** [comment]
OK, I have committed a fix for this issue - user will now see an ugly and impossible to miss warning that the note is now read only. Its even possible to copy the contents (using menu, but not Ctrl-C). But only change you can make is to close it. So, no miss understandings.

Also found and fixed a related bug where a note, deleted by the Sync process was still listed under Recently Used items.
