### ISSUE TITLE
Feature: embedding images

### ISSUE THREAD

**Issue by alexanderadam** [tomboy-notes/tomboy-ng#43]
First of all: thank you for your work! I like the idea to have a modern Tomboy with less dependencies. :+1: 

Second: there was a possibility to [enable Image support in Tomboy with a Plugin](https://github.com/mattguo/tomboy-image) and I would really love to have this functionality integrated natively in tomboy-ng.

Thank you in advance and I hope you have a wonderful day!

**Comment by davidbannon** [comment]
Hi Alex, yes, a possibility but only that right now.
KMemo which provides the underlining editing and presentation does, I believe, know how to handle images. However, the tomboy xml does not support images as I understand it. I guess you have defined an extension to tomboy's xml ?

I note you have a DLL ?  Free Pascal is quite happy to call a C style libraries (or make libraries callable from C). So maybe the door is open ?

It would make a lot of sense ....

Right now, I am struggling with some Mac issues relating to a move to 64bit. Necessary if we are to keep calling it "cross platform" into the next MacOSX release.

**Comment by alexanderadam** [comment]
Hi David,

I don't have the DLL anymore. [The source](https://github.com/mattguo/tomboy-image) is the only thing that's left and I didn't try to build it recently.

But I love the idea of embedding images :wink:

**Comment by davidbannon** [comment]
I have, perhaps, cleared the way a little to allow images to be added to tomboy-ng. Some upstream bugs either fixed or in process. But several issues remain -
1. It will mean we are no longer file compatible with Tomboy and/or Tomdroid
2. At present, cocoa (on Mac) cannot paste images, but could load from a file.
3. How to store images ?  I don't think storing images in the xml is a good idea, will make files very large, slow to search. So, is it reasonable to -
  - Store images in a directory named for note GUID ?
  - In a shared dir where image must named for note GUID plus an index ?
  - In a sqlite dbase ?  Ultimatly, where notes should me IMHO, adds a dependancy.
I think I need to know more about how end users would might want to use these images.....

**Comment by davidbannon** [comment]
Its listed on our ToDo list.
I don't think I will be putting the necessary effort in to add images unless I see more interest.
So, if you don't mind, think I'll close it to tidy up a bit.
Feel frre to reopen if you wish.
Davo
