### ISSUE TITLE
Off topic? Tomboy filenames...

### ISSUE THREAD

**Issue by joshp23** [tomboy-notes/tomboy-ng#44]
I am looking into writing a note editor for [grauphel](https://github.com/cweiske/grauphel), and possibly for [gnoted](https://github.com/joshp23/Gnoted), and I would like to have the ability to create new notes, but I am clueless on the file names... how does Tomboy name it's new notes?

------------------------------
[Issue on grauphel](https://github.com/cweiske/grauphel/issues/58) regarding the possibility of an editor

**Comment by davidbannon** [comment]
Hi Josh, its a "GUID", Globally Unique ID. Originally a Windows thing I think, most programming systems now have it built in. In Pascal I call CreateGUID() and get a new one every time.

From memory, its a hash of current time and a number of other particular machine characteristics.

David

**Comment by davidbannon** [comment]
josh, another idea. I could bundle up particular pascal(units) as C libraries. If what ever you are doing can call C libraries, could save some labour.
Davo

**Comment by joshp23** [comment]
Ah, thanks, but I think I can find a nice PHP library to manage that!
