### ISSUE TITLE
implement 'fixed width'

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#5]
The button should select an appropriate fixed width font. Currently it has no effect.

**Comment by davidbannon** [comment]
This is just a case of setting an appropriate font. However, I need to know what font on each platform will be there. It has to be one that can do all the necessary unicode (ie UFT8) characters.

**Comment by davidbannon** [comment]
benjbrandall has provided a pull request that fixes this.
And, wait for it, strikeout, underline and we even have a proper highlight now. Wow !
