### ISSUE TITLE
Enhancement: Single Note Mode notes that aren't in .note format should display file name as title

### ISSUE THREAD

**Issue by benjbrandall** [tomboy-notes/tomboy-ng#53]
Single Note Mode pulls the title in fine from proper Tomboy notes, but when faced with something like Notes.txt (in tomboy-ng source), it shows the Lazarus unit name as the window title. It should do 'Notes.txt'?

**Comment by benjbrandall** [comment]
I'm thinking it is this line:

NoteFileName := AppendPathDelim(ExtractFilePath(NoteFileName)) +
                            ExtractFileNameOnly(NoteFileName) + '.note';     

Which should work fine?

But then I don't know where window title is being set.

As long as it's set as "NoteFileName" when the note type has been detected as text (Editbox.pas, ln971), it should be good?

**Comment by davidbannon** [comment]
Hmm, important to note that a text file is "imported" and becomes a *.note as soon as any save happens.
Normally, during housekeeping, we determine what the Title is and thats copied to the form caption. I think there's a methord called SetTitle() ?  or similar....  We could put a "if SingleNoteMode ..." thingo in there I suppose.
Thats if we feel the need to address this before v0.16 ?  I would like to get v0.16 out, its got some valuable features, your ones in particular.

**Comment by benjbrandall** [comment]
Of course, that's all good. Just using this as a way to track anything I find for future reference. Easier than me losing it in my head, meandering email threads, or local files. :grin:

**Comment by davidbannon** [comment]
OK, fixed with patch from Ben, great work, thanks
