### ISSUE TITLE
Keyboard shortcuts for large and huge text

### ISSUE THREAD

**Issue by benjbrandall** [tomboy-notes/tomboy-ng#58]
Tomboy doesn't have shortcuts for large and huge text, but this is something I would use in addition to those added by #56. 

Proposed:

Ctrl  1: Huge (like H1, or `#` in markdown)
Ctrl  2: Large (like H2, or `##` in markdown)

This would leave small text looking lonely and odd without a shortcut. 

Also interesting:

Ctrl +: Increment font size (from normal to large, large to huge, etc)
Ctrl -: Decrement font size (normal to small, etc)

**Comment by davidbannon** [comment]
I really don't know about this.
Firstly, the Ctrl+ is a problem as most laptops don't have a dedicated + key. Its a shift key. I considered responding to Ctrl =  but what if someone has a different keyboard layout ?

Next, Ctrl 1 for huge based on html H1 is a bit of a long bow IMHO, we'd need to map normal to 3 and small to 4.  And not too many people know their HTML anyway.  Sigh ....

So, as an experiment, I have mapped Ctrl 1 to small, Ctrl 2 to normal, Ctrl 3 to Large and Ctrl 4 to huge, at least its a normal progression. I think. On the Mac, its Command....

I have NOT put that mapping in the menus so its officially not official. And might change....

I'd like a better answer.

**Comment by xypd** [comment]
We could just add a "shift" key to the combo.

So,
Ctrl-shift-1: Huge
Ctrl-shift-2: Large

Also interesting:
Ctrl-shift- +: Increment font size (from normal to large, large to huge, etc)
Ctrl-shift- -: Decrement font size (normal to small, etc)

Just a thought. I wouldn't mind the extra key since it's easy enough to do and it's not something that need to be done as often a say bolds or bullets

**Comment by davidbannon** [comment]
OK, I have been using Ben's initial suggestion of Ctrl-1..4 for a couple of weeks now and I have found it pretty nice to use. Its the same on all platforms (thats nice too).
So, I think I'm going to call it !
Ctrl-1 - small
Ctrl-2 - normal
Ctrl-3 - large
Ctrl-4 - huge
Thanks for input folks !
Davo
