### ISSUE TITLE
implement -v --version option

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#6]
- When this flag is present, tomboy should not be started,
- instead the current version should be shown.
- When compiled from source the commit hash should be used.
- This should also be visible via the ui in the 'About' dialog

**Comment by davidbannon** [comment]
Hmm, its not that hard but I am not sure there is any real need. The app has an "about" dialog that shows version and compile date. If someone wants it, feel free to reopen.

Tomboy does respond to a number of command line arguments and perhaps, in the future, tomboy-ng might do the same. But it will require some demand.
