### ISSUE TITLE
bash ./mk_dmg.bash creates a broken 1kb .app file

### ISSUE THREAD

**Issue by benjbrandall** [tomboy-notes/tomboy-ng#61]
Clone of the latest commits on macOS, when running the mk_dmg inside /packages:

`Hint: (lazarus) Compiler params changed for KControlsLaz 1.7.1
  Old="-MObjFPC -Scgi -O1 -gw -gl -Fi/Users/benjamin/pascal/kcontrols/source -Fu/Users/benjamin/pascal/kcontrols/source -Fu/Developer/lazarus/packager/units/i386-darwin -Fu/Developer/lazarus/components/lazutils/lib/i386-darwin -Fu/Developer/lazarus/lcl/units/i386-darwin -Fu/Developer/lazarus/lcl/units/i386-darwin/carbon -Fu/Developer/lazarus/components/cairocanvas/lib/i386-darwin/carbon -Fu/Developer/lazarus/components/lazcontrols/lib/i386-darwin/carbon -Fu/Developer/lazarus/components/ideintf/units/i386-darwin/carbon -Fu/Developer/lazarus/components/printers/lib/i386-darwin/carbon -Fu/Developer/lazarus/components/tdbf/lib/i386-darwin/carbon -Fu/Users/benjamin/pascal/kcontrols/packages/kcontrols/ -FU/Users/benjamin/pascal/kcontrols/packages/kcontrols/lib/i386-darwin/ -dLCL -dLCLcarbon kcontrolslaz.pas"
  Now="-MObjFPC -Scgi -O1 -gw -gl -Fi/Users/benjamin/pascal/kcontrols/source -Fu/Users/benjamin/pascal/kcontrols/source -Fu/Developer/lazarus/packager/units/i386-darwin -Fu/Developer/lazarus/components/lazutils/lib/i386-darwin -Fu/Users/benjamin/pascal/kcontrols/packages/kcontrols/lib/i386-darwin -Fu/Developer/lazarus/lcl/units/i386-darwin -Fu/Developer/lazarus/lcl/units/i386-darwin/carbon -Fu/Developer/lazarus/components/cairocanvas/lib/i386-darwin/carbon -Fu/Developer/lazarus/components/lazcontrols/lib/i386-darwin/carbon -Fu/Developer/lazarus/components/ideintf/units/i386-darwin/carbon -Fu/Developer/lazarus/components/printers/lib/i386-darwin/carbon -Fu/Developer/lazarus/components/tdbf/lib/i386-darwin/carbon -Fu/Users/benjamin/pascal/kcontrols/packages/kcontrols/ -FU/Users/benjamin/pascal/kcontrols/packages/kcontrols/lib/i386-darwin/ -dLCL -dLCLcarbon kcontrolslaz.pas"
  State file="/Users/benjamin/pascal/kcontrols/packages/kcontrols/lib/i386-darwin/KControlsLaz.compiled"
Info: (lazarus) Execute Title="Compile package KControlsLaz 1.7.1"
Info: (lazarus) Working Directory="/Users/benjamin/pascal/kcontrols/packages/kcontrols/"
Info: (lazarus) Executable="/usr/local/bin/ppc386"
Info: (lazarus) Param[0]="-MObjFPC"
Info: (lazarus) Param[1]="-Scgi"
Info: (lazarus) Param[2]="-O1"
Info: (lazarus) Param[3]="-gw"
Info: (lazarus) Param[4]="-gl"
Info: (lazarus) Param[5]="-l"
Info: (lazarus) Param[6]="-vewnibq"
Info: (lazarus) Param[7]="-vh-"
Info: (lazarus) Param[8]="-Fi/Users/benjamin/pascal/kcontrols/source"
Info: (lazarus) Param[9]="-Fu/Users/benjamin/pascal/kcontrols/source"
Info: (lazarus) Param[10]="-Fu/Developer/lazarus/packager/units/i386-darwin"
Info: (lazarus) Param[11]="-Fu/Developer/lazarus/components/lazutils/lib/i386-darwin"
Info: (lazarus) Param[12]="-Fu/Users/benjamin/pascal/kcontrols/packages/kcontrols/lib/i386-darwin"
Info: (lazarus) Param[13]="-Fu/Developer/lazarus/lcl/units/i386-darwin"
Info: (lazarus) Param[14]="-Fu/Developer/lazarus/lcl/units/i386-darwin/carbon"
Info: (lazarus) Param[15]="-Fu/Developer/lazarus/components/cairocanvas/lib/i386-darwin/carbon"
Info: (lazarus) Param[16]="-Fu/Developer/lazarus/components/lazcontrols/lib/i386-darwin/carbon"
Info: (lazarus) Param[17]="-Fu/Developer/lazarus/components/ideintf/units/i386-darwin/carbon"
Info: (lazarus) Param[18]="-Fu/Developer/lazarus/components/printers/lib/i386-darwin/carbon"
Info: (lazarus) Param[19]="-Fu/Developer/lazarus/components/tdbf/lib/i386-darwin/carbon"
Info: (lazarus) Param[20]="-Fu/Users/benjamin/pascal/kcontrols/packages/kcontrols/"
Info: (lazarus) Param[21]="-FU/Users/benjamin/pascal/kcontrols/packages/kcontrols/lib/i386-darwin/"
Info: (lazarus) Param[22]="-dLCL"
Info: (lazarus) Param[23]="-dLCLcarbon"
Info: (lazarus) Param[24]="kcontrolslaz.pas"
Free Pascal Compiler version 3.0.4 [2017/11/26] for i386
Copyright (c) 1993-2017 by Florian Klaempfl and others
(1002) Target OS: Darwin for i386
(3104) Compiling kcontrolslaz.pas
(9001) Assembling (pipe) /Users/benjamin/pascal/kcontrols/packages/kcontrols/lib/i386-darwin/kcontrolslaz.s
(1008) 26 lines compiled, 5.8 sec
Hint: (lazarus) State file of KControlsLaz 1.7.1 is newer than state file of Project: Tomboy_NG
Info: (lazarus) Execute Title="Compile Project, Mode: Release, Target: tomboy-ng"
Info: (lazarus) Working Directory="/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/"
Info: (lazarus) Executable="/usr/local/bin/ppc386"
Info: (lazarus) Param[0]="-B"
Info: (lazarus) Param[1]="-Tdarwin"
Info: (lazarus) Param[2]="-Pi386"
Info: (lazarus) Param[3]="-MObjFPC"
Info: (lazarus) Param[4]="-Scghi"
Info: (lazarus) Param[5]="-CX"
Info: (lazarus) Param[6]="-O3"
Info: (lazarus) Param[7]="-XX"
Info: (lazarus) Param[8]="-k-framework"
Info: (lazarus) Param[9]="-kCarbon"
Info: (lazarus) Param[10]="-k-framework"
Info: (lazarus) Param[11]="-kOpenGL"
Info: (lazarus) Param[12]="-k-dylib_file"
Info: (lazarus) Param[13]="-k/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib:/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib"
Info: (lazarus) Param[14]="-l"
Info: (lazarus) Param[15]="-vewnhibq"
Info: (lazarus) Param[16]="-Fi/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin"
Info: (lazarus) Param[17]="-Fu/Users/benjamin/pascal/kcontrols/packages/kcontrols/lib/i386-darwin"
Info: (lazarus) Param[18]="-Fu/Developer/lazarus/components/tdbf/lib/i386-darwin/carbon"
Info: (lazarus) Param[19]="-Fu/Developer/lazarus/components/printers/lib/i386-darwin/carbon"
Info: (lazarus) Param[20]="-Fu/Developer/lazarus/components/ideintf/units/i386-darwin/carbon"
Info: (lazarus) Param[21]="-Fu/Developer/lazarus/components/lazcontrols/lib/i386-darwin/carbon"
Info: (lazarus) Param[22]="-Fu/Developer/lazarus/components/cairocanvas/lib/i386-darwin/carbon"
Info: (lazarus) Param[23]="-Fu/Developer/lazarus/lcl/units/i386-darwin/carbon"
Info: (lazarus) Param[24]="-Fu/Developer/lazarus/lcl/units/i386-darwin"
Info: (lazarus) Param[25]="-Fu/Developer/lazarus/components/lazutils/lib/i386-darwin"
Info: (lazarus) Param[26]="-Fu/Developer/lazarus/packager/units/i386-darwin"
Info: (lazarus) Param[27]="-Fu/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/"
Info: (lazarus) Param[28]="-FU/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/"
Info: (lazarus) Param[29]="-otomboy-ng"
Info: (lazarus) Param[30]="-dLCL"
Info: (lazarus) Param[31]="-dLCLcarbon"
Info: (lazarus) Param[32]="Tomboy_NG.lpr"
Hint: (11030) Start of reading config file /etc/fpc.cfg
Hint: (11031) End of reading config file /etc/fpc.cfg
Free Pascal Compiler version 3.0.4 [2017/11/26] for i386
Copyright (c) 1993-2017 by Florian Klaempfl and others
(1002) Target OS: Darwin for i386
(3104) Compiling Tomboy_NG.lpr
(3104) Compiling searchunit.pas
(3104) Compiling note_lister.pas
(3104) Compiling settings.pas
(3104) Compiling searchunit.pas
(3104) Compiling mainunit.pas
(3104) Compiling uappisrunning.pas
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/uappisrunning.s
(3104) Compiling editbox.pas
(3104) Compiling savenote.pas
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/savenote.s
(3104) Compiling loadnote.pas
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/loadnote.s
(3104) Compiling syncgui.pas
(3104) Compiling tb_sync.pas
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/tb_sync.pas(300,18) Hint: (5024) Parameter "UseLocal" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/tb_sync.pas(300,28) Hint: (5024) Parameter "UseRemote" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/tb_sync.pas(310,25) Hint: (5024) Parameter "FileID" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/tb_sync.pas(310,33) Hint: (5024) Parameter "Rev" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/tb_sync.pas(312,30) Hint: (5024) Parameter "ID" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/tb_sync.pas(312,34) Hint: (5024) Parameter "Rev" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/tb_sync.pas(316,52) Hint: (5024) Parameter "CurrRev" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/tb_sync.pas(318,28) Hint: (5024) Parameter "ID" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/tb_sync.pas(277,31) Hint: (5024) Parameter "WriteDeletes" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/tb_sync.pas(277,63) Hint: (5024) Parameter "CurrRev" not used
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/tb_sync.s
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/syncgui.pas(79,25) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/syncgui.pas(79,46) Hint: (5024) Parameter "CloseAction" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/syncgui.pas(80,36) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/syncgui.pas(89,38) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/syncgui.pas(81,24) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/syncgui.pas(83,35) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/syncgui.pas(83,52) Hint: (5024) Parameter "ACol" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/syncgui.pas(76,33) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/syncgui.pas(77,29) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/syncgui.pas(78,34) Hint: (5024) Parameter "Sender" not used
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/syncgui.s
(3104) Compiling spelling.pas
(3104) Compiling hunspell.pas
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/hunspell.pas(169,17) Hint: (4055) Conversion between ordinals and pointers is not portable
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/hunspell.s
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/spelling.pas(65,28) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/spelling.pas(66,33) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/spelling.pas(62,45) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/spelling.pas(61,37) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/spelling.pas(63,35) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/spelling.pas(64,28) Hint: (5024) Parameter "Sender" not used
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/spelling.s
(3104) Compiling notebook.pas
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/notebook.pas(72,24) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/notebook.pas(70,29) Hint: (5024) Parameter "Sender" not used
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/notebook.s
(3104) Compiling k_prn.pas
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/k_prn.s
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(218,33) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(219,34) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(217,35) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(214,29) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(215,27) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(216,31) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(238,35) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(234,29) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(234,68) Hint: (5024) Parameter "Shift" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(234,88) Hint: (5024) Parameter "X" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(234,91) Hint: (5024) Parameter "Y" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(480,5) Note: (5025) Local variable "Point" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(481,5) Note: (5025) Local variable "LinePos" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(235,33) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(235,50) Hint: (5024) Parameter "Button" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(236,13) Hint: (5024) Parameter "Shift" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(236,33) Hint: (5024) Parameter "X" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(236,36) Hint: (5024) Parameter "Y" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(240,38) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(257,34) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(258,35) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(259,34) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(241,33) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(237,33) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(242,35) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(243,38) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(244,38) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(239,39) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(221,32) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(250,31) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(245,31) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(246,30) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(247,39) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(248,48) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(249,42) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(251,32) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(252,38) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(253,36) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(254,38) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(255,31) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(260,28) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(230,28) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(222,29) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(222,50) Hint: (5024) Parameter "CloseAction" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(223,30) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(224,25) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(261,42) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(231,32) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(233,27) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/editbox.pas(256,38) Hint: (5024) Parameter "Sender" not used
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/editbox.s
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(187,5) Note: (5025) Local variable "I" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(115,28) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(109,38) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(110,32) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(111,29) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(286,3) Note: (5025) Local variable "t" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(112,29) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(112,50) Hint: (5024) Parameter "CloseAction" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(113,30) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(114,31) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(108,37) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(117,34) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(121,35) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(122,31) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(123,33) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(118,31) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(120,33) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/mainunit.pas(116,32) Hint: (5024) Parameter "Sender" not used
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/mainunit.s
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(113,34) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(111,36) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(115,30) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(116,24) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(117,23) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(118,28) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(119,30) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(120,25) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(121,31) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(123,22) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(128,39) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(114,37) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(127,38) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(112,40) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(125,43) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(124,37) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/searchunit.pas(126,42) Hint: (5024) Parameter "Sender" not used
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/searchunit.s
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(171,32) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(170,35) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(163,34) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(163,66) Hint: (5024) Parameter "Shift" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(168,28) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(169,28) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(164,23) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(166,30) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(167,31) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(154,37) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(155,35) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(157,36) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(158,37) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(159,35) Hint: (5024) Parameter "Sender" not used
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/settings.pas(162,33) Hint: (5024) Parameter "Sender" not used
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/settings.s
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/note_lister.s
/Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/Tomboy_NG.lpr(14,60) Hint: (5023) Unit "Notebook" not used in Tomboy_NG
(9001) Assembling (pipe) /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/Tomboy_NG.s
(9022) Compiling resource /Users/benjamin/Dev/tomboy-ng/tomboy-ng/tomboy-ng/lib/i386-darwin/Tomboy_NG.or
(9015) Linking tomboy-ng
(1008) 8144 lines compiled, 4.5 sec
(1022) 128 hint(s) issued
(1023) 4 note(s) issued
total 0
lrwxr-xr-x  1 501  20  13 Jun 29 09:19 Applications -> /Applications
drwxr-xr-x  3 501  20  96 Jun 29 09:19 tomboy-ng.app
rm: tomboy-ng32.dmg: No such file or directory
./mk_dmg.bash: line 38: /Users/benjamin/create-dmg-master/create-dmg: No such file or directory`

And the .app it creates is attached. Is my setup wrong / am I missing something?

[tomboy-ng.app.zip](https://github.com/tomboy-notes/tomboy-ng/files/2147990/tomboy-ng.app.zip)

**Comment by benjbrandall** [comment]
Log attached as .txt here for readability
[mk_dmg_console_log.txt](https://github.com/tomboy-notes/tomboy-ng/files/2148000/mk_dmg_console_log.txt)

**Comment by davidbannon** [comment]
Ben, I see nothing wrong in that log but there should be more. 
The last line is about removing any previous DMG file, first run would not expect to find one there anyway.
I use a tool i downloaded from the interweb thing to make the dmg file. Its mentioned at the top of the script, you have to install it. It then calls a number of built in Apple tools, inc some visual ones, to do the dmg stuff. I see no mention of that at the end of your log....

**Comment by davidbannon** [comment]
Ben, I just looked at the the script. Its the last line that appears to be missing. It calls create-dmg and even if you have it installed, I bet you have it in a different place than I have (cos I struggle with things Mac).
You should see source_folder there however, it should contain a start of the file system that ends up the DMG file.
Davo

**Comment by davidbannon** [comment]
Ben, are you happy for me to close this issue ?
David

**Comment by benjbrandall** [comment]
Yep, no problems David! was my mistake.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by davidbannon** [comment]
All under control.
