### ISSUE TITLE
Add HTML export

### ISSUE THREAD

**Issue by benjbrandall** [tomboy-notes/tomboy-ng#62]
Some initial notes around HTML export:

I thought HTML export might be possible by adding the functionality to kmemo.pas in kcontrols source and RTF writer in kmemortf.pas. After a couple of mins in those files, I realized it'd be a horrible mess.

Perhaps something like how savenote.pas works, replacing tags?

Given a saved tomboy-ng XML file, the ExportToHTML function should:

Substitute `<bold>` and `</bold>` for `<b>` and `</b>`.

Substitute `<italic>` and `</italic>` for `<em>` and `</em>`.

Substitute `<strikeout>` and `</strikeout>` for `<del>` and `</del>`.

Substitute `<monospace>` and `</monospace>` for `<pre>` and `</pre>`.

Substitute `<highlight>` and `</highlight>` for an additional `style="display:inline; background-color:yellow;"` inside the parent element tag of whatever is highlighted. For example, `<p style="display:inline; background-color:yellow;">This is highlighted.</p>`.

Substitute `<size:small>` and `</size:small>` for `<small>` and `</small>`.

Substitute `<size:large>` and `</size:large>` for `<h2>` and `</h2>`

Substitute `<size:huge>` and `</size:huge>` for `<h1>` and `</h1>`

Bullets may well be a pain; right now, we use:

`<list><list-item dir="ltr">`

Whether it's the first or nth bullet in the list. This contrasts with HTML's convention, where a list block is surrounded with `<ul>` `</ul>`.

So, I suppose the first occurrence of an open `<list><list-item dir="ltr">` is replaced by a `<ul><li>`, and then the next (up til the last) with a `<li>`, and then the last `</list></list-item dir="ltr">` with a `</li></ul>`.

We could lazily do a `<ul><li>Bullet</li></ul>` for every line, but the differences are quite big, see: https://jsfiddle.net/7b2j9u61/1/

**Comment by davidbannon** [comment]
Yep, I strongly advise against directly modifying KControls. Would mean we'd have to patch every new version. Agree a new unit not unlike savenote is the way to go.
Bullets is always the problem, sigh ....
If you look in savenote, you will see I had to deal with same sort of issue. And its very ugly.
It can be done but I reckon I'd do the easy way, line by line, first and then get everything else working and then go back and tidy the bullets up.
Am I right in saying most browsers can handle overlapping tags but its a bad thing to do anyway ?

David

**Comment by benjbrandall** [comment]
>  Am I right in saying most browsers can handle overlapping tags but its a bad thing to do anyway ?

Yep, it's a first-in, first-out thing. e.g. <em><del><p>Text Here</p></dev></em>

> line by line, first and then get everything else working and then go back and tidy the bullets up.

That sounds a lot better!

**Comment by davidbannon** [comment]
I think I will close this, there does not seem to be a lot of interest and we can export in markdown.
Feel free to reopen if still wanted.
Davo

**Comment by davidbannon** [comment]
Wow, this ticket turned out a lot older than I thought it was.
Anyway, I have just now released a version of TomboyTools that does export in HTML and does follow links within the note when doing so.

All the best, Davo
