### ISSUE TITLE
Need an obvious way to debug note sync problems on Windows

### ISSUE THREAD

**Issue by erik-brangs** [tomboy-notes/tomboy-ng#64]
Problems during note sync are easy to debug on Linux thanks to the new --debug-sync switch.

How can I provide information about note sync problems on Windows? There isn't any console output and the lines with error in the synchronisation dialogue aren't clickable.

**Comment by davidbannon** [comment]
Sorry Eric, something I skipped over I am afraid.
Its a little harder under windows due, as you note to no default console.
The debug messages can be written to a file that you can read later. But you have to tell the app where that file is. So, you need to either create a windows shortcut with this info or launch tomboy-ng from the command line. The latter is my preferred model of course being a Linux user, use what suits you.
From memory (I don't have a windows machine with me at present) the command line would be eg
tomboy-ng --debug-sync --debug-log=somefile.txt

You need to do that somewhere were you have write permission or set a valid path in front of the "somefile.txt".

You can do what you want and the read the file with (eg) notepad. There are some tools that let you tail a file but I am afraid I cannot remember what they are under windows. Please let me know if you don't make good progress.
David

**Comment by davidbannon** [comment]
http://wiki.freepascal.org/LazLogger

**Comment by erik-brangs** [comment]
Thanks. I wasn't able to make it work with the `--debug-log` flag (tomboy-ng just didn't start) but setting the environment variable `tomboy-ng64_debuglog` worked.

The problems that I saw where:
- wrong nesting of tags in two notes, e.g.
`<list><list-item dir="ltr">Text <underline>OtherText</list-item></list></underline>` instead of
`<list><list-item dir="ltr">Text <underline>OtherText</underline></list-item></list>`
- 1 problem with `&` - there was `& &amp` in the source of the note

**Comment by davidbannon** [comment]
Ah, thats good info Erik. The underline is new code and I guess a bug has slipped through. What you see there is definitely bad xml. Will mess with Indexing but will load into the editbox (as I noted in other post).

I suggest you avoid using underline until we have fixed this. And I am away from the box I generate windows binaries for many weeks I'm afraid. 

**The & issue.** You mention there was a "& &amp" in the xml, can I clarify ?  Note "& &amp;" ? with a semicoma after the amp ?

Is it possible the & that has been messed up was involved with a bullet point ? I am quite unhappy with the bullet code, for reasons just outside my reach, its vastly more complicated than it should be. 
Davo

**Comment by erik-brangs** [comment]
It was indeed `& &amp;`. I must have cut off the end during copy & paste. IIRC I saw the problems with `&` in several places, both in the title and in the main body of the note.

**Comment by davidbannon** [comment]
OK, I have traced the problem relating to the underline xml. A misplaced 'end' that was allowing BulletList() to skip a few lines. I have fixed that with a commit to source just now. But I will not be able to generate new binaries with that fix for some time. 
So, unless you are willing to pull down the source and build it yourself, all I can recommend is you avoid having underline, strike out and fixed width inside Bullet Lists. And I'll ship new binaries as soon as I return home.
Very sorry about that.
I have not been able reproduce the & problem #63 at this stage.

**Comment by davidbannon** [comment]
I have committed some changes that will now push out a short text file, a copy of the linux/mac man page, with the 64bit windows install kit. And the html directory with further docs.
Not proper windows help files but, hopefully a step in right direction.
