### ISSUE TITLE
Escaping in manifest.xml is wrong in tomboy-ng 0.16a

### ISSUE THREAD

**Issue by erik-brangs** [tomboy-notes/tomboy-ng#66]
The escaping in tomboy-ng 0.16a is wrong for one of my notes. From the manifest.xml under `<note-deletions>`:
```
    <note guid="584d4574-778a-4e40-b1e6-15e9b613c3f7" title="(nur falls nötig) plus / minus Long methoden implementieren & testen" />
```

The `&` leads to an error during XML parsing.

**Comment by benjbrandall** [comment]
Just theorizing before coding, I think just above line 544 in tb_sync.pas (1) -- or actually in the loop below? -- there needs to be a function called that takes ManifestList.Items[Index].Title as the arg and strips it of its invalid characters and replaces (2), e.g.

substitute & for &#038;

(1) https://github.com/tomboy-notes/tomboy-ng/blob/318525714cd50c864e7e56cb14ddc7649455f03d/tomboy-ng/tb_sync.pas#L544
(2) https://www.w3.org/TR/xml/#syntax

**Comment by davidbannon** [comment]
Yep, I would say you are both right !
From memory, I do no filtering of the three critical char in any of the manifest files. Its only titles that get copied in there, any title that includes 
< > &
and going to cause problems.

Should not be difficult to fix but I'll not be able to address until at least tomorrow, very sorry folks !

Davo

**Comment by benjbrandall** [comment]
I'm working on a function for this now, it's a simple one so good practice for me to improve my actual Pascal skills vs. my figuring-things-out-from-looking-at-David's-code skills.

o.s. As I can see it, there's 5 chars that need to be considered: & < > " '

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by davidbannon** [comment]
SaveNote has one to do it ....

Tomboy does not munge single and double quotes. Only < > & - I found another reference (don't remember where right now) that also does not mention the two quotes....

**Comment by davidbannon** [comment]
Going slowly here. Users notes at risk !
Problems that need addressing -
1. Do we need to include ' and " in this fix ?  Tomboy does not seem to worry about single or double inverted commas. Only angle brackets and ampersand. Indeed, Tomboy errors out on a note that contains eg & quot; (a space inserted to prevent Github encoding) - so it appears we must not include that in a note. But the manifest files ?? I think we must follow Tomboy's lead here, even if its bad XML.
2. Writing either manifest file during sync
3. Reading either manifest file during sync
4. Writing the XML tag for Note title (before content is written).
5. Do we read the XML for note title or just rely on the content version of it ?
There is already a function that scans for <, >, and & in SaveNote and reinserts those three char in ReadNote. Can be used in EditBox as it already uses SaveNote and ReadNote. But I don't want to introduce extra dependencies into Sync as it has been written as a stand alone unit that could be used outside of tomboy-ng. May have to consider abandoning that approach or move xml fiddling functions to a separate unit ?
Tests must take into account use of UTF8 characters around the munged string.

**Comment by davidbannon** [comment]
OK, just committed fixes for 4) and 5) above for <>&. Two lines of code. 
Will now look at Ben's solution for 2) or 'use' SaveNote and LoadNote model to do 2) and 3).

**Comment by davidbannon** [comment]
Reading local manifest is all done with XML library functions so 3) is OK.  Just checked in code to fix 2)
Ben, I did not use you suggestion as it turned out both a lot harder to check and a lot simpler to fix juts pasting the existing function (from SaveNote) into TB_Sync. And that keeps TB_Sync pretty standalone still. I suspect the optomizer might just deal with the duplication anyway...

But I am still unsure of what to do about ' and ".  Tomboy does not mess with them, if we are to retain file compatibility with Tomboy, tomboy-ng should do the same. But its perhaps bad xml ?

**Comment by benjbrandall** [comment]
Where abouts are you seeing the equivalent Tomboy function? Is it the call to xml.WriteString in utils.cs? https://github.com/tomboy-notes/tomboy/blob/572a596185c7cbd0303436609ae3668b563d9d55/Tomboy/Utils.cs#L723

**Comment by davidbannon** [comment]
No, I'm testing a running version of Tomboy 1.15.6

**Comment by davidbannon** [comment]
OK, further testing still says to me that we do not need to munge the ' and " characters. I don't understand why.
As I am quite worried about this bug that Erik picked up for us, I have just now pushed new binaries to v0.16a. 
Erik, I recommend you pull down new binaries from there, they are new as of today (2018/07/28) even though they have the same v0.16a tag. Its bad practice but 0.16a is not an official release so I plead that its not too bad !

David

**Comment by erik-brangs** [comment]
Thank you.

I've fixed up the broken manifest manually. After that synchronization worked with the new version. I also tested the new version with another note that contained ``&``  in the title. This also worked so this issue is solved from my point of view.

**Comment by davidbannon** [comment]
Thanks Erik for bring this problem to our attention. Scary that its been there since day one !
