### ISSUE TITLE
Case sensitive links break compatibility with Tomboy

### ISSUE THREAD

**Issue by benjbrandall** [tomboy-notes/tomboy-ng#78]
Working inside Tomboy, I created a note in which the phrase 'remote manifest' was linked to a note called Remote Manifest. Inside -ng, the link no longer exists.

Would it be possible to add a setting that allows for case insensitive automatic links?

**Comment by davidbannon** [comment]
Hmm, Rather than an option, should we just do it like Tomboy ?

**Comment by davidbannon** [comment]
Yes, its definitely a problem !  If you have a note and use its name in another note, it shows up as a link. Good. But if the two names don't match case, clicking on the link opens a new, blank note !  So, must fix !
Think I'll just make it all non-case sensitive.

**Comment by davidbannon** [comment]
OK, tested and found good.
