### ISSUE TITLE
Add possibility to not display the welcome form at startup

### ISSUE THREAD

**Issue by erik-brangs** [tomboy-notes/tomboy-ng#79]
When `tomboy-ng` is started, the welcome form with the title "MainForm" is displayed. It has to be dismissed manually.

I'd like to have an option to suppress the display of the form. I have added `tomboy-ng` to autostart and don't want or need to see the form after logging in. A command line flag would be sufficient for my needs.

I haven't configured the dictionaries so not displaying the form when everything is configured wouldn't help me.

**Comment by davidbannon** [comment]
Hmm, not sure I was paying attention.

Erik, did you try     --no-splash    ?

If it does not do as you requested (with your current binary), please let me know on what platform and, perhaps, with what other command line options you use ?
David

**Comment by erik-brangs** [comment]
The flag ``--no-splash`` seems to work fine. Thanks.

In the long term, there should probably be a GUI option (e.g. "start minimized" or something like that). These options are fairly common for Windows programs in my experience.

**Comment by davidbannon** [comment]
Yes Erik, it would be easy to add a config option to that effect. However, some Gnome3 based linux distributions (and Mac Cocoa) need that splash screen as the TrayIcon is not visible. If you set yours to no-splash permanently now, and later upgrade to eg Fedora, you suddenly won't be able to control tomboy-ng (without, perhaps, deleting the config file and rebooting).

The real solution is to fix the TrayIcon component so it does not offend the designers of Gnome3 or to find a reliable fix for the issue they have created. I'm reluctant to maintain, for example, a list of distros that are OK and those that are not, too dependent on upkeep. Then no need for splash screen at all.

Time permitting, I do expect to be able to make some changes to the TrayIcon it self (I have already had some changes accepted) that may be better at detecting if it is, or is not working as expected. That would at least make the process semi automatic. But not in the immediate future.

Davo

**Comment by davidbannon** [comment]
Just tidying up issues list. I don't think I can help you any more but if I can, please reopen this ticket.
Davo

**Comment by davidbannon** [comment]
V0.2 will have a setting to not show splash.  
-g or any errors while initial reading of notes will force the splash screen to show.
