### ISSUE TITLE
deletion fails sometimes, 90% cpu load using links to a deleted note

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#8]
About output: Build date 2017/11/26 TargetCPU i386 OS Linux
OS: debian stretch
Version: ea481bd
size: 32M
build command: lazbuild --pcp=../../lazconf Tomboy_NG.lpi # lazconf contains environmentoptions.xml (automatically copied from /etc/lazarus/) and packagefiles.xml which links kcontrolsbase.lpk kcontrolslaz.lpk
Lazarus version: 1.8.0RC5

1. Delete a note
 - sometimes (not always) the note keeps listed in the tray and i see
> Failed to remove ref to note in NoteLister E92E6135-A0FD-46B3-9716-380216487FEB.note
 - when I click on the entry in the tray (which should have been removed): 
> Assuming a new note /home/user/src/tomboy/Notes/50BDC199-14C8-4D97-B20A-B4A78A5D0B97.note [test]
It opens a new note with that title, which is fine.
2. Click on the link to a deleted note and see ~90% cpu load with no chance to get it responsive again. Last message before I
killed it 
> Peek !!!
> Peek !!!
> Peek !!!

edit: even xkill only closes open notes and removes the tray, the main process keeps consuming my cpu.

**Comment by davidbannon** [comment]
Hmm, that sounds horribly like we are searching endlessly through the list for that deleted note. Firstly, a deleted note should disappear from the tray list immediately, secondly, it should be quite safe to search for a note that does not exist. Thats sounds like two sep issues.

**Comment by traumschule** [comment]
could not reproduce this
