### ISSUE TITLE
Bump version number?

### ISSUE THREAD

**Issue by jbicha** [tomboy-notes/tomboy-ng#80]
tomboy-ng is more or less a replacement for tomboy, right?

tomboy's latest release was 1.15.9 but tomboy-ng's version is only 0.18.

I think it might be helpful for Linux distros if you bumped tomboy-ng's version number so it was higher than 1.15.9.

**Comment by davidbannon** [comment]
Thanks for the suggestion Jeremy, I understand what you mean but am not convinced its appropriate.
tomboy-ng is a new implementation, a new code base. Apart from behavior and the note format, it does not share anything with Tomboy. I think continuing Tomboy's release numbers would be misleading.
tomboy-ng is still not the mature product Tomboy is, we don't have a net based sync model, no formal package manager for windows.
And while it would be great to see a distro adopt it, not sure we're ready for that, for example, don't have a deb src package available yet.

**Comment by davidbannon** [comment]
Just tidying up issues list. I don't think I can help you any more but if I can, please reopen this ticket.
Davo
