### ISSUE TITLE
Set language to not-english??

### ISSUE THREAD

**Issue by tuxedotje** [tomboy-notes/tomboy-ng#81]
Sorry to ask a question here. No tomboy user manual on the web as far as I can find. 
Need to set language in Tomboy. Got hunspell and gtkspell in Fedora 29 beta. But tomboy only offers a sprong of English languages.

**Comment by davidbannon** [comment]
Are you asking about tomboy-ng or the original Tomboy ?
I believe Tomboy has full language support.
But tomboy-ng (where you have asked your question) has none. The capability is there but so far, no one has offered to do any translating ....
(But tomboy-ng 'should' support non english dictionaries ...)

**Comment by tuxedotje** [comment]
Thank you for your kind answer.

**Comment by davidbannon** [comment]
Just tidying up issues list. I don't think I can help you any more but if I can, please reopen this ticket.
Davo
