### ISSUE TITLE
Request to Add a shortcut for bullets

### ISSUE THREAD

**Issue by xypd** [tomboy-notes/tomboy-ng#85]
On the old note port of tomboy on the Mac you were able to use shortcuts to add or remove bullets & sub-bullets. They were using cmd-arrow left or right. Right would be add and left was remove.

Perhaps for cross platform use, you could use the option or control-shift key?

So option-arrow-right or control-shift-arrow-right to add or change a line into a bullet.

This feature work this way on my mobile device as well, very handy.

![shortcut_bullets](https://user-images.githubusercontent.com/23583395/48365150-11915000-e678-11e8-9f2e-e6c41b6a3b77.jpeg)

**Comment by davidbannon** [comment]
Yeah, should not be too hard to do but as noted elsewhere, I need to do some work on Bullets anyway.
Real issue is, as you noted, making it suitably cross platform.  I have real problem understanding ctrl/cmd keys on the Mac.  Even when I use my development IDE nothing works as I expect !
So, we'd need to decide do we use the same key binding as we use with tomboy-ng (and Tomboy) on Linux/Windows or do we use the ones Mac users expect to use ?
Do you find that other ctrl key things work as expected ?  ie Bold, Italics etc ?
Davo

**Comment by davidbannon** [comment]
On the original Tomboy, bullets were Alt-Right (and Alt-Left to turn off). I have implemented just that (and done a number of other bullet improvements) and when tested on my Mac, that seems to have translated to option-right and option-left.

Indeed, my old Powerbook, has 'alt' printed in small letters on the 'option' key so it appears that is the intention.  Now, I've never seen an original Tomboy running on a Mac so don't know which key it used but seems to me to make sense to use the same key across all platforms where ever possible.

So, while you suggested the command key, would you be OK with option key on the Mac ?

Davo

**Comment by xypd** [comment]
> Do you find that other ctrl key things work as expected ? ie Bold, Italics etc ?

Yes the other control seems to work fine on all the other shortcuts. Just was missing the bullets. Though having a shortcut for +- font size could be useful as well. But can live with out that.


>Now, I've never seen an original Tomboy running on a Mac so don't know which key it used but seems to me to make sense to use the same key across all platforms where ever possible.

In the attached image in the first post you can see icon that indicate the shortcut key. They are "^=Control" & "⌥=option" on the newer Mac keyboards. I think it's the control key on older version of tomboy on Mac. Though I used the gnote fork of it before, so I'm not really sure what tomboy used, except the screenshot of it is attached above.

I think you are correct in keeping the keys the same on all platforms. I personally have no issue with using the control key for shortcuts. So thanks for changes.

**Comment by davidbannon** [comment]
AHHH !  I just realised what you were trying to tell me !
The copy and paste and ones to move around the screen are based on Command but the markup (bold, italic etc) are based on Control. I suspect thats horribly confusing for a real Mac user.  Thats the problem, I'm not a real mac user !
I think I need to make it work like I said in previous message ??

Sorry for the confusion ....

Davo

**Comment by xypd** [comment]
Not sure if it different on older Macs, but I'm 90% sure most programs ported from linux use the ^control key now days. If they really want to be more native then yes they use the ⌘command key.

So I'm just one person :), but in my opinion I would recommend either standardize on control for all platforms (not sure what windows uses) or use ⌘command on the Mac.

This of course just my thoughts and not a demand :).

Thanks for your hard work.

**Comment by davidbannon** [comment]
I have implemented, and tested using mostly Command keys on the Mac. I found far too many control keys were already used for some Mac system level and were unavailable.
The exception is Command-H for highlight, Mac uses that to switch windows so, it too is unavailable !
So, the ones that have (tomboy-ng) menu entries are all now described there on the menu so are easy to look up. I'll have to document the remainder. Things like move to end line, beginning line etc.

Ironically, the subject of this ticket, a shortcut key to bullets was easy, all systems use Alt-Arrow !  And I already love it !

Thanks heaps !

**Comment by xypd** [comment]
I'm surprised we did talk about it before. But are you using the English US [keyboard layout](https://en.wikipedia.org/wiki/Keyboard_layout) or some where else. I feel like maybe we see Alt-key and Crtl-key differently in use.

As of right now your using "^ Crtl the control key" for all the shortcut in Tomboy-ng, which is fine for me.

I do agree that using the command key is more challenging, so probably not worth it.

But will have to see once it's in the release :)

Thanks
