### ISSUE TITLE
Tabs don't align

### ISSUE THREAD

**Issue by u9dispose** [tomboy-notes/tomboy-ng#87]
Entering a TAB doesn't take me to the next tab-stop it just moves the cursor over a certain amount.  For the fixed font a TAB is the same as a SPACE.  There should be tab-stops every 4 or 8 ems (an em is the width of a normal sized M).  That makes it possible to easily align text in non-fixed font.

**Comment by davidbannon** [comment]
Thanks for the report u9dispose. Yep, I agree its not really working like tabs should. However, its actually (probably) a hard problem to fix, deep down in KMemo so I am not promising an early fix I'm afraid. Is it something thats causing you a real problem ?

Davo

**Comment by u9dispose** [comment]
Depends upon your definition of "a real problem".  Not it is not a sev 1 or
2 probably a sev 3.  It just makes archiving a pretty layout very difficult.

Robert

**Comment by davidbannon** [comment]
This is an issue listed on the ToDo, its a long termer and no point in leaving it here as an open issue.
