### ISSUE TITLE
Nothing happens after Splash screen > dismiss

### ISSUE THREAD

**Issue by Alex-CodeLab** [tomboy-notes/tomboy-ng#88]
After clicking 'dismiss' the screen disappears and now new window shows up. It is still running in the background though.

![screenshot from 2019-02-01 12-46-59](https://user-images.githubusercontent.com/1678423/52121308-7dec7180-261f-11e9-971e-37b14f7b41b8.png)

Ubuntu 18.04

**Comment by davidbannon** [comment]
Alex, I'm about to release a new version (that will have your requested notebook behavour) but I'd like to resolve this issue, if its an issue, first.
Are you unhappy about the way it starts up ? If so, can you please clarify what you mean ?
Specificially, after you click 'dismiss' - you see another window ?  Does it have a title ?  Do you think it should not be there ?  Are you sure it relates to tomboy-ng ?
Davo

**Comment by Alex-CodeLab** [comment]
the application never shows up. After MainForm there is just nothing. nada.
And leaving it open doesnt help either.

**Comment by davidbannon** [comment]
OK, I thought you were worried by a mystery window opening when you closed the small splash screen.
When you first start -ng, it puts a small green icon on your System Tray, you interact with that.
![tb-ng-icon-u1810](https://user-images.githubusercontent.com/6291248/53275500-71a39200-374f-11e9-9a1e-27bcb7eaf94d.png)
On RedHat flavoured Gnome3 desktops, Gnome developers block the System Tray,  you cannot see that SystemTray Icon and must interact with tomboy-ng via the splash screen. But you are using Ubuntu 18.04 ?  - All my tests say it shows the SystemTray fine. You should always be able to interact with tomboy-ng via the small splash screen, but the SystemTray is far nicer.
**If you cannot see the SystemTray Icon, can you please provide more details about your OS ?  Have you chosen a particular desktop config or set something that might interfere with the SystemTray ?**
When you close the small splash screen, do you press the "Dismiss" button or the close app 'X' button, top right corner ?  The latter will always close the whole application. 
And note, many menu items are initially blank, you must at least confirm where your notes are in the "**Settings**" window.
Davo

**Comment by Alex-CodeLab** [comment]
ubuntu 18.04, no customization.
never seen any icon, so I don't know what you're talking about.

I'm not interested in spending any more time on this, and won't reply anymore.

**Comment by davidbannon** [comment]
Fine Alex. Then it would appear I cannot help you.

**Comment by jagibson** [comment]
@davidbannon I'm seeing the same behavior running Ubuntu 19.04.  The app starts but since there is no icon in the tray it cannot be used.  If I run it with tomboy-ng -g it works but of course I can't dismiss the MainForm window and every time I view a note the MainForm window also has to show.

I'm going to try the "disable wayland" hack to see if that fixes it.

**Comment by davidbannon** [comment]
jagibson, thanks for your report. My own tests with U19.04 indicated (to me) that we did not have this problem. I'm testing on a VM, should, IMHO be a valid test. I'm also very surprised that the disable wayland trick did not help, I was under the impression (on Redhat) that wayland was the key to the problem. So much to learn ....
I am very pleased to see your offer to help debug, this is going to need some help !
Right now I am a very long way from home and traveling with only a little netbook that can barely run its own (U18.04) OS, certainly not a VM. And I can only build 32bit binaries. What I would like to know is which (if any) libappindicator you are loading. I'd like to send you a binary with some extra debugging code but thats hard right now. But you could check to see which libappindicator you have installed please ?  Try this command -
dpkg -l | grep libappindicator <enter>

Either  ver 1 or 3 should work, on my 32bit U18.04 I have both, what do you have ?

Davo

**Comment by jagibson** [comment]
@davidbannon here's my dpkg output
```
dpkg -l | grep libappindicator
ii  libappindicator0.1-cil                     12.10.1+18.04.20180322.1-0ubuntu2        all          CLI bindings for libappindicator
ii  libappindicator1                           12.10.1+18.04.20180322.1-0ubuntu2        amd64        Application Indicators
ii  libappindicator3-1                         12.10.1+18.04.20180322.1-0ubuntu2        amd64        Application Indicators
```
This system has been upgraded from 18.04 -> 18.10 -> 19.04.  I also had unity installed for a while but I've since removed it trying to get tomboy-ng to work.

Kstatusnotifieritem/appindicator support is enabled and when I toggle it off/on my slack indicator goes away/reappears so it seems to be working.

**Comment by davidbannon** [comment]
OK j, thats pretty much what I would expect, it "should" load libappindicator3-1 by first choice and failing that, libappindicator1.  libappindicator3-1 is the unity approach and in my tests worked fine for all Ubuntu and Debian systems. I wonder if the issue relates to updates to 19.04, I tested on only the "out of the box" version, I guess new fixes will have been rolled out by now. As I mentioned, I cannot test myself or send you a binary with debugging until I get home. A couple of weeks I am afraid.
Davo

**Comment by davidbannon** [comment]
Some notes of interest to only me.
GTK2WSFactory function function RegisterCustomTrayIcon() first asks the UnityWSCtrl unit. This unit first tries to load libappindicator_1 if its present, if so, it exits false and lets RegisterCustomTrayIcon() do things the "old way". It only tries to use libappindicator_3 (and the Unity model)  iff libappindicator_1 is not present. Maybe, just maybe, current OS cannot use libappindicator_1 anymore and if its still there, due, perhaps to a series of OS upgrades, bad things happen if its used ??

So, when I again get access to a machine that will run 19.04 in a VM, I need to try and duplicate this issue, maybe forcing the install of a libappindicator_1 if necessary and then force preference for libappindicator_3.

if that works, will need a further upstream bug fix, thats unfortunate in that they won't be seeing my bug fix in Lazarus release for a while so anyone building from source will need to use 'fix' version or apply a patch. Sigh....

**Comment by jagibson** [comment]
> It only tries to use libappindicator_3 (and the Unity model) iff libappindicator_1 is not present.

This did it.  I removed libappindicator_1 and it now shows correctly in the tray!  Thanks for the help and for tomboy-ng!

**Comment by davidbannon** [comment]
Oh, Great !  Thats a really good test, thanks J, I ensure the next release preferes ~_3 so unnecessay to delete the old one. But I suspect deleting the old one will do no harm.  Good news, thanks !

**Comment by davidbannon** [comment]
Have added a patch (to Lazarus LCL, GTK only) to repo that force the use of libappindicator_3 if present. Only tested on my 32bit U18.04 so far but on return to Oz, will test against every Linux I can find ....
(and submit to lazarus bugfixes ...)
Davo

**Comment by jagibson** [comment]
Cool beans!  Once you have new binaries on there I'll give it a shot.

**Comment by davidbannon** [comment]
OK, positive tests done.  Yes indeed, newer distros such as U19.04 do not ship with libappindicator1 and if its there (as a left over from old install or manually installed) v0.22 and earlier of tomboy-ng will, unsuccessfully, try to use it. I have patched LCL to  choose libappindicator3 if its there and that works a treat !  Will have 0.23 with this new behaviour out very soon.
Davo

**Comment by davidbannon** [comment]
OK, can close this at last. V0.23 has a preference for v3 of libappindicator, so far, I can find no down side.  Thanks for your help jagibson
D

**Comment by jagibson** [comment]
no problemo
