### ISSUE TITLE
Search dialog: Word "Search" should disappear when activated

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#9]
- open the Search window
- the word "Search" is written in the text field
-  click into it, it should be automatically cleared
- no user wants to remove it manually

**Comment by davidbannon** [comment]
Agree.
Two things we can do -
1. Delete the content ("search") when user clicks into editbox.
2. Select all the content when user clicks into box, then, when they start typing, content will be replaced with first character typed.
Thoughts ?

**Comment by traumschule** [comment]
first sounds safer to me as some users drag content into it which would not replace marked text.

**Comment by davidbannon** [comment]
Fixed in dfeb374
