### ISSUE TITLE
Quit Issues: Keyboard Shortcut to Quit, etc.

### ISSUE THREAD

**Issue by washere** [tomboy-notes/tomboy-ng#91]
Thanks for this.

**1) Keyboard Shortcut to Quit:**

In Tomboy original we can CAN QUIT FROM ANY PANEL (note, search etc) by:

CTRL + Q

This, keyboard shortcut to quit/exit (CTRL+Q or ALT+F4) is really needed for many: coders, pro writers etc.

**________________________________________________________**

**2) ALT + F4 only quits current Panel, instead of possibility to exit the whole app:**

There needs to be an option in settings so this quits the whole app and exits all panels.
Not just sending it to system tray, but an option in settings to totally exit the app and close all panels.

CTRL + Q is better to eit the whole app because:
similar to Tomboy Original
easier reach for fingers than ALT+F4

**________________________________________________________**

**3): CTRL + W:**

This is the norm for closing only the current panel (Note, search) but not the whole app

**________________________________________________________**

**Comment by davidbannon** [comment]
Again,should be easy. But why would you want to keep exiting the app ?

I have it set to auto start at boot and running non stop ?

(gee, if I knew people would be stopping and restarting all the time, I would not not have worried so much about memory leaks.   -  Joking ....)

Any way, to summarise -
Ctrl Q is quit whole app.
Alt - f4 is close current window ?
Davo

**Comment by washere** [comment]
Hi David,

Thanks for your reply.

There are many reasons for quitting depending on scenarios. Security, workplace environments, restrictions on shared computers etc etc. I can go on.

Basically the classic steps are:

1) Option in settings, default can be checkbox to keep running:

Quitting sends app to system tray [X]

This is the norm in most apps using sys-tray.
Then if someone wants quit to completely shutdown the app, they can uncheck the checkbox. This is standard.

2) CTRL+q
Should be shutdown as in original tomboy, help users migrate.
Also faster & more convenient than the far F4 button (Alt+F4)

3) Close Current Panel (note our search) only:
This should not be Alt+F4 add that's usually app exit standard.
Ctrl+w is a standard for closing a window/page/panel but not apps.
Most coders Peter it too, instead of Ctrl+F4

**Comment by davidbannon** [comment]
I am not sure I want to make this a config option, we already have a mass of config going on and I would like to reduce it if possible. (No, I don't subscribe to the minimalist interface, I assume my users can cope with some complexity but its still nice to make things easy if possible).
So, its a case of defining one keystroke that closes the current window (one of a note, search form, setting form) and another that closes the whole application (without an "are you sure?"). Washere mentions Ctrl-F4, Alt-F4, Ctrl-Q. I've spent too much time at command line to have fixed ideas about this so, discuss !

https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts

Ctrl-F4 and Alt-F4 are vaguely recommended for quit application on Windows, Cmd-Q is widely used on Mac (Cmd often being a metaphor for Alt) and no input from Linux GUI users. (Ctrl-F4 is a Linux command for closing a browser tab but IMHO, that's irreverent here.) 
The wikipedia page does not mention Ctrl-Q. But, by a process of elimination  seems a possibility for quitting the whole application. Ah, and washere says it was the Tomboy way, thats a nice link.
**Decision - Ctrl-Q will close tomboy-ng down on Windows and Linux and Cmd-Q on Mac**

Alt-F4 is also recommended for "Close the focused window " and listed as doing so for Windows and Linux.
Ctrl-W (or Cmd-F11 Cmd-W) are also choice.  In practice, **Alt-F4 does close a note window** in current release of tomboy-ng (at least on Linux). But washere suggests it should not be used as such, its about application exit ??  The wikipedia page does not conclusively agree IMHO.

When time permits, will seek other sources ....

Davo

**Comment by washere** [comment]
Thanks for the report.

CTRL+Q to exit the app COMPLETELY, not just send to tray, is the main feature, as in Tomboy orig for migrating users.

The rest, closing individual panels, are secondary.

Thanks again.

**Comment by washere** [comment]
I attache an image of Keyboard Shortcuts for:

**Microsoft Sticky Notes** 

Some of these shortcuts and features might be food for thought for future development of TomBoy-ng as a reference, some can be useful:

![MS-StickyNotes](https://user-images.githubusercontent.com/5448047/57027173-99254800-6c33-11e9-8c5f-83e6d9954b2f.png)

**Comment by davidbannon** [comment]
Next release, soon, will have a main menu and Ctrl-Q ability on Search, Settings and any open note.
Davo
