### ISSUE TITLE
Dark Mode Not Working

### ISSUE THREAD

**Issue by washere** [tomboy-notes/tomboy-ng#93]
Following from this feedback:

https://github.com/tomboy-notes/tomboy/issues/106

* I have dark mode enabled on Windows 10 Pro (latest Build & updates) and:
* My desktop (as ever) is set to solid color BLACK

as instructed but still the app is a blinding white nd not black (ideal) or even the dark (dark grey).

I tried setting the background to a black solid image but still not working as expected.

Please give us the black theme for this app on Windows too.

Thanks again.

**Comment by davidbannon** [comment]
OK, I thought it was only linux and mac users running with this dark theme thing. I'll see what I can do for windows. I don't expect it to be hard but I don't know my way around windows - I'll have to find out how to set a dark theme myself first !
Davo

**Comment by washere** [comment]
Thanks for the reply David,

This is a very crucial feature. I've made many devs incorporate dark mode/theme into their apps.

For decades there have been forums with thousands of theme mods for Windows, mainly black/dark, which made Windows dark. These modify sys modules (DLL etc) and cause problems with updates. Finally a couple of years ago Microsoft began to introduc dark theme as a result, Dev builds then public. But they held out dark explorer folders until a few months ago.  Even Apple changed its religion of white-only Macs to dark mode option recently.

It's estimated over ninety percent of coders use dark themes, in sublime text or MS VS Code, Atom and other IDEs. See links below. Same with graphics workers and about half professional writers. Less flicker, less stress on eyes, easier to work long hours, longer battery life etc etc. 

Basically with white screens mean you are starting into a light box or huge torch for many hours a day, every day, every week, every year for decades. Many opted out.

In professional graphic workstations, advertising or TV or Hollywood movies cgi etc, the rooms darkening are handled by special lighting engineers. There is a science behind that. Most workers in graphics or long hours of coding or writing have sensitive eyes. That is why most apps now have dark themes on all platforms.

Even Google introduced dark theme for Chrome browser last week.

The "dark reader" extension for Chrome turns any website dark. Just add a word from the URL to its list, eg Google or GitHub etc, and it turns all pages with that word in URL dark.

Turning Windows dark is easy, just press Windows key in keyboard and type: dark.

Also type: night. Nightlight schedules Windows screen to a color tint at night to hours you specify.

Basically if you make Tomboy-ng:

i) DARK MODE (option)
+
ii) Remember Positions+Sizes+Which panels were open in last session

Tomboy-ng will become a powerful note app PLUS index card & visual board that many professionals in many disciplines can use on laptops, ultrabooks and desktop monitor and also spread across multi monitors.

You have done 99% of the work and with these little mods it will go viral. I have post-grad and long existence in UI/UX.

I have other suggestions but these two above (i + ii) need to be done first as basic must haves because once done you will love it yourself too and will see the point in them).

Thanks again for the great work.

https://www.instagram.com/worldcode/

https://www.instagram.com/programmerrepublic/

**Comment by davidbannon** [comment]
OK, a little bit of reading indicates its no easy task. Apparently, unlike Linux, Window's underlying libraries don't respect the desktop colours. On Linux, applications normally 'inherit' colours from the desktop and I needed to manually set only those colours I had manually chosen such as highlight and title colour.
https://www.howtogeek.com/222614/how-to-enable-windows-10s-hidden-dark-theme/
It can be done but will be time consuming. I'll be overseas shortly for just over a month, on trips like this I take only my linux netbook which means I don't have a Windows dev/test platform so, sorry, don't expect anything until, at least June or July.
Then it will depend on how 'adjustable' those Windows colours are. But I will definitly give it a good try !
Davo

**Comment by washere** [comment]
OK, fingers crossed, meanwhile bon voyage and have fun.

Thanks again.

**Comment by washere** [comment]
P.S.
This might be useful:

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.requestedtheme

**Comment by davidbannon** [comment]
Just for the record, a fix for this will not make it into next release, v0.23, sorry. Will make sure its next up....

Davo

**Comment by davidbannon** [comment]
I have had a play with this and, overall, don't think I am achieving much. I can detect that the Dark Theme is selected but we are not getting colors from the Theme Service. Seems that MS has implemented this Dark Theme switch as a separate thing. So, no suggested colors, no guidance from the OS.  I can manually change some parts of the GUI but not some other, critical ones. For example, Menu colors are not accessible at the application level (or, at least my application...). And even some parts of buttons cannot be changed. This is not completely an LCL issue, these colors do change on Linux/Mac when the desktop theme indicates they should. It appears to me that as Windows could not change themes at all until recently, no one has yet bothered, to implement support for it. And, there seems some skepticism that Microsoft has finished this change so its probably too early to start any low level work.

I do have, now, some dark colors for splash screen, note edit screen and search screen but not settings and all the ancillary ones. And all menus are still black text on white background.  I am really not sure if its productive to proceed.

If you would like to have a play with what I have so far, please let me know.

Davo

**Comment by washere** [comment]
Thanks Davo,

I think this is important because many coders, if not most, and writers only work with dark theme apps these days. Specially if it's up for reference on the desktop constantly like tomboy-ng would be. That's why dark themes are taking over the world in many apps specially for Pro users. So I think your soldiering on if the terrain is not easy is appreciated.

The main thing is the notes themselves in read-only mode be dark or even better black background. Menus and even editing-mode backgrounds are secondary. The raison d'etre of tomboy notes is so they're up for reference as secondary layer on desktop. 

These days with large monitors and dual/multi monitors, even more so. Even the next Microsoft surface laptop is dual monitor! So the main thing is if the notes, in read-only mode (not necessarily edit mode), are dark/black in their background colors, while one works in Word/MS VS Code/Atom/sublime text/Scrivener/whatever app.

So whatever you can do will be appreciated and I'll test and feedback.

Thanks again.

**Comment by davidbannon** [comment]
OK, I have posted a test binary into the v0.23 repository.  You can download, unzip and run it from where ever its unzipped to, stop your existing tomboy-ng v0.23 first and the dark one will pick up all the real ones settings. I have doctored only the splash screen, search and edit forms.  Menus and buttons are quite incorrect even on those three forms and there is little I can do about that until MS sorts out its dark theme and passes the correct colours down through the OS.

Davo

**Comment by washere** [comment]
Hi Davo,

Just saw this today and tried it. It basically does 95% of dark mode already:

* Dark Notes
* Dark SearchForm (central command)

The rest are minor. I think you should build this into settings of standard release as "Dark Mode" in settings. Many would miss it as it is and would love to use it.

On  the dark mode problems with Microsoft: there are two ways people make dark mode apps for Windows. One is hard code the dark interface, either as sole look or as option next to light mode.

The second way is using MS guidelines for the app to inherit the mode from the Windows theme settings.  So if one has a dark mode set up in windows, these class of apps actually inherit the dark mode and there is no choice.

I have not coded apps for windows for well over a decade and also do not know what libkits or dev platform you are using. So for either way it depends on that. And then finding the relevant MS references to see what can be done wrt your dev platform. I know people using the big two, qT & GTK, are making dark mode apps every day.

I hope you use the dark mode of ng to see how much easier it is on your eyes.
Many coders would use it NOW regularly as their desktop corkboard if they knew the dark mode was there. Do not make a mistake, this dark mode has huge potential. Takes time for word to spread. 

Some points:

* If the windows frames, borders & scrollbars were to be dark, it would be 99% done, as menus are rarely used. I know, this is where you are hitting the brick wall.

* The note name on first line is too dark to read. Can it be made into a lighter shade of blue?
Either as an option insettings or just hack it as default lighter blue in the current dark?

____________________________________________________
OFF_TOPIC: KB Shortcuts:

* Pro users, and coders, always use keyboard shortcuts: ALL MENU OPTIONS SHOULD REALLY HAVE THEM

* Can we have the following as standard:

1) CTRL+F4 to close current note window (as is already plus CTRL+W to do the same, this is sort of norm, much faster too as W is nearer CTRL)

2) ALT + F4 Exits the whole app
ALSO: Should have a setting checkbox option: On exiting App, send to systray/minimize
If unchecked, it shuts down the app comlpletely, instead of just sending to tray

* Can you add to the cogwheel icon menu on each note: Settings
Then can access settings from within notes

* In SearchForm: Have ALT+F drop down the (MAIN) menu for the top-left icon (arrow on document logo icon)

I have more UI/UX ideas but later. The way it remembers from previous session: which notes were open, where on screen etc is brilliant.

It is slowly getting to be a very useful beast. Thanks for all the hard work.

**Comment by davidbannon** [comment]
Hi washere, glad you like it (dark mode) so far.  You won't convince me to use it, it makes for serious headaches !  Funny, I have asked around in the two developer areas I lurk and very few use or want a dark theme. Mostly linux people and they have had automatic dark themes available to them for some time. 

Anyway, the issue on Windows is that MS does not pass the dark colours down to new windows as they open (like Linux and Mac do and have done for very many years). An app makes a particular (Microsoft) call to open a window and gets the colour that the OS determines. I then change the colours that I can.  As Microsoft is only just catching up to this dark theme idea, I expect it will be some time before they make the necessary information either available, or better yet, automatically set.  But its in their hands. My research indicates that other apps are faced with the same problem. I have no desire to dive down below the API and do owner draw stuff I'm afraid, it would be slower, error prone and difficult to maintain.

The maintainers of Lazarus's LCL (that tomboy-ng is built on) have indicated they see no immediate prospect of providing further means to change API provided colours, want to wait until Microsoft have sorted their act out.

Maybe you need to move over to Linux washere ?   Most distros have built in dark themes and its dead easy to design your own :-)

Yep, I agree the dark blue heading on a black is too hard to see, pretty sure thats something I can fix. Same thing for links to other notes.

On topic of keyboard short cuts, please see #91, again, I am limited somewhat in making something that still feels a lit like the original Tomboy and also driven by need to feel like Linux, Mac AND Windows all at same time. I reason that tomboy-ng's main claim to fame is its cross platformness, so users are likely to be switching platforms, I don't want too may platform dependent commands. 

I agree opening the settings window from a note would be good, I have wished for that myself on occasions, should be easy enough .....

Development will be a bit slow for awhile, I'm traveling and won't be home with my familiar tools for a couple of months.
 
Thanks for your input mate !

Davo

**Comment by xypd** [comment]
Running dark theme via OS system settings, but don't see a dark theme in tomboy-ng. Am I missing something? Thanks.

**Comment by davidbannon** [comment]
On a Mac ?  Think you are a Mac user ?
I have not tested it on a Mac at all. Maybe the Linux code would pick up external settings but but I might have made that Linux only. Must admit, did not consider Mac in this context.

**Comment by xypd** [comment]
Ah, okay. Sorry I thought this was possibly for all platforms. No worries if you didn't plan for this. Just wanted to make sure I wasn't missing something.

**Comment by davidbannon** [comment]
No reason why it does not work in the Mac, its just that I have not tried it. In fact, my Mac experience being what it is, I don't even know how to set my Mac to a dark theme.....

Been having so much trouble getting the next release out, don't want to add another variable right now. Maybe the next release ....

**Comment by xypd** [comment]
Sure thing, just put it on the long term list I guess

**Comment by davidbannon** [comment]
Hmm, I am afraid I cannot, at this stage, pursue this issue on the Mac. My Mac test bed is a Sierra and apparently it does not have the ability to set a Dark Theme. Wow, mac ........

Maybe after this release, I'll risk updating my OS, but its an old machine and I am not a keen Mac user, hmm....

Davo

**Comment by davidbannon** [comment]
Origional topic, dark on Windows is somewhat improved in 0.24.
;-0
