### ISSUE TITLE
no x86_64 rpm

### ISSUE THREAD

**Issue by edgreenberg** [tomboy-notes/tomboy-ng#95]
There is no x86_64 rpm available, only i386 and amd64. Can an x86_64 rpm be added?

**Comment by davidbannon** [comment]
Thanks edgreenberg, I think the first entry is the one you are looking for -

tomboy-ng-0.22-2.amd64.rpm

Can you not see that one ?

Davo

**Comment by davidbannon** [comment]
Hmm, after re-reading this question, maybe I did not answer it very well initially.
edgeenberg, the "amd64" binary is the one you want, it works fine with the Intel chips as well. Its a historical accident that amd got their name in there, they actually released a 64bit x86 chip before Intel and the industry just adopted the that name.
Closing.
