### ISSUE TITLE
Bug: New lines after title line are not changing back to normal text

### ISSUE THREAD

**Issue by jagibson** [tomboy-notes/tomboy-ng#98]
If I write three lines rapidly tomboy-ng does not change the text from the second line down to normal text but keeps the blue hyperlink text along with the large font.

Here is how I can reproduce the bug

Create a new note
Click on the second line under the title
Press backspace to go to the top (title) line
Press Enter again and type on the next line
Before the text turns black press enter again
All lines now remain in the same format as the title line

**Comment by davidbannon** [comment]
Yeah, sorry I have not fixed that yet, its actually an old bug, relates to #26 
Thanks for the report but it won't make it to next release I am afraid, trying to get it out now.
(The text is correctly formatted when next the note is loaded. So, its not a permanent error.)
Davo

**Comment by jagibson** [comment]
Cool beans.  I didn't see #26.   It's not a big deal just thought I'd let you know.

**Comment by davidbannon** [comment]
Fixed in v0.24, thanks for report.
